import type { CaseStudy } from "./knowledgeTypes";

export const CASE_STUDIES_2: CaseStudy[] = [
  {
    slug: "itc-echoupal-agri-supply-chain",
    title: "ITC's e-Choupal direct farmer procurement network",
    kind: "build",
    industrySlug: "agriculture-agribusiness",
    strategySlug: "platform-strategy",
    summary: "A conglomerate built a network of village internet kiosks to connect directly with farmers, bypassing several layers of traditional intermediaries in agricultural procurement.",
    story: [
      "This large diversified conglomerate, needing reliable agricultural commodity procurement for its business, built a network of internet-enabled kiosks in villages, each managed by a trained local farmer, giving surrounding farmers direct access to real-time crop prices, weather information, and farming best practices.",
      "Before this network, farmers typically sold through several layers of intermediaries at village markets, with price discovery happening far from the farmer and information asymmetry generally favouring traders over producers.",
      "By giving farmers direct price transparency and, eventually, the option to sell directly to the company at their village rather than transporting produce to a distant market, the network reduced the number of intermediary layers and associated costs for participating farmers, while giving the company more reliable, traceable procurement.",
      "The model became a widely studied example of using accessible technology to restructure an agricultural supply chain, expanding to cover a large number of villages and multiple crop categories over time.",
    ],
    lesson: "Giving the weakest link in a supply chain direct access to information and a direct channel to buyers can restructure the entire chain's economics — the technology's real value was transparency and access, not novelty.",
  },
  {
    slug: "infosys-global-delivery-model",
    title: "Infosys and the global delivery model",
    kind: "build",
    industrySlug: "it-ites-services",
    strategySlug: "economies-of-scale",
    summary: "An Indian IT services company pioneered a delivery model that split work across time zones and cost centres, becoming a template the wider Indian IT industry adopted.",
    story: [
      "In the early years of the Indian IT services industry, most software work for international clients required consultants to travel and work on-site at the client's location, which was expensive and difficult to scale.",
      "This company developed and refined what became known as the global delivery model — splitting project work between smaller onsite teams (client-facing, requirements-gathering) and larger offshore teams in India (development, testing) connected through disciplined processes and communication protocols.",
      "This structural innovation let the company offer international clients significant cost advantages while maintaining quality, by doing most of the labour-intensive work in a lower-cost location without sacrificing coordination with the client.",
      "The model became the template the broader Indian IT services industry adopted and refined, contributing significantly to India's emergence as a major global hub for IT services and business process outsourcing.",
    ],
    lesson: "A structural innovation in how work is organised and delivered — not just what is delivered — can become a durable competitive advantage and, eventually, an entire industry's template.",
  },
  {
    slug: "satyam-fraud-collapse",
    title: "Satyam Computers' accounting fraud and collapse",
    kind: "failure",
    industrySlug: "it-ites-services",
    summary: "A major Indian IT services company collapsed after its founder admitted to years of systematically falsified accounts, becoming one of the country's most significant corporate governance failures.",
    story: [
      "This IT services company had grown into one of India's largest, with a strong public profile and a listing on international stock exchanges, appearing by its reported financial statements to be a genuinely successful, fast-growing business.",
      "In a public admission, the company's founder revealed that the company's accounts had been systematically falsified for years — inflating revenue, profit, and cash balances that did not actually exist, in one of the largest corporate accounting frauds in Indian corporate history.",
      "The revelation triggered an immediate collapse in the company's stock value, a full change in leadership and ownership through a government-supervised process, criminal proceedings against those involved, and a broader crisis of confidence in Indian corporate governance and auditing practices at the time.",
      "The company was ultimately acquired and restructured under new ownership, and the case became a landmark reference point for corporate governance reform, auditing standards, and whistleblower protections in India.",
    ],
    lesson: "Financial statements are only as trustworthy as the governance and audit systems behind them — a business built on fabricated numbers can maintain the appearance of success for years, but the eventual reckoning is total, not partial.",
  },
  {
    slug: "cipla-affordable-medicine-access",
    title: "Cipla's affordable access strategy in global medicine",
    kind: "build",
    industrySlug: "pharma",
    strategySlug: "cost-leadership",
    summary: "A pharmaceutical company made a strategic decision to produce and sell life-saving medication at a small fraction of the price charged elsewhere, dramatically expanding access in price-sensitive markets.",
    story: [
      "In the early 2000s, life-saving antiretroviral medication for a major global health crisis was priced by international pharmaceutical companies at a level that made it inaccessible to the vast majority of patients in developing countries, despite the urgent and widespread need.",
      "This Indian pharmaceutical company's leadership made a deliberate strategic decision to manufacture generic versions of the needed combination therapy and offer it at a price dramatically lower than the prevailing international price — a fraction of what was being charged elsewhere at the time.",
      "This move drew significant international attention and controversy, including legal and diplomatic pressure, but also fundamentally shifted the global conversation about medicine pricing and access in developing markets, contributing to broader international efforts to expand affordable access to essential medication.",
      "The company built a lasting reputation and business position around affordable, accessible medicine, demonstrating that a lower-price strategy in a life-critical category could be both a genuine public health contribution and a viable long-term business model, given sufficient manufacturing scale.",
    ],
    lesson: "In categories where affordability is a genuine barrier to access, an aggressive low-cost strategy can open an enormous underserved market while making a real difference — provided the underlying manufacturing scale and quality can sustain it.",
  },
  {
    slug: "lt-engineering-diversification",
    title: "Larsen & Toubro's engineering-led diversification",
    kind: "build",
    industrySlug: "construction-infrastructure",
    summary: "An engineering and construction conglomerate built durable market leadership by diversifying across infrastructure, defence, technology, and heavy engineering, rather than remaining a single-category contractor.",
    story: [
      "This engineering and construction company built its foundation on heavy engineering and construction project execution, developing deep in-house technical capability rather than depending heavily on external subcontractors for core engineering work.",
      "Over decades, the company deliberately diversified into adjacent and complementary sectors — infrastructure development, defence manufacturing, technology services, and heavy equipment — using its core engineering capability as the common thread across otherwise very different end markets.",
      "This diversification reduced the company's dependence on any single sector's cycle — a downturn in one area (commercial construction, for instance) could be partially offset by stability or growth in another (defence, infrastructure) — while the shared engineering capability meant diversification didn't require starting from zero in each new area.",
      "The company became one of India's largest and most diversified engineering conglomerates, frequently cited as an example of how deep technical capability, rather than a single product category, can be the actual basis of a diversified industrial business.",
    ],
    lesson: "Diversification works best when it's built around a genuine shared capability — in this case, deep engineering expertise — rather than unrelated businesses bolted together purely for scale.",
  },
  {
    slug: "hotstar-ipl-streaming-scale",
    title: "Hotstar's live-sports streaming scale during the IPL",
    kind: "build",
    industrySlug: "media-entertainment",
    strategySlug: "platform-strategy",
    summary: "A streaming platform built its dominant market position substantially around exclusive live cricket streaming rights, repeatedly setting global live-streaming concurrency records during major tournaments.",
    story: [
      "This Indian streaming platform built much of its early scale and market position around securing exclusive digital streaming rights to major cricket tournaments — a content category with an enormous, passionate, and highly engaged existing audience in India.",
      "Live sports content, unlike most on-demand entertainment, effectively demands to be watched in real time, which meant the platform could not rely on catalogue depth alone — it had to solve genuinely difficult technical challenges around streaming to extremely large simultaneous audiences without buffering or failure.",
      "During peak tournament matches, the platform repeatedly set and broke global records for concurrent online viewership, requiring significant, sustained investment in streaming infrastructure specifically built to handle these extreme, predictable demand spikes.",
      "This live-sports anchor gave the platform a recurring, highly engaged audience during the tournament season that it could then use to cross-promote its broader on-demand entertainment catalogue, illustrating how one category of exclusive content can anchor a much broader platform strategy.",
    ],
    lesson: "Live, exclusive content that an audience is already passionate about can anchor an entire platform strategy — it solves the cold-start problem of building an audience and gives a recurring reason to return that on-demand content alone struggles to replicate.",
  },
  {
    slug: "nykaa-beauty-marketplace",
    title: "Nykaa's build from beauty content to beauty marketplace",
    kind: "build",
    industrySlug: "beauty-wellness",
    strategySlug: "niche-domination",
    summary: "A beauty and wellness e-commerce company built trust and audience through content and expertise before scaling into a full retail marketplace, rather than starting with pure transactional selling.",
    story: [
      "This beauty and wellness company built its early audience substantially through content — product reviews, tutorials, and expert beauty advice — establishing credibility and trust with a beauty-conscious audience before that audience was ever asked to make a purchase.",
      "This content-first approach addressed a genuine gap in a category where online shoppers were often uncertain about product authenticity and suitability for their specific skin type or concern — trusted content and expert curation reduced that uncertainty in a way pure product listings couldn't.",
      "Building on this trusted audience, the company expanded into a full e-commerce marketplace spanning a wide range of beauty and wellness brands, and eventually into its own private-label product lines, leveraging the customer insight and trust built through its content and curation business.",
      "The company's growth demonstrated a specific niche-domination path: dominate a narrow, trust-dependent function (content and curation) within a category first, then expand into full commerce once that trust and audience is genuinely established.",
    ],
    lesson: "In categories where trust and authenticity concerns are high, building genuine expertise and content credibility before asking for a purchase can be a more durable foundation for a marketplace than transactional selling from day one.",
  },
  {
    slug: "reliance-digital-electronics-retail",
    title: "Reliance Digital's organised electronics retail scale-up",
    kind: "build",
    industrySlug: "electronics-retail",
    strategySlug: "economies-of-scale",
    summary: "A large conglomerate's electronics retail chain used scale purchasing power and an omnichannel model to compete against both traditional local electronics shops and pure online retailers simultaneously.",
    story: [
      "Entering the organised electronics retail category, this large retail chain leveraged its parent conglomerate's scale and purchasing power to negotiate better terms with electronics manufacturers than smaller, independent electronics retailers could typically access.",
      "The chain built an extensive physical store network across a wide range of city tiers, while simultaneously investing in a genuine omnichannel experience — allowing customers to research online and complete purchases either online or in-store, with consistent pricing and inventory visibility across channels.",
      "This combination let the chain compete effectively against both traditional local electronics shops (on selection, transparent pricing, and after-sales service) and pure online retailers (on the ability to see, touch, and get immediate service for higher-consideration electronics purchases).",
      "The chain's scale also let it invest more heavily in after-sales service infrastructure than smaller competitors could sustain, turning service quality into a genuine differentiator in a category where product specifications alone are easily matched by competitors.",
    ],
    lesson: "Scale purchasing power combined with a genuine omnichannel experience can let a retailer compete simultaneously against both smaller traditional competitors and pure online players, each of which alone might otherwise have a distinct advantage.",
  },
  {
    slug: "hatsun-agro-dairy-expansion",
    title: "Hatsun Agro's dairy procurement and processing scale-up",
    kind: "build",
    industrySlug: "dairy-livestock",
    strategySlug: "geographic-rollout",
    summary: "A private dairy company built one of India's largest private dairy businesses by investing heavily in direct farmer procurement networks and cold chain infrastructure in specific regional markets before expanding further.",
    story: [
      "This dairy company built its business around a private-sector procurement model, establishing direct collection relationships with a large number of individual dairy farmers in its home region, rather than depending primarily on cooperative structures common elsewhere in the industry.",
      "Significant investment in cold chain infrastructure — collection points, refrigerated transport, and processing capacity — was central to the company's ability to reliably move perishable milk from thousands of small individual farmers to processing facilities without spoilage losses undermining the economics.",
      "Rather than expanding broadly and thinly across many regions at once, the company built deep procurement and distribution density in its core regional markets before methodically expanding into new geographic regions, applying the same procurement and cold-chain playbook each time.",
      "The company grew into one of India's largest private dairy businesses, with a broad portfolio spanning liquid milk, ice cream, and other value-added dairy products, demonstrating that private, farmer-direct procurement could scale alongside the more traditional cooperative dairy model.",
    ],
    lesson: "In a perishable, cold-chain-dependent category, building genuine regional density and procurement reliability before expanding geographically protects the operational discipline that a thin, over-extended rollout would put at risk.",
  },
  {
    slug: "fabindia-handicraft-exports",
    title: "Fabindia's handicraft retail and artisan network model",
    kind: "build",
    industrySlug: "handicrafts-exports",
    strategySlug: "brand-moat",
    summary: "A retail company built a nationally and internationally recognised brand around traditional Indian handicrafts and textiles by building a large network of rural artisan producers directly into its supply chain.",
    story: [
      "This retail company built its business model specifically around sourcing directly from a large network of rural artisans and craftspeople across India, rather than through intermediary trading layers common in the traditional handicraft supply chain.",
      "This direct-sourcing model required significant investment in working with artisan communities on quality consistency, design adaptation for contemporary retail customers, and reliable payment and ordering systems — addressing exactly the standardisation-without-industrialisation challenge the category faces.",
      "The company built its retail brand identity explicitly around the authenticity and craftsmanship of its supply chain, making the artisan-sourced, handmade nature of its products a central part of its marketing and brand story rather than a background operational detail.",
      "This model let the company build a recognisable national retail brand while simultaneously supporting a large network of rural artisan livelihoods, demonstrating that authenticity-led sourcing and commercial retail scale aren't necessarily in tension if managed deliberately.",
    ],
    lesson: "Making the authenticity and story of a fragmented, artisan-based supply chain the actual center of the brand — rather than something to standardise away — can be the differentiator that justifies premium retail pricing.",
  },
  {
    slug: "blendtec-will-it-blend-guerrilla",
    title: "Blendtec's 'Will It Blend?' viral content campaign",
    kind: "build",
    industrySlug: "manufacturing",
    strategySlug: "viral-challenge-marketing",
    summary: "A blender manufacturer with a minimal marketing budget built massive brand awareness by filming its founder blending unusual objects — from marbles to smartphones — in a long-running viral video series.",
    story: [
      "This blender manufacturer, competing against far larger and better-funded kitchen appliance brands, had a genuinely durable product but almost no consumer brand recognition and a marketing budget too small to compete on conventional advertising.",
      "The company's founder began filming himself blending unusual and unexpected objects — golf balls, glow sticks, and eventually a smartphone — in the company's own blenders, demonstrating the product's durability and power in a way that was inherently entertaining and shareable, not just a technical demonstration.",
      "The video series required minimal production budget compared to traditional advertising, but generated enormous organic viewership and sharing precisely because each new video answered a genuinely funny and curious question — will it actually blend this specific unlikely object — that people wanted to see resolved.",
      "The campaign ran for years, generating far more brand awareness and product credibility per dollar spent than the company's conventional advertising budget ever could have, becoming a widely cited example of low-budget content that outperforms expensive advertising through genuine shareability.",
    ],
    lesson: "A small marketing budget doesn't have to mean small reach — content built around genuine curiosity and entertainment value can generate organic distribution that a much larger conventional advertising budget struggles to match.",
  },
  {
    slug: "tata-jlr-acquisition-negotiation",
    title: "Tata Motors' acquisition of Jaguar Land Rover",
    kind: "build",
    industrySlug: "manufacturing",
    strategySlug: "batna-leverage",
    summary: "An Indian automotive manufacturer acquired two storied but struggling British luxury car brands from a global manufacturer, then invested patiently to turn them into a major profit engine rather than integrating them hastily.",
    story: [
      "This Indian automotive manufacturer, known primarily for affordable commercial and passenger vehicles in its home market, acquired two well-known British luxury and off-road vehicle brands from a global automotive manufacturer that was looking to divest them amid its own financial pressures.",
      "The acquisition was met with considerable scepticism at the time — critics questioned why a manufacturer known for affordable vehicles would take on two loss-making luxury brands with significant legacy costs and cultural differences from its home market operations.",
      "Rather than aggressively integrating the acquired brands into its existing operations or imposing its own manufacturing philosophy immediately, the parent company largely preserved the acquired brands' independent design and engineering culture, investing patiently in new product development and quality improvement over several years.",
      "The acquired brands eventually became a major source of profit for the parent company, at times contributing more to overall profitability than its home-market vehicle business, becoming a widely studied example of a successful cross-border acquisition built on patience and cultural preservation rather than immediate integration.",
    ],
    lesson: "A successful acquisition, especially across very different market and cultural contexts, often depends more on patient investment and preserving what made the acquired business valuable than on rapid integration into the acquirer's existing playbook.",
  },
  {
    slug: "festive-sale-anchoring-ecommerce",
    title: "Festive season e-commerce sales and price anchoring",
    kind: "build",
    industrySlug: "d2c-ecommerce",
    strategySlug: "anchoring-effect",
    summary: "Major Indian e-commerce platforms built their single largest revenue events of the year around festive season sales that combine deep discounts, urgency messaging, and price anchoring at enormous scale.",
    story: [
      "India's major e-commerce platforms built large-scale annual festive season sale events — timed around major shopping festivals — that have grown into each platform's single largest revenue event of the year, sometimes generating a meaningful share of annual e-commerce sales within a few days.",
      "These events are built around a combination of pricing psychology techniques operating simultaneously: displaying original prices prominently alongside discounted prices to anchor perceived value, count-down timers and limited-quantity messaging to create urgency, and early access for loyalty program members to reward existing engaged customers.",
      "The scale of these events also requires significant operational preparation months in advance — inventory pre-positioning, logistics capacity planning, and seller onboarding — since a poorly executed high-demand event can generate as much negative publicity (stockouts, delivery failures) as a well-executed one generates positive buzz.",
      "The consistent success of these annual events, now closely watched and anticipated by both consumers and sellers, illustrates how pricing psychology combined with genuine operational readiness can be productised into a predictable, repeatable annual revenue driver rather than a one-off promotional tactic.",
    ],
    lesson: "Pricing psychology techniques compound when used together deliberately and at scale — anchoring, urgency, and loyalty rewards combined can turn a single sale event into a business's most important annual revenue driver, provided operations can actually deliver on the demand generated.",
  },
];
