import type { StarterKitLink } from "./knowledgeTypes";

export type ScheduleDay = {
  day: number;
  week: number;
  title: string;
  trackFocus: string;
  sessionGoal: string;
  topics: string[];
  frameworks: string[];
  activity: string;
  deliverable: string;
  relatedLink?: StarterKitLink;
};

export const SCHEDULE_WEEK_LABELS: Record<number, string> = {
  1: "Week 1 — The Paarth reset",
  2: "Week 2 — Customer, problem & market intelligence",
  3: "Week 3 — Positioning, offer & differentiation",
  4: "Week 4 — Digital identity, content & trust",
  5: "Week 5 — Demand generation & content systems",
  6: "Week 6 — Demand systems & content operations",
  7: "Week 7 — Campaigns, creative marketing & attention",
  8: "Week 8 — Sales, persuasion & conversion",
  9: "Week 9 — Funnels, lead magnets & website thinking",
  10: "Week 10 — Business execution & growth thinking",
  11: "Week 11 — Operations, systems & execution discipline",
  12: "Week 12 — Team building, hiring & leadership communication",
  13: "Week 13 — KPIs, dashboards & decision-making",
  14: "Week 14 — Business model strength & leadership identity",
  15: "Week 15 — Capstone build, defense & Paarth boardroom",
};

export const FLAGSHIP_SCHEDULE: ScheduleDay[] = [
  // ===== WEEK 1 =====
  { day: 1, week: 1, title: "The Paarth opening: why this isn't a normal institute", trackFocus: "Leadership + orientation", sessionGoal: "Break the course mindset and introduce Paarth as a builder environment.", topics: ["What separates information, skill, capability and real leverage", "Why learning without execution changes little", "The shift from learner identity to operator identity"], frameworks: ["Builder vs learner identity model", "Personal capability stack"], activity: "Write a one-page intent note on why you're here and what you want to build.", deliverable: "Personal intent note and baseline self-introduction video." },
  { day: 2, week: 1, title: "Understanding the modern business landscape", trackFocus: "Business thinking", sessionGoal: "Show how businesses actually grow today and where opportunity exists.", topics: ["Attention, trust, offer, conversion, retention as the five growth levers", "Traditional vs digitally accelerated business", "Agency, product, service, platform and education business models"], frameworks: ["Business growth engine overview", "Attention-trust-conversion-retention model"], activity: "Map ten admired businesses and identify how each actually makes money.", deliverable: "Business model observation sheet." },
  { day: 3, week: 1, title: "Personal vision, ambition & builder identity", trackFocus: "Leadership", sessionGoal: "Help students define their ambition and operating direction.", topics: ["Ambition vs confusion", "Career paths: founder, marketer, strategist, operator", "Why clarity creates speed"], frameworks: ["Personal ambition mapping", "Identity-habits-outcomes model"], activity: "Build a 3-year business or career map.", deliverable: "Personal vision map and future operator identity statement." },
  { day: 4, week: 1, title: "AI orientation for business builders", trackFocus: "AI", sessionGoal: "Reframe AI from a novelty into a genuine business operating advantage.", topics: ["Where AI genuinely helps: research, writing, planning, content, strategy", "What AI should never replace: judgment, ethics, empathy", "The research-draft-refine-deploy workflow"], frameworks: ["AI leverage stack", "Human judgment + AI execution model"], activity: "Test AI across five real tasks: idea research, content, competitor analysis, offer improvement, landing page outline.", deliverable: "Personal AI toolkit sheet and first prompt notebook." },
  { day: 5, week: 1, title: "Personal operating system: discipline, focus & execution", trackFocus: "Leadership", sessionGoal: "Build the habits needed to survive a demanding, self-directed program.", topics: ["Why talented people stay average: distraction, weak routines", "Deep work, decision fatigue and energy management", "Weekly planning and review systems"], frameworks: ["Personal operating system", "Build-market-learn-reflect weekly structure"], activity: "Run your first 7-day execution tracker.", deliverable: "Personal operating system sheet and daily performance scorecard." },
  { day: 6, week: 1, title: "Communication, presence & the first leadership drill", trackFocus: "Leadership + communication", sessionGoal: "Start shaping how students speak, present and carry conviction.", topics: ["Leadership begins with communication clarity", "Confidence vs authority vs arrogance", "Structure: context, problem, point, proof, next step"], frameworks: ["Speak-with-structure framework", "Confidence-through-preparation model"], activity: "Deliver a 60-second stage introduction and receive peer feedback.", deliverable: "Communication baseline recording and personal authority checklist." },

  // ===== WEEK 2 =====
  { day: 7, week: 2, title: "Customer research: stop guessing, start observing", trackFocus: "Marketing", sessionGoal: "Teach real customer pain research instead of founder assumption.", topics: ["What customer research actually means", "What customers say vs what they do", "Pain, aspiration, anxiety, objection, trigger"], frameworks: ["Customer pain map", "Jobs-to-be-done lens"], activity: "Interview three real potential customers with a structured script.", deliverable: "Customer research sheet and pain-point board v1." },
  { day: 8, week: 2, title: "Market observation lab", trackFocus: "Field execution + marketing", sessionGoal: "Train the eye to see how real businesses sell, serve and build trust.", topics: ["What to observe: offer clarity, staff behaviour, pricing cues, trust signals", "Market visitor vs market observer"], frameworks: ["Business observation checklist", "Offer-proof-process-experience audit"], activity: "Visit two or three businesses in teams and audit how they attract attention and lose customers.", deliverable: "Field market audit sheet and photo/video observation log." },
  { day: 9, week: 2, title: "Design thinking for business builders", trackFocus: "Innovation", sessionGoal: "Teach structured problem-solving from unmet needs.", topics: ["Empathy, define, ideate, prototype, test", "How relevance comes from solving a sharper problem"], frameworks: ["Design thinking", "Start-with-unmet-need model"], activity: "Convert field observations into ten written problem statements.", deliverable: "Problem statement sheet and design thinking canvas." },
  { day: 10, week: 2, title: "Persona, buyer mindset & decision-making unit", trackFocus: "Marketing", sessionGoal: "Move from vague audience thinking to real persona clarity.", topics: ["What a persona is and isn't", "Who influences a purchase decision", "Luxury buyer vs price-sensitive buyer behaviour"], frameworks: ["Persona canvas", "Decision making unit"], activity: "Build one detailed persona for a chosen business and identify their objections.", deliverable: "Persona deck and decision-unit map." },
  { day: 11, week: 2, title: "Competitor intelligence & category mapping", trackFocus: "Marketing + strategy", sessionGoal: "Teach students to read a category and find white space.", topics: ["Category leaders vs category noise", "Auditing offer, messaging, positioning, proof", "Finding what nobody in a category is saying"], frameworks: ["Competitor audit matrix", "White-space opportunity grid"], activity: "Run a competitor teardown of five brands in one industry.", deliverable: "Competitor matrix and category insight note." },
  { day: 12, week: 2, title: "AI research lab: market, competitor & customer intelligence", trackFocus: "AI + marketing", sessionGoal: "Use AI to speed up and deepen market research.", topics: ["AI prompts for persona and competitor mapping", "Verifying AI outputs instead of trusting them blindly"], frameworks: ["AI-assisted research workflow", "Human verification checklist"], activity: "Build a competitor report and convert interview notes into pain themes using AI.", deliverable: "AI research dossier and prompt library v2." },

  // ===== WEEK 3 =====
  { day: 13, week: 3, title: "Positioning fundamentals", trackFocus: "Marketing + strategy", sessionGoal: "Teach students to define where a brand should stand in the market.", topics: ["Perception vs product", "Why weak positioning makes marketing expensive", "Levers: niche, expertise, promise, method, proof"], frameworks: ["Positioning triangle: audience + promise + proof"], activity: "Reposition a weak local business and write first-draft positioning lines.", deliverable: "Positioning draft v1 and positioning swipe file.", relatedLink: { kind: "framework", slug: "positioning-statement", label: "Positioning rewrite" } },
  { day: 14, week: 3, title: "SWOT, strategic drivers & business reality", trackFocus: "Leadership + strategy", sessionGoal: "Teach strategic thinking instead of emotional decision-making.", topics: ["SWOT done properly", "Internal vs external reality", "Avoiding generic strategy decks"], frameworks: ["SWOT", "Strategic driver map"], activity: "Run a SWOT for a real local business and identify three strategic drivers.", deliverable: "SWOT report and strategic driver map.", relatedLink: { kind: "tool", slug: "swot-builder", label: "SWOT builder" } },
  { day: 15, week: 3, title: "Offer engineering: build something people want", trackFocus: "Marketing + business design", sessionGoal: "Show how to shape an offer that feels compelling and buyable.", topics: ["Offer vs product vs service vs package", "Bonuses, risk reversal, urgency, proof", "Offer laddering and premium packaging"], frameworks: ["Offer stack framework", "Offer ladder model"], activity: "Rewrite three boring offers into stronger ones.", deliverable: "Offer stack sheet and offer ladder." },
  { day: 16, week: 3, title: "Messaging & copy foundations", trackFocus: "Marketing", sessionGoal: "Help students turn strategy into words that move people.", topics: ["Messaging hierarchy: audience, pain, promise, proof, CTA", "Writing clearly vs writing cleverly", "Headline fundamentals"], frameworks: ["Message pyramid", "Hook-pain-promise-proof-action structure"], activity: "Rewrite weak landing page copy and write ten hooks for the same offer.", deliverable: "Messaging framework sheet and hero copy draft." },
  { day: 17, week: 3, title: "AI copy lab: offer, ads, landing pages", trackFocus: "AI + marketing", sessionGoal: "Teach AI-assisted messaging without sounding generic.", topics: ["Prompting for ad, email, landing page and sales copy", "Feeding AI the right context", "Editing AI output into human-quality copy"], frameworks: ["AI copy prompting framework", "Copy evaluation scorecard"], activity: "Generate homepage copy, five ad hooks and a landing page structure with AI.", deliverable: "AI-assisted copy pack and prompt swipe file." },
  { day: 18, week: 3, title: "Personal brand foundations", trackFocus: "Marketing + leadership", sessionGoal: "Help students see personal brand as business leverage, not vanity.", topics: ["Personal brand vs influencer behaviour", "Authority, trust, visibility, opportunity", "Positioning without pretending to be bigger than you are"], frameworks: ["Personal brand architecture", "Story-proof-expertise-perspective model"], activity: "Audit ten strong personal brands and define your three expertise pillars.", deliverable: "Personal brand statement and authority pillar map." },

  // ===== WEEK 4 =====
  { day: 19, week: 4, title: "Profile, portfolio & trust infrastructure", trackFocus: "Marketing", sessionGoal: "Build the digital trust layer around the student.", topics: ["Why people judge credibility in seconds", "Profile optimisation across platforms", "Building a proof stack even when starting early"], frameworks: ["Trust stack model", "Profile audit checklist"], activity: "Run live profile audits and rebuild bios, headlines and pinned content.", deliverable: "Digital profile upgrade and portfolio v1." },
  { day: 20, week: 4, title: "Content strategy: what should you actually talk about?", trackFocus: "Marketing", sessionGoal: "Teach students to build a content engine with real purpose.", topics: ["Content pillars", "Awareness vs consideration vs conversion content", "Why random posting doesn't build demand"], frameworks: ["Content pillar framework", "70-20-10 content mix"], activity: "Build content pillars for three different types of brand and generate 30 content ideas.", deliverable: "Content pillar map and 30-day content idea bank.", relatedLink: { kind: "framework", slug: "content-engine", label: "Content engine setup" } },
  { day: 21, week: 4, title: "Hooks, storytelling & attention design", trackFocus: "Marketing + communication", sessionGoal: "Train students to earn attention without becoming shallow.", topics: ["The first three seconds of content", "Hook styles: tension, curiosity, contradiction, pain", "Storytelling in business content"], frameworks: ["Hook bank framework", "Story arc for content"], activity: "Write 25 hooks around one topic and convert a boring lesson into three content angles.", deliverable: "Hook bank and three finished content pieces." },
  { day: 22, week: 4, title: "AI content lab: faster content, better systems", trackFocus: "AI + marketing", sessionGoal: "Use AI to build a repeatable content engine.", topics: ["AI for ideation, outlines, captions, scripts, repurposing", "Preserving your own tone and thinking", "Building workflows instead of one-off posts"], frameworks: ["AI content engine workflow", "Long-form to short-form repurposing system"], activity: "Use AI to turn one idea into a reel script, carousel, post, email and thread.", deliverable: "AI content workflow and 7-day content sprint plan." },
  { day: 23, week: 4, title: "Social proof, testimonials & trust conversion", trackFocus: "Marketing + sales", sessionGoal: "Show how trust is created and used to improve conversion.", topics: ["Why proof is often stronger than persuasion", "Before/after, case study and screenshot proof", "Trust elements across social, landing pages and sales calls"], frameworks: ["Proof stack framework", "Testimonial collection system"], activity: "Audit ten brands for proof quality and rewrite weak testimonials into case-style proof.", deliverable: "Proof library and testimonial template bank." },
  { day: 24, week: 4, title: "Week 4 review: positioning, brand & content boardroom", trackFocus: "Review + presentation", sessionGoal: "Consolidate the first four weeks into a visible strategic review.", topics: ["Personal brand positioning presented and defended", "Persona, offer direction and content pillars reviewed"], frameworks: ["Boardroom review format"], activity: "Deliver an 8-minute presentation followed by 7 minutes of faculty and peer questioning.", deliverable: "Boardroom review score and revision plan for phase two." },

  // ===== WEEK 5 =====
  { day: 25, week: 5, title: "Organic demand generation", trackFocus: "Marketing", sessionGoal: "Help students understand how businesses create ongoing inbound demand.", topics: ["Demand generation vs random visibility", "Top-of-funnel vs mid-funnel vs conversion content", "Lead capture and nurture basics"], frameworks: ["Demand engine model", "Visibility-trust-inquiry-conversion flow"], activity: "Map the demand engine of three brands and build a simple demand flow for one business.", deliverable: "Demand generation sheet and funnel awareness map." },
  { day: 26, week: 5, title: "Content calendar, distribution & consistency systems", trackFocus: "Marketing + systems", sessionGoal: "Move from scattered ideas to a real content operating system.", topics: ["Weekly and monthly content planning", "Platform-specific distribution logic", "Batching, scheduling and quality control"], frameworks: ["Content operating system", "Weekly content sprint"], activity: "Build a 30-day content calendar with formats, platforms, goals and CTAs.", deliverable: "30-day content calendar and content workflow SOP v1.", relatedLink: { kind: "tool", slug: "content-calendar", label: "Content calendar tool" } },
  { day: 27, week: 5, title: "Creative marketing, attention triggers & brand recall", trackFocus: "Marketing + strategy", sessionGoal: "Introduce unconventional marketing and campaign-led attention.", topics: ["Why some campaigns are remembered and most are forgotten", "Buzz, pattern interrupts, seasonal hooks", "When bold ideas help and when they become gimmicks"], frameworks: ["Creative hook matrix", "Attention trigger model"], activity: "Break down ten memorable campaigns and build five creative ideas for a local business.", deliverable: "Campaign idea bank and creative marketing worksheet." },
  { day: 28, week: 5, title: "Sales psychology, conviction & conversion thinking", trackFocus: "Leadership + sales", sessionGoal: "Start moving students from brand thinking into conversion thinking.", topics: ["Why good marketers still struggle to sell", "Sales as diagnosis, clarity, confidence, follow-up", "Trust gaps and fear of commitment"], frameworks: ["Sales conviction framework", "Trust-risk-conviction triangle"], activity: "Run mock discovery calls and objection roleplay.", deliverable: "Discovery script and follow-up sequence draft." },
  { day: 29, week: 5, title: "AI for demand systems: content, offers, lead magnets & funnels", trackFocus: "AI + marketing", sessionGoal: "Use AI to accelerate demand-generation assets.", topics: ["AI for content calendar refinement and lead magnet ideation", "AI for offer-page structure", "AI for email follow-up and nurture flows"], frameworks: ["AI funnel drafting workflow", "Lead magnet creation model"], activity: "Use AI to create a lead magnet topic, landing page structure and 5-email nurture sequence.", deliverable: "Lead magnet concept and nurture sequence draft." },
  { day: 30, week: 5, title: "Month 1 review + Paarth growth lab", trackFocus: "Review + integration", sessionGoal: "Close the first 30 days with clarity and readiness for growth-heavy month two.", topics: ["Personal brand, persona, competitor map and offer direction reviewed", "Content calendar and demand-generation flow presented", "The one personal weakness being fixed in phase two"], frameworks: ["Month 1 builder review format"], activity: "Deliver a 10-minute presentation and 10 minutes of questioning.", deliverable: "Month 1 builder review score and revised growth plan for month two." },

  // ===== WEEK 6 =====
  { day: 31, week: 6, title: "The demand engine: how businesses create ongoing inbound attention", trackFocus: "Marketing + growth strategy", sessionGoal: "Show that demand is a structured system, not just posting.", topics: ["Attention vs engagement vs inquiries vs demand", "Organic, paid, referral and authority-driven demand", "Why inconsistent businesses never built a repeatable system"], frameworks: ["Demand engine model", "Content-to-demand map"], activity: "Reverse-engineer the demand systems of three strong brands.", deliverable: "Demand engine map and lead-source framework." },
  { day: 32, week: 6, title: "Content as a business asset, not a social media activity", trackFocus: "Marketing", sessionGoal: "Reframe content as business infrastructure.", topics: ["Content for awareness, authority, proof, nurture, sales", "Content as a compounding asset", "Why most content has no business role attached to it"], frameworks: ["Content asset ladder", "Content purpose matrix"], activity: "Categorise thirty brand posts by actual business purpose.", deliverable: "Content purpose matrix and business-content map." },
  { day: 33, week: 6, title: "Content systems: calendar, workflow, repurposing & review", trackFocus: "Marketing + systems", sessionGoal: "Build a real content operating system.", topics: ["Monthly planning vs weekly execution", "Batching, scripting, editing, publishing, repurposing", "How agencies systemise content"], frameworks: ["Content operating system", "Repurposing matrix"], activity: "Build a content operating workflow with assigned roles for one business.", deliverable: "Content workflow SOP and weekly publishing dashboard." },
  { day: 34, week: 6, title: "Advanced hooks: attention, curiosity, tension & recall", trackFocus: "Marketing + communication", sessionGoal: "Train high-performing content openings and ad hooks.", topics: ["Why most content dies in the first two seconds", "Hook structures for reels, ads, carousels, founder videos", "Curiosity vs clarity vs contradiction vs authority"], frameworks: ["Hook bank framework", "10 hook categories model"], activity: "Write fifty hooks across five different businesses.", deliverable: "Hook bank v2 and category-wise swipe file." },
  { day: 35, week: 6, title: "Storytelling for business: founder, customer & brand stories", trackFocus: "Marketing + leadership", sessionGoal: "Use narrative as a genuine business growth tool.", topics: ["Story as trust-building, not just entertainment", "Founder, customer, transformation and mission stories", "Using lived experience without sounding dramatic"], frameworks: ["Story arc framework", "Before-friction-breakthrough-lesson-action structure"], activity: "Write and present a 60-second founder origin story.", deliverable: "Founder story draft and storytelling bank." },
  { day: 36, week: 6, title: "AI content production lab", trackFocus: "AI + marketing", sessionGoal: "Speed up content creation without killing originality.", topics: ["AI for ideation, outlines, captions, scripting, repurposing", "Tone and context control", "Turning one idea into ten content assets"], frameworks: ["AI content engine workflow", "Long-form to short-form system"], activity: "Convert one founder story into a reel script, LinkedIn post, carousel, email and thread using AI.", deliverable: "AI content workflow and 7-day content sprint." },
  { day: 37, week: 6, title: "Content review lab + performance thinking", trackFocus: "Marketing + analysis", sessionGoal: "Teach students to judge content performance intelligently.", topics: ["What makes content work beyond vanity metrics", "Retention, saves, shares, comments, inquiries", "Improving weak content through iteration"], frameworks: ["Content performance review framework", "Post-mortem review sheet"], activity: "Audit ten posts across brands and redesign one low-performing piece.", deliverable: "Content performance sheet and iteration plan." },

  // ===== WEEK 7 =====
  { day: 38, week: 7, title: "Campaign thinking: from isolated posts to strategic bursts", trackFocus: "Marketing + strategy", sessionGoal: "Teach how real campaigns are structured.", topics: ["Objective, audience, message, creative idea, timeline, CTA", "Brand vs performance vs launch vs event campaigns", "Why campaigns create momentum better than random content"], frameworks: ["Campaign blueprint", "Objective-audience-idea-asset-distribution-CTA model"], activity: "Break down five real campaigns and build a mini campaign plan for a local brand.", deliverable: "Campaign blueprint v1 and campaign objective sheet.", relatedLink: { kind: "framework", slug: "ad-campaign-blueprint", label: "Ad campaign blueprint" } },
  { day: 39, week: 7, title: "Creative marketing & pattern interrupts", trackFocus: "Marketing + brand strategy", sessionGoal: "Train students to think beyond conventional ads.", topics: ["Pattern interrupts and surprise", "Emotional resonance, shareability, memorability", "When bold marketing helps and when it damages trust"], frameworks: ["Creative trigger model", "Pattern interrupt matrix"], activity: "Brainstorm twenty unconventional ideas and sort them into safe, bold, risky and premium-fit buckets.", deliverable: "Creative idea bank and pattern interrupt sheet." },
  { day: 40, week: 7, title: "Regional, cultural & social-trust marketing", trackFocus: "Marketing + brand relevance", sessionGoal: "Show how marketing strengthens with local relevance.", topics: ["Regional language, cultural context, community trust", "Social-trust marketing and ethical positioning", "How small brands win by feeling closer to the audience"], frameworks: ["Regional resonance framework", "Cultural relevance checklist"], activity: "Localise one national campaign for a specific regional audience.", deliverable: "Regional campaign adaptation sheet." },
  { day: 41, week: 7, title: "Event, festival & occasion-based campaigns", trackFocus: "Marketing + campaign strategy", sessionGoal: "Teach students to use the calendar as a marketing advantage.", topics: ["Why festivals, launches and seasonal moments create opportunity", "Building campaigns around occasions without forcing them", "Urgency, theme and offer adaptation"], frameworks: ["Occasion marketing calendar", "Event-led campaign planning"], activity: "Map the next six months of campaign-worthy events for different businesses.", deliverable: "Event marketing calendar and festival campaign ideas." },
  { day: 42, week: 7, title: "AI campaign lab: concepts, scripts & creative boards", trackFocus: "AI + marketing", sessionGoal: "Use AI to accelerate campaign ideation.", topics: ["AI for campaign angles, ad scripts, concept expansion", "Guiding AI with brand tone, audience and objective", "Quantity first, then quality refinement"], frameworks: ["AI campaign ideation workflow", "Concept expansion prompt structure"], activity: "Generate twenty campaign angles for one brand with AI and turn one into a full concept.", deliverable: "Campaign concept deck and AI prompt bank." },
  { day: 43, week: 7, title: "Campaign review boardroom", trackFocus: "Presentation + strategic defense", sessionGoal: "Make students defend their campaign thinking under scrutiny.", topics: ["Business, audience, objective and creative hook presented", "Distribution plan and expected result defended"], frameworks: ["Boardroom review format"], activity: "Deliver an 8-minute presentation followed by 8 minutes of critique on originality, relevance and feasibility.", deliverable: "Campaign review score and revised campaign blueprint." },

  // ===== WEEK 8 =====
  { day: 44, week: 8, title: "Sales fundamentals for founders, marketers & operators", trackFocus: "Leadership + sales", sessionGoal: "Remove fear around selling and treat it as a business necessity.", topics: ["What selling actually is", "Sales as clarity, diagnosis, trust and conviction", "Persuasion vs manipulation"], frameworks: ["Sales conversation framework", "Problem-fit-value-trust-next-step flow"], activity: "Roleplay a basic discovery conversation and identify what sounds trustworthy.", deliverable: "Sales conversation outline and discovery script v1." },
  { day: 45, week: 8, title: "Customer objections, trust gaps & buying resistance", trackFocus: "Sales + psychology", sessionGoal: "Teach students to handle hesitation intelligently.", topics: ["Why people hesitate even when interested", "Objection types: price, trust, timing, confusion, risk", "Handling objections with clarity and calm"], frameworks: ["Objection map", "Trust-risk-conviction triangle"], activity: "Roleplay fifteen objections and rewrite weak objection replies.", deliverable: "Objection handling library and response cheat sheet." },
  { day: 46, week: 8, title: "Sales conviction, product knowledge & offer defense", trackFocus: "Leadership + sales", sessionGoal: "Show that weak conviction kills conversion.", topics: ["Conviction from product knowledge, customer knowledge, clarity", "How uncertainty leaks into sales conversations", "The importance of guarantees and proof"], frameworks: ["Sales conviction framework", "Value articulation model"], activity: "Defend an offer live in front of the room in a 60-second drill.", deliverable: "Offer defense script and conviction pitch video." },
  { day: 47, week: 8, title: "Conversion copy: landing pages, offers & CTAs", trackFocus: "Marketing + sales", sessionGoal: "Show how conversion happens through copy, proof and clarity.", topics: ["The job of a landing page", "Hero section, problem framing, proof, FAQ, CTA", "Conversion copy vs informational copy"], frameworks: ["Landing page wireframe", "CTA formula bank"], activity: "Tear down five landing pages and rewrite a weak page into a stronger one.", deliverable: "Landing page copy draft and CTA bank." },
  { day: 48, week: 8, title: "AI sales & conversion lab", trackFocus: "AI + sales + marketing", sessionGoal: "Use AI to build sales-support and conversion assets faster.", topics: ["AI for scripts, objection handling, FAQs, follow-up emails", "Feeding customer pain and offer details into prompts", "Improving AI outputs with business context"], frameworks: ["AI sales prompt system", "Conversion asset generation workflow"], activity: "Use AI to generate a FAQ section, objection replies and a follow-up sequence.", deliverable: "AI sales pack and FAQ/objection asset bank." },
  { day: 49, week: 8, title: "Mock sales calls & conversion review", trackFocus: "Sales + communication", sessionGoal: "Practice real persuasion under pressure.", topics: ["Tone, pace, confidence, questioning, listening", "Identifying whether a lead is ready, confused or curious", "Ending a sales conversation well"], frameworks: ["Discovery-call scorecard", "Call review framework"], activity: "Run mock sales calls in trios: founder, customer, evaluator.", deliverable: "Mock sales evaluation sheet and revised call script." },

  // ===== WEEK 9 =====
  { day: 50, week: 9, title: "Funnel thinking: what happens after attention?", trackFocus: "Marketing + strategy", sessionGoal: "Teach students to think in journeys, not isolated posts.", topics: ["What a funnel is and isn't", "Awareness, interest, trust, action, nurture", "Why social content alone is never enough"], frameworks: ["Funnel map model", "Audience journey framework"], activity: "Map three funnel examples from real businesses and identify where leads drop off.", deliverable: "Funnel map and customer journey sheet." },
  { day: 51, week: 9, title: "Lead magnets, free value & trust capture", trackFocus: "Marketing + offer design", sessionGoal: "Show how to create lead magnets that pull the right audience.", topics: ["What lead magnets are", "When free value builds trust and when it attracts the wrong audience", "Aligning lead magnets to the main offer"], frameworks: ["Lead magnet alignment model", "Free-value-to-offer ladder"], activity: "Evaluate twenty lead magnet examples and brainstorm ten ideas for one business.", deliverable: "Lead magnet concept note and CTA draft." },
  { day: 52, week: 9, title: "Website strategy: what a high-converting website must do", trackFocus: "Marketing + digital assets", sessionGoal: "Teach website thinking as business infrastructure, not design.", topics: ["The role of a website in trust and conversion", "How websites differ by business type", "Why pretty websites often fail commercially"], frameworks: ["Website conversion architecture", "Digital trust checklist"], activity: "Audit ten websites and identify weak messaging, proof and broken CTA flow.", deliverable: "Website strategy sheet and homepage wireframe notes." },
  { day: 53, week: 9, title: "Landing pages vs websites vs funnels", trackFocus: "Marketing + digital strategy", sessionGoal: "Teach students when to use what.", topics: ["Differences in intent, structure and conversion goal", "When a business needs a brochure site, a lead-gen page or a full funnel", "Reducing friction in the buyer journey"], frameworks: ["Digital asset selection matrix", "Friction reduction checklist"], activity: "Compare five businesses and decide what digital asset system each actually needs.", deliverable: "Digital asset strategy note and buyer-journey map." },
  { day: 54, week: 9, title: "AI website & funnel build lab", trackFocus: "AI + digital build", sessionGoal: "Start building real conversion assets with AI support.", topics: ["AI for website structure, copy, lead magnets, funnel planning", "Using AI website builders and prompt-led site creation", "Maintaining positioning clarity while using AI"], frameworks: ["AI website creation workflow", "Funnel drafting system"], activity: "Generate homepage copy and a funnel structure with AI, then build a first landing page draft.", deliverable: "Landing page draft and AI website prompt stack." },
  { day: 55, week: 9, title: "Lead nurture: email, WhatsApp & follow-up systems", trackFocus: "Marketing + sales", sessionGoal: "Teach what happens after someone enters the funnel.", topics: ["Lead nurturing basics", "Follow-up through email, WhatsApp, DMs, reminders", "Why most leads die from lack of follow-up"], frameworks: ["Nurture sequence framework", "Lead temperature model"], activity: "Write a 5-step nurture sequence classified into welcome, proof, education, urgency, follow-up.", deliverable: "Nurture sequence draft and follow-up message bank." },
  { day: 56, week: 9, title: "Funnel & website review boardroom", trackFocus: "Presentation + review", sessionGoal: "Make students defend their funnel and website logic.", topics: ["Customer journey, lead magnet and landing page structure presented", "CTA logic and follow-up sequence defended"], frameworks: ["Boardroom review format"], activity: "Deliver a 10-minute presentation with 10 minutes of questioning on clarity, usability and conversion logic.", deliverable: "Funnel review score and revision action plan." },

  // ===== WEEK 10 =====
  { day: 57, week: 10, title: "Business models & growth pathways", trackFocus: "Leadership + business strategy", sessionGoal: "Shift students from campaign thinking to broader growth thinking.", topics: ["How businesses actually scale", "Service, product, education, community and platform business", "Recurring vs one-time revenue"], frameworks: ["Business model map", "Growth pathway matrix"], activity: "Break down the growth model of five businesses and identify what stops scaling.", deliverable: "Business model map and growth pathway sheet.", relatedLink: { kind: "tool", slug: "business-model-canvas", label: "Business model canvas" } },
  { day: 58, week: 10, title: "AI for business operations, SOP thinking & internal efficiency", trackFocus: "AI + operations", sessionGoal: "Show that AI serves internal efficiency, not just marketing.", topics: ["AI for SOP drafting, meeting summaries, reporting, research", "Chaos-driven vs system-supported execution", "Early process thinking ahead of the systems phase"], frameworks: ["AI operations workflow", "Task-to-system model"], activity: "Turn one messy process into a clean SOP outline using AI.", deliverable: "SOP draft v1 and AI operations toolkit note.", relatedLink: { kind: "framework", slug: "sop-builder", label: "SOP builder" } },
  { day: 59, week: 10, title: "Founder communication, decision-making & team briefing", trackFocus: "Leadership", sessionGoal: "Strengthen the ability to lead conversations and decide with clarity.", topics: ["How founders brief teams, agencies, vendors", "Clear instruction vs vague instruction", "Making decisions with incomplete information"], frameworks: ["Founder briefing framework", "Decision clarity checklist"], activity: "Run a mock team briefing assigning campaign work clearly.", deliverable: "Founder brief document and decision log sheet." },
  { day: 60, week: 10, title: "Phase 2 growth boardroom: build, present, defend", trackFocus: "Review + integration", sessionGoal: "Consolidate days 31–60 and prepare for the final phase.", topics: ["Demand engine, content system and campaign concept presented", "Sales, funnel and AI workflows defended", "Biggest execution lesson from the last thirty days"], frameworks: ["Phase 2 growth review format"], activity: "Deliver a 12-minute presentation with 12 minutes of faculty questioning.", deliverable: "Phase 2 growth review score and phase 3 readiness note." },

  // ===== WEEK 11 =====
  { day: 61, week: 11, title: "Why businesses break: chaos, dependence & lack of systems", trackFocus: "Business leadership + operations", sessionGoal: "Understand why promising businesses stop growing even with demand.", topics: ["Founder dependence, unclear roles, weak communication", "The hidden cost of chaos", "Why hard work isn't the same as business maturity"], frameworks: ["Business chaos diagnostic", "Founder dependence map"], activity: "Diagnose five business chaos scenarios and map operational leaks in a sample business.", deliverable: "Operational leak map and founder dependence sheet." },
  { day: 62, week: 11, title: "Thinking in systems: from tasks to repeatable processes", trackFocus: "Operations + leadership", sessionGoal: "Teach repeatable workflow thinking over random action.", topics: ["What a system actually is", "Process vs outcome vs responsibility", "Identifying which tasks should become processes"], frameworks: ["Task-process-system model", "Repeatability framework"], activity: "Convert messy daily activities into repeatable process flows for sales, onboarding and content.", deliverable: "Process map set and system-thinking notes." },
  { day: 63, week: 11, title: "SOP fundamentals: how to document business execution", trackFocus: "Operations", sessionGoal: "Show how SOPs make a business more stable and scalable.", topics: ["Why SOPs reduce confusion and founder dependency", "What should and shouldn't be documented", "SOP structure: objective, owner, steps, timeline, checkpoints"], frameworks: ["SOP structure framework", "Quality checkpoint system"], activity: "Draft two SOPs: content production and lead follow-up.", deliverable: "SOP draft set v1 and SOP structure template.", relatedLink: { kind: "framework", slug: "sop-builder", label: "SOP builder" } },
  { day: 64, week: 11, title: "AI for SOPs, documentation & internal systems", trackFocus: "AI + operations", sessionGoal: "Speed up documentation and internal system-building with AI.", topics: ["AI for SOP drafting, workflow capture, training docs", "Where AI helps and where human clarity is still required"], frameworks: ["AI SOP drafting workflow", "Process-to-document pipeline"], activity: "Use AI to turn a messy workflow into an SOP draft.", deliverable: "AI SOP toolkit and process documentation pack." },
  { day: 65, week: 11, title: "Business workflow design: sales, delivery, reporting & review", trackFocus: "Operations + business design", sessionGoal: "See a business as connected workflows, not isolated tasks.", topics: ["Lead capture through retention as one connected chain", "Why many businesses break at handoffs", "Designing workflows that are simple, visible, accountable"], frameworks: ["End-to-end workflow map", "Handoff clarity framework"], activity: "Map a full customer journey from first inquiry to delivery.", deliverable: "End-to-end workflow map and bottleneck sheet." },
  { day: 66, week: 11, title: "Business review rhythms: daily, weekly & monthly cadence", trackFocus: "Leadership + operations", sessionGoal: "Teach that businesses improve through regular review, not just effort.", topics: ["Why review rhythm matters", "Daily check-ins vs weekly vs monthly reviews", "What should actually be reviewed"], frameworks: ["Daily-weekly-monthly review rhythm", "Operating cadence model"], activity: "Build a weekly review agenda and simulate a monthly business review meeting.", deliverable: "Weekly review template and operating cadence chart." },

  // ===== WEEK 12 =====
  { day: 67, week: 12, title: "Roles, responsibilities & org thinking", trackFocus: "Leadership + operations", sessionGoal: "Show businesses need role clarity before they need more people.", topics: ["Role clarity vs talent chaos", "Why 'everyone doing everything' only works briefly", "What ownership actually means"], frameworks: ["Role-responsibility map", "Function-to-owner model"], activity: "Break down a five-person team structure and define what each role should own.", deliverable: "Role-responsibility map and function chart." },
  { day: 68, week: 12, title: "Hiring basics: who to hire, when, and what to look for", trackFocus: "Leadership + business building", sessionGoal: "Introduce practical hiring logic for small, growing businesses.", topics: ["Hiring too early vs too late", "Skill, reliability, ownership, attitude, learning ability", "Freelancer vs employee vs intern vs partner"], frameworks: ["Hiring need matrix", "Role scorecard"], activity: "Write a job brief for a content executive, sales caller and operations coordinator.", deliverable: "Hiring brief and interview scorecard.", relatedLink: { kind: "tool", slug: "hiring-scorecard", label: "Hiring scorecard" } },
  { day: 69, week: 12, title: "Onboarding, training & early team enablement", trackFocus: "Leadership + operations", sessionGoal: "Show how to help new people become productive faster.", topics: ["Why onboarding is often ignored in small businesses", "The first 7, 14 and 30 days of a new hire", "Creating learning paths for new hires"], frameworks: ["30-day onboarding map", "Role enablement checklist"], activity: "Build a 14-day onboarding plan for a content or sales role.", deliverable: "Onboarding plan and first-30-days training map." },
  { day: 70, week: 12, title: "Leadership communication: briefing, delegation & follow-through", trackFocus: "Leadership", sessionGoal: "Train students to communicate work clearly so execution improves.", topics: ["Vague vs clear instructions", "Delegation without abdication", "Following up without becoming controlling"], frameworks: ["Delegation framework", "Task clarity checklist"], activity: "Write and deliver a team brief, then roleplay assigning work to a designer, marketer and sales rep.", deliverable: "Founder brief document and delegation checklist." },
  { day: 71, week: 12, title: "Difficult conversations, feedback & accountability", trackFocus: "Leadership + people management", sessionGoal: "Handle underperformance and uncomfortable conversations with maturity.", topics: ["Why avoiding difficult conversations weakens businesses", "Feedback vs blame", "Correcting behaviour without humiliating people"], frameworks: ["Feedback conversation model", "Issue-impact-expectation-support structure"], activity: "Roleplay difficult conversations: missed deadlines, careless work, repeated excuses.", deliverable: "Feedback script bank and accountability conversation notes." },

  // ===== WEEK 13 =====
  { day: 72, week: 13, title: "KPI thinking: what should a business actually track?", trackFocus: "Business strategy + operations", sessionGoal: "Teach that not all metrics matter equally.", topics: ["Vanity metrics vs business metrics", "Output vs performance vs health metrics", "Why weak businesses track nothing or the wrong things"], frameworks: ["KPI hierarchy", "Leading vs lagging indicators"], activity: "Identify KPIs for five different business types and map what to track weekly vs monthly.", deliverable: "KPI map and business health scorecard draft." },
  { day: 73, week: 13, title: "KRA, ownership & performance accountability", trackFocus: "Leadership + team management", sessionGoal: "Move from tracking numbers to assigning real responsibility.", topics: ["KPI vs KRA", "Ownership-based execution", "Aligning metrics to responsibilities"], frameworks: ["KRA assignment model", "Owner-to-metric framework"], activity: "Assign KRAs to different roles and connect KPIs to ownership.", deliverable: "KPI-KRA table and accountability map." },
  { day: 74, week: 13, title: "Dashboards, reporting & decision visibility", trackFocus: "Operations + leadership", sessionGoal: "Teach how reporting helps founders decide faster.", topics: ["Dashboard basics for small businesses", "Weekly vs monthly reports", "How reporting reduces emotional decision-making"], frameworks: ["Dashboard design model", "Founder visibility framework"], activity: "Build a sample founder dashboard for an agency, education or D2C business.", deliverable: "Dashboard draft and weekly report template." },
  { day: 75, week: 13, title: "Decision-making under pressure", trackFocus: "Leadership", sessionGoal: "Train students to decide without freezing or reacting emotionally.", topics: ["Decisions with incomplete information", "Speed vs accuracy", "Separating ego, panic and fact"], frameworks: ["Decision filter framework", "Urgency-impact matrix"], activity: "Run scenario-based decision drills and debate what you would do and why.", deliverable: "Decision log and scenario response notes." },
  { day: 76, week: 13, title: "AI for dashboards, summaries, reviews & business analysis", trackFocus: "AI + business operations", sessionGoal: "Show AI's role in business review, not just marketing.", topics: ["AI for report summaries, KPI interpretation, meeting notes", "Turning raw information into decision-ready summaries", "Using AI to spot patterns and follow-up actions"], frameworks: ["AI business review workflow", "Data-to-decision summary model"], activity: "Feed a mock business report into AI and generate insights, then compare to manual review.", deliverable: "AI review template and business analysis prompt bank." },

  // ===== WEEK 14 =====
  { day: 77, week: 14, title: "Business model strength: revenue, margin & sustainability", trackFocus: "Business strategy", sessionGoal: "Understand that growth without economics is fragile.", topics: ["Recurring vs one-time revenue", "Margin awareness", "Why some businesses look successful but are structurally weak"], frameworks: ["Business model map", "Sustainability diagnostic"], activity: "Analyse five business models for strength and weakness, then redesign a low-margin one.", deliverable: "Business model strength sheet and revenue stream map.", relatedLink: { kind: "tool", slug: "break-even-calculator", label: "Break-even calculator" } },
  { day: 78, week: 14, title: "Capacity, bottlenecks & scale constraints", trackFocus: "Operations + scale strategy", sessionGoal: "Show what starts breaking when a business grows.", topics: ["Founder bandwidth, team skill, process gaps as bottlenecks", "Low margins, bad client quality, weak delivery systems", "Why some businesses can't handle the growth they created"], frameworks: ["Bottleneck analysis model", "Capacity map"], activity: "Run a 'what breaks at 2x growth?' exercise for different business models.", deliverable: "Bottleneck report and capacity map." },
  { day: 79, week: 14, title: "Founder energy, burnout & sustainable performance", trackFocus: "Leadership", sessionGoal: "Teach that leadership also requires managing your own energy.", topics: ["Founder burnout patterns", "Stress from ambiguity, overload, responsibility", "Personal routines, recovery, delegation"], frameworks: ["Founder sustainability framework", "Energy audit"], activity: "Perform a founder energy audit and design a weekly sustainability routine.", deliverable: "Founder energy audit and 30-day performance plan." },
  { day: 80, week: 14, title: "Leadership identity: what kind of builder are you becoming?", trackFocus: "Leadership + reflection", sessionGoal: "Return to identity from a more mature, tested place.", topics: ["How identity changes after real execution", "Wanting success vs being able to carry responsibility", "Leadership as behaviour, not image"], frameworks: ["Leadership identity map", "Values-under-pressure reflection"], activity: "Write a guided reflection on who you've become in eighty days.", deliverable: "Leadership identity statement and operating philosophy note." },

  // ===== WEEK 15 =====
  { day: 81, week: 15, title: "Capstone blueprint kickoff", trackFocus: "Integration + strategy", sessionGoal: "Begin assembling ninety days of work into one business blueprint.", topics: ["What the final capstone must include", "Moving from scattered documents to one coherent build", "Thinking like a boardroom presenter"], frameworks: ["Capstone structure"], activity: "Walk through the capstone structure and assign presentation sections.", deliverable: "Capstone outline and evidence checklist." },
  { day: 82, week: 15, title: "Capstone build lab 1: strategy, positioning & demand", trackFocus: "Build lab", sessionGoal: "Strengthen the front-end strategic section of the capstone.", topics: ["Market understanding and customer persona", "Competitor and white-space insight", "Positioning, offer and demand engine"], frameworks: ["Strategy narrative structure"], activity: "Receive faculty review on strategic clarity and refine the market thesis.", deliverable: "Capstone section 1 draft and refined positioning stack." },
  { day: 83, week: 15, title: "Capstone build lab 2: campaigns, funnels, sales & website", trackFocus: "Build lab", sessionGoal: "Build the growth and conversion layer of the capstone.", topics: ["Campaign concepts and content system", "Funnel flow and sales script", "Landing page and website structure"], frameworks: ["Conversion layer structure"], activity: "Review conversion logic and tighten funnel simplicity and sales clarity.", deliverable: "Capstone section 2 draft and funnel architecture." },
  { day: 84, week: 15, title: "Capstone build lab 3: SOPs, roles, KPIs & scale", trackFocus: "Build lab", sessionGoal: "Build the operator layer of the capstone.", topics: ["SOPs and workflow maps", "Team structure and onboarding logic", "KPI, KRA, dashboard and business review cadence"], frameworks: ["Operating blueprint structure"], activity: "Receive faculty critique on business realism and strengthen operating clarity.", deliverable: "Capstone section 3 draft and operating blueprint." },
  { day: 85, week: 15, title: "Boardroom communication masterclass", trackFocus: "Leadership + presentation", sessionGoal: "Prepare students to defend ideas like operators, not students reading slides.", topics: ["Presenting with conviction and structure", "Answering tough questions without collapsing", "Admitting uncertainty intelligently"], frameworks: ["Boardroom presentation structure", "Answer-with-clarity model"], activity: "Practice the capstone pitch opening followed by a rapid-fire questioning drill.", deliverable: "Presentation script and boardroom Q&A prep sheet." },
  { day: 86, week: 15, title: "Capstone review round 1", trackFocus: "Review + critique", sessionGoal: "Put the first full capstone version under pressure.", topics: ["Clarity and realism reviewed", "Strategic depth and conversion logic tested", "Operational maturity and leadership thinking assessed"], frameworks: ["Capstone review criteria"], activity: "Present the draft capstone to faculty and peers for critique.", deliverable: "Capstone review notes and version 2 build plan." },
  { day: 87, week: 15, title: "Capstone review round 2", trackFocus: "Review + refinement", sessionGoal: "Strengthen the final business blueprint and remove weak areas.", topics: ["Cleaner structure and stronger business logic", "Tighter systems and better KPI articulation", "Stronger founder communication"], frameworks: ["Capstone refinement criteria"], activity: "Complete a second round of capstone review with sharper critique.", deliverable: "Refined capstone draft and boardroom-ready structure." },
  { day: 88, week: 15, title: "Final personal reflection + leadership debrief", trackFocus: "Leadership + reflection", sessionGoal: "Give students space to articulate how they've changed.", topics: ["What changed in how they think", "Where maturity is still lacking", "What kind of work they now feel capable of doing"], frameworks: ["90-day builder reflection structure"], activity: "Write a 90-day builder reflection and record a final leadership video message.", deliverable: "90-Day Builder Reflection and post-Paarth action plan." },
  { day: 89, week: 15, title: "Final Paarth boardroom rehearsal", trackFocus: "Presentation + strategic defense", sessionGoal: "Prepare students for the final evaluation environment.", topics: ["Full-dress rehearsal of the final boardroom", "Timing discipline and Q&A pressure testing", "Visual deck, story flow and closing statement refinement"], frameworks: ["Final rehearsal checklist"], activity: "Run a complete rehearsal of the final capstone presentation under time pressure.", deliverable: "Rehearsal score and final presentation adjustments." },
  { day: 90, week: 15, title: "The Paarth final boardroom", trackFocus: "Final capstone defense + graduation benchmark", sessionGoal: "Evaluate whether the student has genuinely become a more capable builder, marketer, AI-enabled operator and emerging leader.", topics: ["Market understanding, positioning, offer and demand presented", "Sales, funnel, systems, team and scale thinking defended", "AI integration across the entire build explained"], frameworks: ["Final boardroom evaluation criteria"], activity: "Deliver a 15-minute final presentation followed by 15 minutes of strategic questioning.", deliverable: "Paarth final boardroom score and next-180-days growth recommendation." },
];

export function getScheduleDay(day: number) {
  return FLAGSHIP_SCHEDULE.find((d) => d.day === day);
}

export function getScheduleWeek(week: number) {
  return FLAGSHIP_SCHEDULE.filter((d) => d.week === week);
}
