import type { GlossaryTerm } from "./knowledgeTypes";

export const GLOSSARY: GlossaryTerm[] = [
  // ---------- FINANCE ----------
  { term: "Gross margin", category: "Finance", definition: "The percentage of revenue left after subtracting the direct cost of making or delivering what you sold, before any overhead is deducted." },
  { term: "Net margin", category: "Finance", definition: "The percentage of revenue left as actual profit after every cost — direct, overhead, interest, and tax — has been subtracted." },
  { term: "EBITDA", category: "Finance", definition: "Earnings before interest, tax, depreciation, and amortisation — a measure of operating profitability that strips out financing and accounting decisions to make businesses easier to compare." },
  { term: "Working capital", category: "Finance", definition: "The cash tied up in day-to-day operations — inventory and money owed to you, minus money you owe — that keeps the business running between sale and payment." },
  { term: "Cash flow", category: "Finance", definition: "The actual movement of money in and out of a business, which can differ sharply from reported profit if customers pay late or inventory ties up cash." },
  { term: "Burn rate", category: "Finance", definition: "How fast a business is spending its cash reserves each month, typically used when a business is running at a loss funded by savings or investment." },
  { term: "Runway", category: "Finance", definition: "How many months a business can keep operating at its current burn rate before running out of cash." },
  { term: "CAC (customer acquisition cost)", category: "Finance", definition: "The total cost — marketing, sales, and related effort — of winning one new paying customer." },
  { term: "LTV (customer lifetime value)", category: "Finance", definition: "The total profit a business can expect to earn from one customer over the entire span of their relationship, not just their first purchase." },
  { term: "ROI (return on investment)", category: "Finance", definition: "The return earned on money invested, expressed as a percentage of what was put in — used to judge whether spending on a project was worth it." },
  { term: "ROCE (return on capital employed)", category: "Finance", definition: "How efficiently a business turns the total capital invested in it — both debt and equity — into operating profit." },
  { term: "Break-even point", category: "Finance", definition: "The sales level at which total revenue exactly equals total costs, with no profit and no loss." },
  { term: "Fixed costs", category: "Finance", definition: "Costs that stay roughly the same regardless of how much you sell, like rent or salaried staff." },
  { term: "Variable costs", category: "Finance", definition: "Costs that rise and fall directly with how much you produce or sell, like raw materials or packaging." },
  { term: "Accounts receivable", category: "Finance", definition: "Money customers owe you for goods or services already delivered but not yet paid for." },
  { term: "Accounts payable", category: "Finance", definition: "Money you owe suppliers or vendors for goods or services you've already received but not yet paid for." },
  { term: "Debt-to-equity ratio", category: "Finance", definition: "How much of a business is funded by borrowed money compared to the owner's own invested capital — a key measure of financial risk." },
  { term: "Depreciation", category: "Finance", definition: "The accounting practice of spreading the cost of a long-lasting asset (like machinery) across the years it's actually used, rather than expensing it all at once." },
  { term: "Valuation", category: "Finance", definition: "An estimate of what a whole business is worth, used when raising investment, selling, or bringing in a partner." },

  // ---------- MARKETING ----------
  { term: "Brand equity", category: "Marketing", definition: "The added value a brand name itself creates — the reason customers will pay more or choose it over an identical unbranded alternative." },
  { term: "Positioning", category: "Marketing", definition: "The specific, ownable space a brand occupies in a customer's mind relative to competitors, defined by what it's known for." },
  { term: "Conversion rate", category: "Marketing", definition: "The percentage of people who take a desired action (buying, signing up) out of everyone who saw the opportunity to." },
  { term: "Marketing funnel", category: "Marketing", definition: "The stages a stranger passes through on the way to becoming a customer — typically awareness, interest, consideration, and purchase." },
  { term: "Impressions", category: "Marketing", definition: "The number of times an ad or piece of content was displayed, regardless of whether anyone engaged with it." },
  { term: "CTR (click-through rate)", category: "Marketing", definition: "The percentage of people who saw an ad or link and actually clicked on it." },
  { term: "Organic reach", category: "Marketing", definition: "The number of people who see your content without any paid promotion behind it." },
  { term: "SEO (search engine optimisation)", category: "Marketing", definition: "The practice of improving a website so it ranks higher in search results for relevant terms, driving free traffic over time." },
  { term: "Content marketing", category: "Marketing", definition: "Attracting and retaining customers by consistently publishing genuinely useful or entertaining content, rather than direct advertising." },
  { term: "USP (unique selling proposition)", category: "Marketing", definition: "The single clearest reason a customer should choose you over every alternative, including doing nothing." },
  { term: "Target audience", category: "Marketing", definition: "The specific group of people a product or message is designed for, defined by shared needs, behaviour, or characteristics." },
  { term: "Market segmentation", category: "Marketing", definition: "Dividing a broad market into smaller groups of customers who share similar needs, so messaging and offers can be tailored to each." },
  { term: "A/B testing", category: "Marketing", definition: "Showing two versions of something (an ad, a page, a price) to different groups at the same time to see which performs better." },
  { term: "Churn rate", category: "Marketing", definition: "The percentage of customers who stop buying or cancel their subscription over a given period." },
  { term: "NPS (net promoter score)", category: "Marketing", definition: "A score based on how likely customers are to recommend you to others, used as a proxy for overall satisfaction and loyalty." },
  { term: "Impression share", category: "Marketing", definition: "The percentage of all possible times your ad could have shown for a given search or audience that it actually did show." },

  // ---------- SALES ----------
  { term: "Sales funnel", category: "Sales", definition: "The stages a prospect moves through from first contact to closed sale, used to track where deals are getting stuck." },
  { term: "Lead", category: "Sales", definition: "A person or company that has shown some interest in what you sell but hasn't yet been qualified as a serious prospect." },
  { term: "Qualified lead", category: "Sales", definition: "A lead that has been checked against real buying criteria (budget, authority, need, timeline) and confirmed worth pursuing seriously." },
  { term: "Pipeline", category: "Sales", definition: "The full set of deals currently in progress at various stages, used to forecast future revenue." },
  { term: "Closing rate", category: "Sales", definition: "The percentage of qualified opportunities that actually convert into a signed sale." },
  { term: "Upselling", category: "Sales", definition: "Encouraging a customer to buy a more expensive or upgraded version of what they were already planning to purchase." },
  { term: "Cross-selling", category: "Sales", definition: "Encouraging a customer to buy an additional, complementary product alongside what they were already purchasing." },
  { term: "Objection handling", category: "Sales", definition: "The skill of responding to a prospect's hesitations or concerns in a way that moves the conversation forward rather than ending it." },
  { term: "Cold calling", category: "Sales", definition: "Reaching out to a prospect who has had no prior contact with your business, typically by phone." },
  { term: "Sales cycle", category: "Sales", definition: "The typical length of time between first contact with a prospect and closing the sale." },
  { term: "Quota", category: "Sales", definition: "The sales target a salesperson or team is expected to hit within a given period." },
  { term: "Discovery call", category: "Sales", definition: "An early sales conversation focused on understanding a prospect's situation and needs before proposing a solution." },
  { term: "Decision maker", category: "Sales", definition: "The person in a buying process who has actual authority to approve or block the purchase." },
  { term: "BANT", category: "Sales", definition: "A lead-qualifying checklist covering Budget, Authority, Need, and Timeline, used to judge how ready a prospect really is to buy." },

  // ---------- OPERATIONS ----------
  { term: "SOP (standard operating procedure)", category: "Operations", definition: "A documented, step-by-step process for how a task should be done, so quality stays consistent no matter who performs it." },
  { term: "TAT (turnaround time)", category: "Operations", definition: "The time between a request entering a process and the result coming out the other end." },
  { term: "Inventory turnover", category: "Operations", definition: "How many times a business sells and replaces its stock over a given period — a higher number generally means healthier cash flow." },
  { term: "Supply chain", category: "Operations", definition: "The full sequence of steps and parties involved in getting a product from raw material to the final customer." },
  { term: "Lean", category: "Operations", definition: "An operating philosophy focused on systematically removing any step in a process that doesn't add value the customer would pay for." },
  { term: "Six Sigma", category: "Operations", definition: "A structured methodology for reducing errors and variation in a process to a very small, statistically defined tolerance." },
  { term: "Just-in-time (JIT)", category: "Operations", definition: "Receiving inventory only as close as possible to when it's actually needed, minimising cash tied up in stored stock." },
  { term: "Bottleneck", category: "Operations", definition: "The single slowest step in a process that limits how much the entire process can output, regardless of how fast other steps run." },
  { term: "Quality control", category: "Operations", definition: "The systematic process of checking that products or services meet a defined standard before they reach the customer." },
  { term: "Vendor management", category: "Operations", definition: "The ongoing process of selecting, evaluating, and maintaining relationships with external suppliers." },
  { term: "Capacity utilisation", category: "Operations", definition: "The percentage of a business's total possible output that's actually being used or produced." },
  { term: "Outsourcing", category: "Operations", definition: "Paying an external specialist to handle a function instead of doing it in-house." },
  { term: "Automation", category: "Operations", definition: "Using technology to perform a task that would otherwise require manual human effort, usually to increase speed or consistency." },
  { term: "WIP (work in progress)", category: "Operations", definition: "Items or tasks that have been started but not yet completed as they move through a process." },

  // ---------- PEOPLE ----------
  { term: "KPI (key performance indicator)", category: "People", definition: "A specific, tracked number used to judge whether a role, team, or business is performing as expected." },
  { term: "KRA (key result area)", category: "People", definition: "The specific responsibilities and activities a role is expected to own, which together produce its KPIs." },
  { term: "Onboarding", category: "People", definition: "The structured process of getting a new hire up to speed on expectations, tools, and relationships in their first weeks." },
  { term: "Attrition", category: "People", definition: "The rate at which employees leave a business over a given period, whether voluntarily or not." },
  { term: "Performance review", category: "People", definition: "A structured, periodic conversation assessing how an employee has performed against expectations." },
  { term: "Org chart", category: "People", definition: "A visual map of who reports to whom across a business." },
  { term: "Delegation", category: "People", definition: "Handing off a task or decision to someone else, ranging from simple task assignment to full ownership of the outcome." },
  { term: "Span of control", category: "People", definition: "The number of people directly reporting to one manager." },
  { term: "Culture", category: "People", definition: "The accumulated, often unwritten patterns of behaviour and belief that shape how people actually act inside a business." },
  { term: "Employee engagement", category: "People", definition: "The degree to which employees feel invested in and motivated by their work, beyond simply showing up." },
  { term: "Succession planning", category: "People", definition: "Deliberately preparing specific people to step into key roles before those roles become vacant." },
  { term: "ESOP (employee stock ownership plan)", category: "People", definition: "A scheme that gives employees a share of company ownership, usually vesting over time, to align their incentives with the business's success." },
  { term: "Exit interview", category: "People", definition: "A structured conversation with a departing employee to understand why they're leaving and what could be improved." },
  { term: "Talent acquisition", category: "People", definition: "The broader, ongoing function of sourcing, attracting, and hiring the right people, as distinct from just filling an open position." },

  // ---------- STRATEGY ----------
  { term: "SWOT analysis", category: "Strategy", definition: "A framework for assessing a business's internal Strengths and Weaknesses alongside external Opportunities and Threats." },
  { term: "Moat", category: "Strategy", definition: "A durable competitive advantage that protects a business from being easily copied or displaced by competitors." },
  { term: "Core competency", category: "Strategy", definition: "The specific capability a business does better than almost anyone else, and which its strategy should be built around." },
  { term: "Pivot", category: "Strategy", definition: "A significant, deliberate change in business model or direction, usually made after learning the original approach isn't working." },
  { term: "MVP (minimum viable product)", category: "Strategy", definition: "The simplest version of a product that can still be released to real customers to test whether the underlying idea has value." },
  { term: "Market share", category: "Strategy", definition: "The percentage of total sales in a category or market that one business captures." },
  { term: "Competitive advantage", category: "Strategy", definition: "Any factor that allows a business to outperform its competitors on a sustained basis." },
  { term: "Diversification", category: "Strategy", definition: "Expanding into new products, markets, or business lines to reduce dependence on any single source of revenue." },
  { term: "Scalability", category: "Strategy", definition: "How easily a business can grow output or revenue without a proportional increase in cost or complexity." },
  { term: "Unit economics", category: "Strategy", definition: "The revenue and cost of a business at the level of one single unit — one customer, one order, one product — used to judge if the model actually works before scaling it." },
  { term: "Disruption", category: "Strategy", definition: "A new entrant or technology that initially serves an overlooked segment more simply or cheaply, then moves upmarket to challenge established leaders." },
  { term: "Network effect", category: "Strategy", definition: "A property where a product becomes more valuable to each user as more people use it." },
  { term: "First-mover advantage", category: "Strategy", definition: "The temporary edge gained by being the first credible entrant into a new market or category." },
  { term: "Vertical integration", category: "Strategy", definition: "Owning multiple stages of your own supply or distribution chain, rather than depending on external partners at each stage." },
];
