import type { Industry } from "./knowledgeTypes";

export const INDUSTRIES: Industry[] = [
  {
    slug: "fmcg-retail",
    name: "FMCG & retail",
    tagline: "Won at the shelf, in the truck, and in the customer's habit",
    summary:
      "Fast-moving consumer goods and general retail compete on three fronts at once: being physically available everywhere the customer shops, being the brand customers reach for without thinking, and running thin margins across enormous volume.",
    structure: [
      "Revenue is a function of distribution reach (how many outlets stock you) multiplied by velocity (how fast each outlet sells through).",
      "Margins are thin per unit; profit comes from volume and inventory turnover, not per-item markup.",
      "Trade — distributors, wholesalers, and retail partners — often has more day-to-day power over what customers see than advertising does.",
      "Brand recall substitutes for a sales pitch — most FMCG purchases are made in seconds, on habit.",
      "Modern trade (chains) and general trade (kirana/independent stores) require genuinely different playbooks for pricing, credit, and merchandising.",
    ],
    strategies: [
      { title: "Win the shelf before you win the ad", body: "Distribution reach usually beats advertising spend in FMCG — a product customers can't find loses to a mediocre product they can. Build outlet coverage and merchandising presence before scaling paid demand generation." },
      { title: "Protect margin as a fixed percentage", body: "Split retail price into cost, distribution, and margin as fixed proportions rather than letting margin be whatever's left over — otherwise rising costs quietly eat profitability without anyone deciding it should." },
      { title: "Use recurring, need-based triggers", body: "The strongest FMCG marketing connects the product to something the customer already needs regularly, not to a feature — convenience, hygiene, status, or habit outlast any single ad campaign." },
      { title: "Bundle slow movers with fast movers", body: "A wide product line always has laggards; bundling them with proven sellers, rather than discounting them alone, moves stock without training customers to expect discounts." },
      { title: "Build trade relationships, not just consumer ones", body: "Retailers and distributors decide shelf placement and push; incentive structures, credit terms, and relationship quality with trade partners often move sales more than consumer advertising alone." },
      { title: "Localise for regional taste and language", body: "India's FMCG winners routinely adapt flavour, packaging size, and messaging by region rather than running one national formula — a product that wins in one state can flop in another for reasons that have nothing to do with quality." },
      { title: "Defend with an entry barrier, not just a good product", body: "Commoditised categories get copied fast; durable FMCG winners build a real barrier — distribution network, brand trust, patented formulation, or manufacturing scale — around an otherwise easy-to-copy product." },
    ],
    benchmarks: [
      { metric: "Gross margin", typical: "25–45%", note: "Varies hugely by category — packaged food runs thinner than personal care or cosmetics." },
      { metric: "Inventory turnover", typical: "8–15× per year", note: "Fast-moving staples turn faster; premium or seasonal lines turn slower." },
      { metric: "Distribution reach target", typical: "Direct + indirect coverage of the addressable outlet base in the pilot region before expanding" },
      { metric: "Marketing spend", typical: "5–12% of revenue", note: "New entrants building awareness often spend at the higher end temporarily." },
      { metric: "Working capital cycle", typical: "30–60 days", note: "Driven by trade credit terms extended to distributors and retailers." },
    ],
    pitfalls: [
      "Launching too many SKUs before any single one has proven distribution and repeat purchase.",
      "Pricing without protecting the fixed margin structure, so trade and input cost inflation silently erodes profit.",
      "Treating modern trade and general trade with the same commercial terms, when their economics are fundamentally different.",
      "Underinvesting in trade relationships while overspending on consumer advertising.",
      "Ignoring regional taste differences and launching one national formula everywhere at once.",
    ],
    caseStudySlugs: ["patanjali-fmcg-disruption", "dmart-cash-and-carry", "amul-cooperative-model", "titan-tanishq-trust", "haldirams-snack-empire", "ikea-india-adaptation"],
    starterKit: [
      { kind: "tool", slug: "revenue-multiplier", label: "Revenue multiplier" },
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "critical-success-factors", label: "Critical success factors" },
      { kind: "journey", slug: "sales-have-stalled", label: "Sales have stalled journey" },
    ],
  },
  {
    slug: "d2c-ecommerce",
    name: "D2C & e-commerce",
    tagline: "The margin you save by skipping retail, spent winning attention instead",
    summary:
      "Direct-to-consumer and e-commerce businesses trade the reach of traditional retail for full control of the customer relationship, pricing, and data — which only pays off if the cost of digitally acquiring that customer stays below what they're worth.",
    structure: [
      "The entire business lives or dies on the relationship between customer acquisition cost and customer lifetime value.",
      "Logistics and returns handling are core operations, not an afterthought — they decide real margin, not just headline margin.",
      "Paid channels get more expensive as a category matures; organic content and retention become the durable moat over time.",
      "Reviews, ratings, and social proof substitute for the in-store trust a physical retailer would have provided.",
      "Cash conversion cycle matters enormously — inventory purchased today is often sold weeks before payment gateways settle the cash.",
    ],
    strategies: [
      { title: "Know your CAC-to-LTV ratio before you scale spend", body: "Scaling paid acquisition before lifetime value comfortably exceeds acquisition cost just accelerates cash burn — profitable unit economics has to exist before volume, not the other way round." },
      { title: "Build one killer product before a catalogue", body: "A wide catalogue with no clear best-seller confuses both marketing and inventory planning; most successful D2C brands became known for one thing before expanding the line." },
      { title: "Treat content as owned distribution", body: "Every rupee of paid traffic disappears when spend stops; content, community, and email/WhatsApp lists are the only channels a brand actually owns and keeps compounding." },
      { title: "Reduce return rates deliberately", body: "Returns quietly destroy D2C margins through reverse logistics cost and damaged inventory — sizing guides, honest photography, and clear expectations reduce returns more cheaply than any ad campaign increases sales." },
      { title: "Use influencer and creator marketing for trust, not just reach", body: "Smaller, credible creators often convert better than broad reach campaigns because their endorsement functions as social proof, substituting for the trust a physical store would build automatically." },
      { title: "Design the unboxing as a marketing moment", body: "The delivered package is the only physical touchpoint a D2C brand gets — treating it as disposable wastes the single moment most likely to generate a repeat purchase or a shared post." },
    ],
    benchmarks: [
      { metric: "CAC-to-LTV ratio", typical: "At least 1:3", note: "Below this, growth typically isn't sustainable without external funding." },
      { metric: "Return rate", typical: "10–30%", note: "Apparel runs highest; consumables and accessories run lowest." },
      { metric: "Repeat purchase rate", typical: "20–40% within 6 months for a healthy brand" },
      { metric: "Gross margin after logistics", typical: "40–60%", note: "Before logistics and payment gateway fees are subtracted, headline margin often looks better than it is." },
      { metric: "Cash conversion cycle", typical: "Often negative-to-short if inventory is lean and payment gateways settle quickly" },
    ],
    pitfalls: [
      "Scaling paid ad spend before unit economics (CAC vs LTV) are actually proven.",
      "Launching a wide catalogue instead of proving one hero product first.",
      "Under-investing in reducing return rates, which silently erodes margin more than any single cost line.",
      "Depending entirely on one paid channel that can change algorithms or pricing overnight.",
      "Ignoring the cash conversion cycle and running out of working capital despite healthy-looking sales.",
    ],
    caseStudySlugs: ["zomato-swiggy-funding-war", "boat-d2c-audio-brand"],
    starterKit: [
      { kind: "tool", slug: "acquisition-cost", label: "Acquisition cost auditor" },
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "framework", slug: "content-engine", label: "Content engine setup" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
  {
    slug: "restaurants-qsr",
    name: "Restaurants & QSR",
    tagline: "A margin business disguised as a hospitality business",
    summary:
      "Restaurants and quick-service chains run on thin food-cost margins, high fixed costs (rent, staff), and a turnaround-time discipline that decides whether a location is profitable or barely surviving.",
    structure: [
      "Food cost, labour cost, and rent together typically consume the large majority of revenue, leaving a thin operating margin.",
      "Table or order turnaround time directly determines how much revenue one location can generate in a day.",
      "Menu engineering — which items to promote, price high, or quietly retire — matters as much as cooking quality.",
      "Delivery platforms have added a new, high-commission channel that changes unit economics per order.",
      "Consistency across locations, not creativity at one location, is what makes a multi-outlet restaurant business scale.",
    ],
    strategies: [
      { title: "Engineer the menu around margin, not just popularity", body: "Not every popular dish is profitable; menu engineering promotes high-margin, popular items and quietly repositions or drops low-margin, low-popularity ones." },
      { title: "Cut turnaround time deliberately", body: "Table or order turnaround time is a direct revenue lever — reducing it by even a few minutes per order compounds into meaningfully more covers served per day from the same space." },
      { title: "Localise the menu for the market", body: "Global chains that succeeded in India specifically adapted flavour and menu items to local taste rather than importing an unchanged international menu." },
      { title: "Price delivery-platform items to protect margin", body: "Delivery platform commissions can consume 15–30% of order value — pricing delivery-only items to account for this, rather than mirroring dine-in prices, protects margin on that channel specifically." },
      { title: "Build SOPs before opening a second location", body: "A single well-run restaurant often depends on one skilled owner-operator; multi-location success requires documenting exactly how that first location runs so quality doesn't depend on any one person." },
      { title: "Use a loyalty mechanism to fight discount dependency", body: "Constant discounting trains customers to wait for deals; a loyalty or frequency mechanism rewards genuine repeat behaviour without training the whole customer base to expect a discount." },
    ],
    benchmarks: [
      { metric: "Food cost", typical: "28–35% of menu price", note: "Premium or specialty ingredients can run higher if priced accordingly." },
      { metric: "Labour cost", typical: "20–30% of revenue" },
      { metric: "Rent / occupancy cost", typical: "8–15% of revenue for a well-located outlet" },
      { metric: "Table turnaround", typical: "45–75 minutes for full-service dining; under 10 minutes for QSR" },
      { metric: "Delivery platform commission", typical: "15–30% of order value" },
    ],
    pitfalls: [
      "Pricing delivery-platform items the same as dine-in, ignoring the commission that eats the margin.",
      "Opening a second location before the first one's operations are documented into repeatable SOPs.",
      "Chasing footfall through constant discounting instead of a genuine loyalty mechanism.",
      "Ignoring turnaround time as a lever, treating it only as a service-quality issue rather than a revenue issue.",
      "Keeping a bloated menu that increases inventory complexity without meaningfully increasing sales.",
    ],
    caseStudySlugs: ["mcdonalds-india-localization"],
    starterKit: [
      { kind: "tool", slug: "revenue-multiplier", label: "Revenue multiplier" },
      { kind: "framework", slug: "sop-builder", label: "SOP builder" },
      { kind: "framework", slug: "cx-touchpoints", label: "Experience touchpoint audit" },
      { kind: "journey", slug: "sales-have-stalled", label: "Sales have stalled journey" },
    ],
  },
  {
    slug: "manufacturing",
    name: "Manufacturing",
    tagline: "Won on cost per unit, quality consistency, and not missing the next shift",
    summary:
      "Manufacturing businesses compete on the discipline of turning raw material into finished goods at a predictable cost and quality, where small process improvements compound into large margin gains at scale.",
    structure: [
      "Fixed costs (machinery, factory space) are high, so capacity utilisation directly decides unit economics.",
      "Raw material cost volatility can swing margins more than any pricing decision the business makes.",
      "Quality consistency, not peak quality, is what large B2B and retail buyers actually evaluate suppliers on.",
      "Working capital is often tied up for months between raw material purchase and finished goods payment.",
      "A single bottleneck process typically limits total output more than any other single factor.",
    ],
    strategies: [
      { title: "Find and fix the actual bottleneck", body: "In any production line, one step limits total output; improving any other step produces no real gain until that specific bottleneck is addressed." },
      { title: "Build a real cost or IP moat, not just current low pricing", body: "Manufacturing margins get copied fast without a durable advantage — economies of scale, proprietary process, or patented technology protect a cost position that pure pricing discipline alone can't." },
      { title: "Reduce turnaround time as a trust-building metric", body: "Faster, more predictable order-to-delivery time builds buyer trust and repeat orders as much as price does, especially in B2B manufacturing relationships." },
      { title: "Adopt just-in-time inventory carefully", body: "Reducing inventory holding frees significant working capital, but only where supplier reliability is genuinely strong enough to avoid production stoppages." },
      { title: "Standardise quality with documented process, not tribal skill", body: "Quality that depends on one experienced operator's judgment doesn't scale reliably across shifts or new hires; documented process parameters do." },
      { title: "Diversify raw material sourcing", body: "Single-supplier dependency exposes the whole operation to one disruption; qualifying at least a second source protects continuity even if it's rarely used." },
    ],
    benchmarks: [
      { metric: "Capacity utilisation", typical: "75–90% for a healthy operation", note: "Below this, fixed costs are being spread over too little output." },
      { metric: "Raw material cost", typical: "40–65% of cost of goods sold, category-dependent" },
      { metric: "Inventory turnover", typical: "4–8× per year for finished goods" },
      { metric: "On-time delivery rate", typical: "95%+ for a trusted B2B supplier" },
      { metric: "Working capital cycle", typical: "60–120 days between raw material purchase and customer payment" },
    ],
    pitfalls: [
      "Running at low capacity utilisation while fixed costs stay the same, quietly destroying margin.",
      "Depending on a single raw material supplier with no qualified backup.",
      "Letting quality depend on individual operator skill instead of documented process.",
      "Chasing just-in-time inventory savings without supplier reliability solid enough to support it.",
      "Competing on price alone without a cost structure or IP advantage that's actually hard to copy.",
    ],
    caseStudySlugs: ["nokia-smartphone-fall", "kodak-digital-camera", "xiaomi-india-entry", "segway-failure", "fevicol-category-ownership"],
    starterKit: [
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "sop-builder", label: "SOP builder" },
      { kind: "tool", slug: "moat-builder", label: "Moat builder" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
  {
    slug: "apparel-textiles",
    name: "Apparel & textiles",
    tagline: "Seasonal, trend-driven, and unforgiving of dead stock",
    summary:
      "Apparel and textile businesses balance the creative risk of trend-driven design against the operational discipline of inventory that ages fast — last season's stock is worth a fraction of this season's.",
    structure: [
      "Seasonal cycles mean design and buying decisions are made months before the actual selling season.",
      "Dead stock from missed trends is one of the largest silent profit destroyers in the category.",
      "Brand and positioning decide pricing power far more than raw fabric or manufacturing cost does.",
      "Sizing and fit inconsistency drive a large share of returns, especially online.",
      "Both fast-fashion (frequent, cheap, trend-chasing) and premium (slower, brand-led) models can work, but require entirely different operating disciplines.",
    ],
    strategies: [
      { title: "Order in tranches, not one big seasonal bet", body: "Placing a smaller first order and reordering fast-selling styles based on early signal reduces the dead-stock risk of betting the whole season on an unproven design." },
      { title: "Build brand equity to escape pure price competition", body: "Fabric and stitching are relatively easy to copy; a genuine brand story and consistent positioning are what let apparel businesses charge more than a commodity competitor for a similar garment." },
      { title: "Bundle and discount ageing stock deliberately, not desperately", body: "Planned clearance cycles protect brand perception better than constant unplanned discounting, which trains customers to always wait for a sale." },
      { title: "Fix sizing consistency before scaling online", body: "Inconsistent sizing between styles is one of the most preventable causes of returns — standardising and clearly communicating fit reduces returns more cheaply than any other single fix." },
      { title: "Localise for climate and occasion, not just national trend", body: "Regional climate, festival calendars, and occasion-wear needs vary enormously across India — a national one-size collection strategy underperforms regionally tuned buying." },
      { title: "Protect margin with vertical integration where it matters most", body: "Owning design and key manufacturing stages (rather than depending entirely on external job-workers) protects both speed-to-market and margin on hero styles." },
    ],
    benchmarks: [
      { metric: "Gross margin", typical: "40–60%", note: "Before markdowns and clearance sales are accounted for." },
      { metric: "Sell-through rate", typical: "Target 80%+ of a season's stock sold at full or near-full price" },
      { metric: "Return rate (online)", typical: "20–40%", note: "Among the highest of any e-commerce category, driven by fit uncertainty." },
      { metric: "Inventory turnover", typical: "3–6× per year", note: "Faster for fast-fashion, slower for premium/occasion wear." },
    ],
    pitfalls: [
      "Betting the full season's buy on one design trend without a tranche-and-reorder approach.",
      "Letting sizing inconsistency between styles drive avoidable returns.",
      "Discounting unpredictably rather than through a planned clearance cycle, training customers to wait.",
      "Copying national trend collections without adapting for regional climate and occasion needs.",
      "Competing purely on price in a category where brand story is what actually protects margin.",
    ],
    caseStudySlugs: ["raymond-apparel-branding"],
    starterKit: [
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "brand-signals", label: "Brand signal alignment" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "real-estate",
    name: "Real estate",
    tagline: "Trust, timing, and capital discipline decide who survives the cycle",
    summary:
      "Real estate businesses — developers, brokers, and co-working or rental operators — manage long capital cycles and low-frequency, high-stakes customer trust, where one cycle's overreach can sink an otherwise sound business.",
    structure: [
      "Capital is deployed years before revenue is realised, making cash flow timing as important as the underlying project economics.",
      "Customer trust is the primary currency — most buyers have been burned or know someone who has, and the industry carries that reputation cost.",
      "Local market knowledge (regulatory approvals, land titles, neighbourhood dynamics) matters more than national brand in most transactions.",
      "Debt financing is central to the business model, which makes debt discipline a survival skill, not an optional one.",
      "Both project-based (developers) and recurring-revenue (rental, co-working) models exist under the same broad industry, with very different cash dynamics.",
    ],
    strategies: [
      { title: "Underwrite for a downturn, not the current cycle", body: "Real estate cycles turn; projects financed assuming current growth and pricing continue indefinitely are the ones that collapse when the market corrects." },
      { title: "Build trust infrastructure deliberately", body: "Clear documentation, transparent pricing, and visible delivery track record substitute for the trust a first-time or wary buyer can't otherwise verify." },
      { title: "Match debt structure to project timeline", body: "Short-term debt financing a long-gestation project creates a mismatch that can force distressed decisions purely on cash flow timing, independent of the project's underlying quality." },
      { title: "Don't confuse a story with a real business model", body: "Rapid expansion funded by growth narrative rather than proven unit economics at the existing footprint is a pattern that has collapsed more than one well-known real-estate-adjacent business." },
      { title: "Localise deeply rather than replicate nationally", body: "Regulatory approval processes, buyer expectations, and price sensitivity vary sharply by city and even by neighbourhood — a playbook that worked in one market rarely transfers unchanged." },
      { title: "Diversify beyond a single project or asset class", body: "Concentration in one large project or one asset type means one delay or downturn threatens the whole business; a portfolio approach spreads that risk." },
    ],
    benchmarks: [
      { metric: "Project debt-to-equity", typical: "Should stay below roughly 2×, matched to project cash flow timeline" },
      { metric: "Pre-sales before construction start", typical: "20–40% of inventory, common industry practice to fund early construction" },
      { metric: "Rental yield (commercial)", typical: "6–10% annually of asset value" },
      { metric: "Sales cycle length", typical: "Weeks to several months, depending on ticket size and buyer type" },
    ],
    pitfalls: [
      "Financing a long-gestation project with short-term debt that doesn't match the actual timeline.",
      "Scaling on growth narrative and story rather than proven unit economics at existing sites.",
      "Underestimating how much trust infrastructure (documentation, transparency) matters to wary buyers.",
      "Concentrating risk in a single large project or asset class.",
      "Copying a playbook from one city's market dynamics directly into another without local adaptation.",
    ],
    caseStudySlugs: ["wework-collapse"],
    starterKit: [
      { kind: "framework", slug: "borrowing-readiness", label: "Borrowing readiness check" },
      { kind: "framework", slug: "brand-signals", label: "Brand signal alignment" },
      { kind: "tool", slug: "cash-runway", label: "Cash flow runway" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
  {
    slug: "healthcare-clinics",
    name: "Healthcare & clinics",
    tagline: "A trust business first, an operations business second",
    summary:
      "Healthcare providers — clinics, diagnostics, and hospitals — win on a combination patients rarely separate consciously: clinical trust, wait time, and the emotional experience of an inherently stressful visit.",
    structure: [
      "Patient trust compounds slowly through outcomes and word of mouth, and is extremely costly to rebuild once damaged.",
      "Turnaround time (for diagnostics, appointments, results) is both an operational metric and a trust signal patients feel directly.",
      "Regulatory compliance and accreditation function as both a legal requirement and a genuine competitive moat.",
      "Referral networks (other doctors, previous patients) often drive more volume than any advertising channel.",
      "Staffing quality — especially front-line clinical and reception staff — shapes patient experience more than facility quality alone.",
    ],
    strategies: [
      { title: "Treat turnaround time as a patient-trust metric", body: "Faster, more predictable diagnostic and appointment turnaround isn't just operational efficiency — patients directly experience it as a sign of competence and care." },
      { title: "Invest in accreditation as a real moat", body: "Regulatory certifications and accreditations are slow and costly to obtain, which is exactly what makes them a durable competitive barrier once earned." },
      { title: "Build referral relationships deliberately", body: "A structured relationship with referring doctors and a genuine focus on patient experience (which drives word-of-mouth referral) typically outperforms advertising spend in healthcare." },
      { title: "Standardise the patient experience across every touchpoint", body: "Reception, waiting, consultation, and billing are all touchpoints patients judge collectively — excellence in the clinical visit can be undone by a poor billing or reception experience." },
      { title: "Expand geographically only after the flagship location proves its model", body: "Healthcare quality is hard to fake at scale; expanding to a second facility before the first has a proven, documented operating model risks diluting the trust that took years to build." },
      { title: "Use technology to reduce wait time and paperwork friction", body: "Digital scheduling, records, and reporting reduce both the operational cost and the emotional friction patients experience during an already stressful visit." },
    ],
    benchmarks: [
      { metric: "Patient wait time", typical: "Target under 15–20 minutes for scheduled appointments" },
      { metric: "Diagnostic report turnaround", typical: "Same-day for standard tests is now a common patient expectation" },
      { metric: "Bed/chair occupancy (facility-based)", typical: "70–85% for healthy utilisation without excessive patient wait" },
      { metric: "Referral share of new patients", typical: "30–50% for an established, trusted practice" },
    ],
    pitfalls: [
      "Expanding to new locations before the first facility's operating model is fully documented and proven.",
      "Treating reception and billing experience as separate from clinical quality in the patient's mind.",
      "Underinvesting in accreditation, missing a durable moat competitors will find harder to catch up on.",
      "Ignoring turnaround time as a trust signal, treating it as purely operational.",
      "Depending entirely on advertising rather than building genuine referral relationships.",
    ],
    caseStudySlugs: ["apollo-hospitals-healthcare-scale"],
    starterKit: [
      { kind: "framework", slug: "cx-touchpoints", label: "Experience touchpoint audit" },
      { kind: "framework", slug: "service-ladder", label: "Service maturity ladder" },
      { kind: "tool", slug: "moat-builder", label: "Moat builder" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "education-coaching",
    name: "Education & coaching",
    tagline: "Outcomes build the brand; enrolment growth without outcomes breaks it",
    summary:
      "Education and coaching businesses sell a promise of future outcome that's hard to verify upfront, which makes trust, demonstrated results, and word of mouth the real currency — growth funded ahead of proven outcomes is the category's most common failure pattern.",
    structure: [
      "Customer decision cycles are often emotional and high-stakes (a career, a child's future), making trust-building content and testimonials unusually powerful.",
      "Outcome measurement (did the student actually succeed) is hard to verify from outside, which rewards businesses that measure and publish it honestly.",
      "Enrolment-driven revenue creates a constant temptation to prioritise growth marketing over program quality.",
      "Instructor or mentor quality is often the single biggest driver of both outcomes and word of mouth.",
      "Both offline (classroom, in-person coaching) and online (digital courses, hybrid) models coexist, with very different cost structures and completion-rate challenges.",
    ],
    strategies: [
      { title: "Measure and publish real outcomes, not just enrolment", body: "Outcome data (placement rates, score improvements, completion rates) is the strongest trust signal in education — businesses that measure and share it honestly build durable reputation that marketing alone can't buy." },
      { title: "Grow enrolment only as fast as quality can be maintained", body: "The most damaging pattern in education businesses is scaling enrolment and marketing spend faster than instructor quality and support infrastructure can keep pace with." },
      { title: "Invest in instructor quality as the core product", body: "In most coaching and education businesses, the instructor or mentor is the actual product; underinvesting here to protect margin usually shows up in outcomes and word of mouth within a cohort or two." },
      { title: "Use social proof from real outcomes, not manufactured testimonials", body: "Prospective students and parents are unusually good at sensing manufactured or exaggerated testimonials — specific, verifiable outcome stories convert far better and protect long-term trust." },
      { title: "Design for completion, not just enrolment", body: "In online and hybrid education, low completion rates quietly undermine both outcomes and referrals — completion-focused design (pacing, accountability, community) often matters more than content quality alone." },
      { title: "Build a referral engine around genuinely satisfied families or learners", body: "Education decisions are frequently made on trusted personal recommendation more than any other consumer category — a structured referral approach compounds faster here than in most industries." },
    ],
    benchmarks: [
      { metric: "Course/program completion rate", typical: "40–70% online, 70–90% for in-person structured programs" },
      { metric: "Customer acquisition cost", typical: "Often high relative to a single course price; recovered through lifetime value across multiple courses or referrals" },
      { metric: "Referral share of enrolment", typical: "25–45% for a trusted, established program" },
      { metric: "Instructor cost", typical: "20–35% of program revenue for quality-led programs" },
    ],
    pitfalls: [
      "Scaling enrolment and marketing spend faster than instructor quality and support can keep pace with.",
      "Measuring and celebrating enrolment growth while outcomes quietly decline.",
      "Manufacturing or exaggerating testimonials, which erodes trust once discovered.",
      "Underinvesting in program completion design, especially for online formats.",
      "Expanding into new subjects or geographies before the flagship program's outcomes are consistently proven.",
    ],
    caseStudySlugs: ["byjus-overexpansion"],
    starterKit: [
      { kind: "framework", slug: "nps-engine", label: "Recommendation score engine" },
      { kind: "framework", slug: "training-evaluation", label: "Training that sticks" },
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "journey", slug: "want-to-grow-safely", label: "Ready to grow, afraid to break it journey" },
    ],
  },
  {
    slug: "auto-dealerships",
    name: "Auto dealerships",
    tagline: "The sale is the beginning of the relationship, not the end",
    summary:
      "Automotive dealerships and service networks make a large share of real profit not on the vehicle sale itself but on financing, accessories, and — most durably — the years of service and parts revenue that follow.",
    structure: [
      "Vehicle sale margins are often thin; financing, insurance, accessories, and service form the more durable profit centres.",
      "Service network quality and convenience create a genuine switching cost that keeps customers returning for years.",
      "Inventory financing (holding vehicles before sale) ties up significant working capital.",
      "Manufacturer relationships and territory rights function as a real entry barrier for new competitors.",
      "Customer trust in a dealership compounds across the ownership lifecycle — service experience shapes the next purchase decision more than the original sale did.",
    ],
    strategies: [
      { title: "Treat service revenue as the real business, not an add-on", body: "The service department typically carries higher, more stable margins than vehicle sales — building genuine service quality and convenience protects a recurring revenue stream that sales alone can't match." },
      { title: "Use the sale to start a multi-year relationship", body: "The strongest dealerships design the first sale specifically to earn years of service visits and the next purchase, rather than treating each sale as a standalone transaction." },
      { title: "Manage inventory financing discipline tightly", body: "Vehicles sitting unsold tie up expensive financing; disciplined ordering matched to actual local demand protects margin more than any single sales promotion." },
      { title: "Bundle financing and accessories thoughtfully", body: "Financing, insurance, and accessory attachment at the point of sale meaningfully increase per-transaction profit when presented as genuine value, not pressure." },
      { title: "Build service turnaround time as a competitive differentiator", body: "Faster, more transparent service turnaround directly drives repeat visits and referrals in a category where customers have real alternatives for where to service their vehicle." },
      { title: "Defend territory relationships with the manufacturer", body: "Manufacturer territory rights are a genuine entry barrier — protecting and deepening that relationship is as strategically important as any customer-facing initiative." },
    ],
    benchmarks: [
      { metric: "Service department margin", typical: "Often higher than new vehicle sales margin, sometimes 40%+ gross" },
      { metric: "Inventory turnover", typical: "8–12× per year for new vehicles" },
      { metric: "Service retention rate", typical: "Target 60%+ of customers returning for service within warranty period" },
      { metric: "Finance & insurance attach rate", typical: "40–70% of vehicle sales for a well-run dealership" },
    ],
    pitfalls: [
      "Treating each vehicle sale as a standalone transaction rather than the start of a service relationship.",
      "Over-ordering inventory relative to actual local demand, tying up expensive financing.",
      "Underinvesting in service department speed and transparency, losing recurring high-margin revenue.",
      "Neglecting the manufacturer relationship that protects territory rights.",
      "Pressuring customers on financing and accessory attachment in a way that damages long-term trust.",
    ],
    caseStudySlugs: ["maruti-suzuki-dealership-network"],
    starterKit: [
      { kind: "framework", slug: "switching-barriers", label: "Switching barrier designer" },
      { kind: "framework", slug: "service-ladder", label: "Service maturity ladder" },
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "logistics-transport",
    name: "Logistics & transport",
    tagline: "Won on utilisation, turnaround time, and route density",
    summary:
      "Logistics and transport businesses turn a profit on a narrow spread between fixed capacity costs and variable delivery revenue, where fleet utilisation and route density decide the difference between thin profit and real loss.",
    structure: [
      "High fixed costs (fleet, hubs, technology) mean utilisation rate is the single biggest lever on profitability.",
      "Route density — how many deliveries fit efficiently along one route — compounds cost efficiency at scale.",
      "Turnaround time and reliability are the actual product customers are buying, more than price alone.",
      "Local, last-mile operations often require completely different tactics from long-haul or hub-based logistics.",
      "Technology for routing, tracking, and matching supply to demand has become a genuine competitive differentiator, not just a support function.",
    ],
    strategies: [
      { title: "Optimise for utilisation before adding capacity", body: "Adding more vehicles or hubs without first maximising utilisation of existing capacity just multiplies the same underlying inefficiency at greater cost." },
      { title: "Build density before expanding geography", body: "A logistics network with high delivery density in one region is more profitable and more defensible than a thin, spread-out network across many regions." },
      { title: "Treat turnaround time as the actual product being sold", body: "Customers rarely evaluate logistics purely on price — reliable, predictable turnaround time is what actually earns repeat business and premium pricing." },
      { title: "Use hub-and-spoke design to cut route complexity", body: "Routing through central hubs dramatically reduces the number of direct connections needed to serve a large, scattered set of origins and destinations, at the cost of some added transit time." },
      { title: "Balance the two sides of matching supply to demand", body: "In demand-matching logistics models (delivery riders and orders, for instance), the genuinely scarcer side — not the more visible side — is usually the actual bottleneck worth solving first." },
      { title: "Invest in technology for routing and tracking, not just fleet size", body: "Smarter routing and real-time tracking often improve margins more than adding raw fleet capacity, especially in dense urban last-mile operations." },
    ],
    benchmarks: [
      { metric: "Fleet utilisation", typical: "70–85% for a healthy operation" },
      { metric: "On-time delivery rate", typical: "90%+ for a trusted logistics provider" },
      { metric: "Cost per delivery", typical: "Falls sharply with route density; a key metric to track by zone" },
      { metric: "Fuel and maintenance", typical: "25–40% of operating cost for owned-fleet models" },
    ],
    pitfalls: [
      "Expanding fleet or hub capacity before maximising utilisation of what already exists.",
      "Spreading thin across many regions instead of building density in fewer regions first.",
      "Competing purely on price when turnaround reliability is what customers actually value most.",
      "Underinvesting in routing and tracking technology relative to raw fleet expansion.",
      "Ignoring which side of a supply-demand matching problem is the real bottleneck.",
    ],
    caseStudySlugs: ["ola-vs-uber-india"],
    starterKit: [
      { kind: "framework", slug: "execution-scoreboard", label: "Execution scoreboard" },
      { kind: "framework", slug: "scale-up-plan", label: "Scale-up trio" },
      { kind: "tool", slug: "revenue-multiplier", label: "Revenue multiplier" },
      { kind: "journey", slug: "want-to-grow-safely", label: "Ready to grow, afraid to break it journey" },
    ],
  },
  {
    slug: "financial-services",
    name: "Financial services",
    tagline: "Trust and risk discipline are the product, not just compliance overhead",
    summary:
      "Financial services businesses — NBFCs, insurance, advisory, and fintech — sell trust and risk management as the core product, where a single lapse in risk discipline or trust can undo years of otherwise sound growth.",
    structure: [
      "Regulatory compliance is both a genuine cost and a real competitive moat once earned, since it's slow and costly for new entrants to replicate.",
      "Risk assessment quality (who to lend to, insure, or advise, and on what terms) is the actual core competency, more than the product wrapper around it.",
      "Trust compounds over years and can be destroyed by a single well-publicised failure or scandal.",
      "Distribution — through agents, digital channels, or partnerships — often matters as much as the underlying financial product design.",
      "Customer lifetime value is unusually high in this category, since financial relationships often span years or decades once trust is established.",
    ],
    strategies: [
      { title: "Treat risk assessment as the real core competency", body: "The actual differentiator in lending, insurance, and advisory businesses is the quality of risk assessment — everything else (product design, marketing) is secondary to getting this right." },
      { title: "Build compliance as a genuine moat, not a checkbox", body: "Regulatory compliance done deeply and early becomes a durable advantage new entrants take years to replicate, rather than a cost to minimise." },
      { title: "Protect trust more carefully than growth rate", body: "A single well-publicised trust failure can undo years of growth in financial services faster than in almost any other industry — growth decisions should be weighed against trust risk explicitly." },
      { title: "Design distribution deliberately", body: "Whether through agents, digital-only channels, or partnerships with other businesses, the distribution model shapes both cost of acquisition and the trust customers extend to the product." },
      { title: "Use the long customer lifetime value to justify patient acquisition spend", body: "Financial relationships often last years or decades once trust is established — this justifies more patient, relationship-focused acquisition spend than a typical one-time-purchase category." },
      { title: "Diversify the loan book or risk pool deliberately", body: "Concentration in one customer segment, geography, or risk category exposes the business to a single shock; deliberate diversification protects against that concentration risk." },
    ],
    benchmarks: [
      { metric: "Non-performing asset (NPA) ratio", typical: "Should stay well below industry-average thresholds for the specific lending category" },
      { metric: "Customer acquisition cost", typical: "Justified against a multi-year customer lifetime value, not a single transaction" },
      { metric: "Compliance and risk team investment", typical: "A meaningfully growing share of operating cost as the business scales, not a flat line" },
      { metric: "Customer retention", typical: "70%+ annually for an established, trusted relationship-based provider" },
    ],
    pitfalls: [
      "Prioritising growth rate over risk assessment discipline, especially during a favourable market cycle.",
      "Treating regulatory compliance as a cost to minimise rather than a moat to build.",
      "Concentrating risk in a single customer segment or geography.",
      "Underestimating how fast trust can be destroyed by a single publicised failure.",
      "Copying a distribution model from a very different market without adapting for local trust dynamics.",
    ],
    caseStudySlugs: ["paytm-wallet-to-superapp"],
    starterKit: [
      { kind: "framework", slug: "borrowing-readiness", label: "Borrowing readiness check" },
      { kind: "tool", slug: "moat-builder", label: "Moat builder" },
      { kind: "framework", slug: "core-values", label: "Core value charter" },
      { kind: "journey", slug: "competitor-could-copy-me", label: "Competitor could copy me tomorrow journey" },
    ],
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    tagline: "A perishable-inventory business wearing a service-experience costume",
    summary:
      "Hotels, resorts, and accommodation businesses sell a room-night that's worthless the moment it goes unsold — which makes occupancy, rate management, and guest experience three sides of the same profitability problem.",
    structure: [
      "Room-nights are perishable inventory — unsold capacity is gone forever, unlike physical stock that can wait for a future sale.",
      "Revenue management (balancing occupancy against average rate) is a distinct discipline from guest experience, though both drive the same bottom line.",
      "Guest experience and review scores now function as the primary trust signal for new guests, more than brand alone.",
      "Online travel platforms have added a powerful but commission-heavy distribution channel alongside direct booking.",
      "Seasonality and local events create demand swings that reward dynamic pricing and flexible staffing.",
    ],
    strategies: [
      { title: "Manage occupancy and rate together, not separately", body: "Chasing occupancy alone by dropping rates too far, or protecting rate alone while rooms sit empty, both destroy revenue — the two decisions have to be optimised together, day by day." },
      { title: "Use dynamic pricing for perishable inventory", body: "A room unsold tonight earns nothing tomorrow; pricing that flexes with real-time demand captures more of the revenue perishable inventory otherwise loses to empty rooms or underpriced peak nights." },
      { title: "Invest in guest experience as the review-generation engine", body: "Review scores now drive booking decisions as much as brand or price — genuinely excellent, well-trained guest-facing staff are a direct revenue investment, not just a service cost." },
      { title: "Balance direct and platform booking channels", body: "Online travel platforms bring valuable reach but charge significant commission; building direct booking relationships (loyalty, repeat guests) protects margin platforms alone can't." },
      { title: "Turn small acts of unexpected care into stories", body: "Guests remember and share moments of unexpected thoughtfulness — a small proactive gesture handled well often generates more organic marketing than a formal campaign." },
      { title: "Plan staffing around genuine seasonal demand patterns", body: "Overstaffing in low season and understaffing in peak season both damage margin and guest experience — staffing plans built around real historical demand patterns outperform flat year-round staffing." },
    ],
    benchmarks: [
      { metric: "Occupancy rate", typical: "65–80% for a healthy property annually" },
      { metric: "Average daily rate (ADR)", typical: "Tracked alongside occupancy as RevPAR (revenue per available room)" },
      { metric: "Online travel platform commission", typical: "15–25% of booking value" },
      { metric: "Guest review score target", typical: "4.3+ out of 5 to meaningfully influence booking decisions" },
    ],
    pitfalls: [
      "Chasing occupancy through deep discounting without considering the impact on average rate.",
      "Over-relying on online travel platforms without building any direct booking relationship.",
      "Understaffing during peak season to protect short-term costs at the expense of guest experience and reviews.",
      "Treating guest experience investment as a cost rather than a direct driver of review-fuelled bookings.",
      "Ignoring seasonality in staffing and pricing planning.",
    ],
    caseStudySlugs: ["airbnb-photography-fix"],
    starterKit: [
      { kind: "framework", slug: "cx-touchpoints", label: "Experience touchpoint audit" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "framework", slug: "nps-engine", label: "Recommendation score engine" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "b2b-services-agencies",
    name: "B2B services & agencies",
    tagline: "The product is trust in a person or team, delivered repeatedly",
    summary:
      "Consulting firms, agencies, and B2B service providers sell expertise and execution that's hard to evaluate before purchase, which makes reputation, case studies, and consistent delivery quality the actual growth engine.",
    structure: [
      "Revenue is usually tied directly to billable hours or defined project scope, which caps growth without either raising rates or adding capacity.",
      "Client trust and referral drive a large share of new business in most service categories.",
      "Talent quality and retention are the core product — client relationships often follow specific people, not just the firm's brand.",
      "Scope creep (unpaid extra work) is one of the most common silent profit destroyers in service businesses.",
      "Moving from project-based to retainer or productised offerings is a common path to more predictable revenue.",
    ],
    strategies: [
      { title: "Price on value delivered, not hours spent", body: "Two providers doing similar hours of work can reasonably charge very different prices if one demonstrably changes the client's business more — anchoring price to outcome, not time, captures that difference." },
      { title: "Productise repeatable engagements", body: "Turning a bespoke, one-off service into a defined, repeatable package (with clear scope and price) increases margin and reduces the sales cycle for engagements that don't need to be reinvented each time." },
      { title: "Build a referral and case-study engine deliberately", body: "Since B2B service quality is hard to evaluate upfront, specific, documented client outcomes are what actually convince prospective clients — collecting them should be a standard process, not an afterthought." },
      { title: "Defend against scope creep with clear contracts", body: "Unscoped 'just one more thing' requests are one of the largest silent margin destroyers in service businesses; clear scope boundaries and change-order processes protect profitability without damaging the relationship." },
      { title: "Move toward retainer revenue where the relationship supports it", body: "Project-based revenue is inherently lumpy; retainer or subscription-style ongoing engagements smooth cash flow and deepen the client relationship over time." },
      { title: "Invest in talent retention as a client-retention strategy", body: "Client relationships often attach to specific people on the team — losing key talent risks losing the client relationship along with them, making retention a genuine business continuity issue." },
    ],
    benchmarks: [
      { metric: "Utilisation rate (billable hours)", typical: "65–80% of available hours for a healthy service business" },
      { metric: "Client concentration", typical: "No single client should typically exceed 20–30% of revenue" },
      { metric: "Referral share of new business", typical: "30–50% for an established firm" },
      { metric: "Gross margin", typical: "40–60%", note: "After direct delivery cost, before overhead." },
    ],
    pitfalls: [
      "Letting scope creep erode margin on fixed-price or loosely scoped engagements.",
      "Depending on one or two large clients for the majority of revenue.",
      "Pricing purely on hours rather than the value the engagement actually delivers.",
      "Losing key talent and losing the attached client relationships along with them.",
      "Staying entirely project-based when parts of the business could support more predictable retainer revenue.",
    ],
    caseStudySlugs: ["consulting-value-based-pricing"],
    starterKit: [
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "framework", slug: "execution-scoreboard", label: "Execution scoreboard" },
      { kind: "framework", slug: "talent-engagement", label: "Engagement lift plan" },
      { kind: "journey", slug: "sales-have-stalled", label: "Sales have stalled journey" },
    ],
  },
  {
    slug: "saas-tech",
    name: "SaaS & tech products",
    tagline: "Won on activation, retention, and expansion — not just sign-ups",
    summary:
      "Software and tech product businesses run on recurring revenue economics, where the real story isn't how many people sign up but how many stay, expand their usage, and never think about switching away.",
    structure: [
      "Revenue compounds through retention and expansion, not just new customer acquisition — churn quietly undoes new growth.",
      "The gap between activation (a new user reaching real value) and eventual churn decides most of the business's long-term trajectory.",
      "Product usage data is both a retention early-warning system and a genuine product-improvement input, if actually acted on.",
      "Free or trial tiers function as the primary acquisition channel for many products, shifting the growth burden onto product design rather than sales alone.",
      "Technical debt and infrastructure decisions made early quietly shape how fast and how expensively the product can scale later.",
    ],
    strategies: [
      { title: "Optimise for activation before acquisition", body: "Acquiring more trial users into a product with a weak activation experience just means more people churning before ever feeling real value — fixing activation multiplies the value of every acquisition channel." },
      { title: "Treat churn as the most important number in the business", body: "Even strong new-customer growth can't outrun high churn forever; retention and expansion revenue from existing customers is usually cheaper and more durable than constantly replacing churned ones." },
      { title: "Use usage data to predict and prevent churn", body: "Declining usage patterns typically show up weeks before a customer formally cancels — proactive outreach based on usage signals catches churn while it's still preventable." },
      { title: "Design pricing tiers around genuine usage-based value", body: "Pricing tiers that map to real value milestones (more seats, more usage, more capability) let customers naturally expand spend as they get more value, rather than facing an artificial upgrade wall." },
      { title: "Invest in customer success as a growth function", body: "In subscription businesses, proactive customer success reliably shows higher renewal and expansion rates than reactive support — treating it as a growth investment rather than a cost centre pays back directly." },
      { title: "Protect technical foundations even under growth pressure", body: "Technical shortcuts taken to hit a growth deadline quietly compound into expensive rebuilds later — the businesses that scale smoothly usually paid down technical debt deliberately along the way." },
    ],
    benchmarks: [
      { metric: "Monthly/annual churn", typical: "Under 5% monthly for SMB-focused SaaS, under 1% monthly for enterprise" },
      { metric: "Net revenue retention", typical: "100%+ is healthy; 110–130% is considered excellent for a growing SaaS business" },
      { metric: "CAC payback period", typical: "12–18 months is a common healthy target" },
      { metric: "Free-to-paid conversion", typical: "2–5% for freemium products, higher for time-limited free trials" },
    ],
    pitfalls: [
      "Focusing acquisition spend on sign-ups while activation and onboarding remain weak.",
      "Treating churn as an inevitable cost of doing business rather than the most important number to fix.",
      "Ignoring usage data as an early-warning signal for at-risk accounts.",
      "Under-investing in customer success, treating it purely as a reactive support cost.",
      "Accumulating technical debt under growth pressure without ever deliberately paying it down.",
    ],
    caseStudySlugs: ["netflix-vs-blockbuster", "yahoo-missed-acquisitions"],
    starterKit: [
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "framework", slug: "nps-engine", label: "Recommendation score engine" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "wholesale-distribution",
    name: "Wholesale & distribution",
    tagline: "Margin lives in turnover speed and route efficiency, not markup",
    summary:
      "Wholesale and distribution businesses operate on thin per-unit margins across large volume, where the real profit driver is how fast inventory turns and how efficiently it's routed to retail customers, not the markup on any single item.",
    structure: [
      "Thin per-unit margins mean volume and turnover speed, not pricing power, drive most of the profit.",
      "Relationships with both suppliers (for terms and priority) and retail customers (for reliable off-take) are the core asset of the business.",
      "Credit extended to retail customers ties up working capital and carries real default risk if not managed carefully.",
      "Route and delivery efficiency directly affects the cost of serving each customer, especially in fragmented, small-order markets.",
      "Modern organised wholesale formats increasingly compete with traditional relationship-based distribution on price transparency and convenience.",
    ],
    strategies: [
      { title: "Prioritise inventory turnover over markup", body: "In a thin-margin business, a product that turns twice as fast is worth more to the business than one with a slightly higher markup that sits longer — turnover, not price, is the lever worth optimising." },
      { title: "Manage customer credit as carefully as inventory", body: "Extending trade credit to retail customers is often necessary to win their business, but undisciplined credit terms tie up working capital and create default risk that erodes thin margins fast." },
      { title: "Build route density before adding new territories", body: "Serving more customers efficiently along existing routes is usually more profitable than spreading thinner across new, less dense territories." },
      { title: "Protect supplier relationships and terms deliberately", body: "Favourable payment terms and priority allocation from suppliers function as a genuine competitive advantage in a category where most competitors sell nearly identical products." },
      { title: "Modernise against organised competition proactively", body: "Modern, organised wholesale formats increasingly compete on price transparency and convenience — traditional distributors who adapt selectively (without losing relationship strengths) defend share better than those who ignore the shift entirely." },
      { title: "Bundle slow-moving stock with fast movers for retail partners", body: "Just as with direct-to-consumer retail, bundling slower-moving inventory with proven sellers helps move stock through the channel without resorting to margin-destroying discounts." },
    ],
    benchmarks: [
      { metric: "Gross margin", typical: "8–20%", note: "Among the thinnest of any category — profit depends on volume and turnover." },
      { metric: "Inventory turnover", typical: "10–20× per year for a healthy distribution business" },
      { metric: "Days sales outstanding (customer credit)", typical: "30–60 days, tightly managed" },
      { metric: "Order fulfilment accuracy", typical: "98%+ for a trusted distributor" },
    ],
    pitfalls: [
      "Extending customer credit without disciplined limits, tying up working capital and risking defaults.",
      "Spreading into new territories before route density is fully built out in existing ones.",
      "Competing purely on price without protecting supplier relationships and terms.",
      "Ignoring organised, modern wholesale competitors until share has already been lost.",
      "Treating turnover speed as secondary to markup, when in this category it's usually the bigger lever.",
    ],
    caseStudySlugs: ["metro-cash-and-carry-wholesale"],
    starterKit: [
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "working-capital-allocator", label: "Working capital allocator" },
      { kind: "framework", slug: "borrowing-readiness", label: "Borrowing readiness check" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
];
