import type { Industry } from "./knowledgeTypes";

export const INDUSTRIES_2: Industry[] = [
  {
    slug: "agriculture-agribusiness",
    name: "Agriculture & agribusiness",
    tagline: "Won at the farm gate, in storage, and in the last mile to market",
    summary:
      "Agribusiness sits between biology and logistics — yield, storage loss, and the price a farmer or aggregator gets at each handoff decide profitability far more than any single input decision.",
    structure: [
      "Post-harvest loss between farm and final buyer often destroys more value than any single production decision.",
      "Price discovery has historically favoured whoever controls the mandi or middleman layer, not the producer.",
      "Working capital cycles are tied to crop seasons, not calendar months, creating long, uneven cash gaps.",
      "Quality grading and storage infrastructure decide how much of the harvest actually reaches market at full value.",
      "Direct digital procurement is increasingly bypassing traditional middleman layers, changing who captures the margin.",
    ],
    strategies: [
      { title: "Cut post-harvest loss before chasing higher yield", body: "Improving storage, grading, and transport to reduce spoilage often recovers more value per season than incremental yield improvements, at a fraction of the investment." },
      { title: "Build direct procurement relationships", body: "Connecting closer to the actual grower — through aggregation points, digital procurement, or contracted supply — captures margin that traditionally went to layers of intermediaries." },
      { title: "Invest in grading and quality standardisation", body: "Buyers pay a real premium for consistently graded produce; inconsistent quality forces even good produce into commodity pricing." },
      { title: "Match financing to the crop cycle, not the calendar", body: "Working capital and loan structures that assume monthly regularity mismatch agriculture's seasonal cash reality — financing built around actual harvest timing reduces distress borrowing." },
      { title: "Diversify across crops or value-added processing", body: "Dependence on a single crop concentrates weather and price risk; moving into value-added processing (oils, packaged staples) captures more of the value chain than raw produce alone." },
      { title: "Use aggregation to gain negotiating power", body: "Individual small producers have little pricing power alone; formal or informal aggregation — cooperatives, farmer producer organisations — restores some negotiating leverage against large buyers." },
    ],
    benchmarks: [
      { metric: "Post-harvest loss", typical: "10–20% of produce value, category-dependent", note: "A major, addressable source of lost margin across the sector." },
      { metric: "Working capital cycle", typical: "3–8 months, aligned to crop season" },
      { metric: "Storage-to-market time", typical: "Shorter is better — perishables lose value daily" },
      { metric: "Price realisation vs. MSP/market benchmark", typical: "Tracked as a share of the benchmark price actually captured by the producer" },
    ],
    pitfalls: [
      "Focusing entirely on yield while ignoring post-harvest loss, which often destroys more value.",
      "Financing structured around calendar months rather than actual crop cash cycles.",
      "Selling only raw, ungraded produce and missing the premium consistent grading commands.",
      "Remaining dependent on a single crop with no diversification against weather or price risk.",
      "Staying fragmented instead of aggregating for negotiating power against large buyers.",
    ],
    caseStudySlugs: ["itc-echoupal-agri-supply-chain"],
    starterKit: [
      { kind: "framework", slug: "working-capital-allocator", label: "Working capital allocator" },
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "non-customer-expansion", label: "Non-customer expansion" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
  {
    slug: "it-ites-services",
    name: "IT & ITES services",
    tagline: "A talent business wearing a technology company's clothes",
    summary:
      "IT services and business process outsourcing sell skilled hours and delivered outcomes at scale — the actual product is talent quality, process discipline, and client trust, delivered through technology, not the technology itself.",
    structure: [
      "Utilisation (billable hours as a share of total available hours) is the primary profitability lever.",
      "Client concentration risk is high — losing one large account can meaningfully affect revenue.",
      "Talent attrition directly threatens both delivery quality and client relationships built around specific people.",
      "Fixed-price and time-and-material contracts carry very different risk profiles for the delivering business.",
      "Moving up the value chain from staffing to consulting and platforms changes margin structure substantially.",
    ],
    strategies: [
      { title: "Protect utilisation without burning out delivery teams", body: "Utilisation drives margin, but pushing it too aggressively increases attrition and quality risk — the discipline is finding the sustainable ceiling, not the theoretical maximum." },
      { title: "Diversify beyond a small number of large clients", body: "Heavy dependence on one or two large accounts is a structural risk that shows up suddenly when a client cuts budget or takes work in-house." },
      { title: "Invest deliberately in talent retention", body: "Client trust and delivery quality are often tied to specific people; losing key talent risks losing the account relationship built around them, not just a seat to fill." },
      { title: "Move up the value chain deliberately", body: "Pure staffing and time-and-material work is margin-thin and easily commoditised; building genuine consulting, IP, or platform capability protects margin as the market matures." },
      { title: "Price fixed-scope work carefully", body: "Fixed-price contracts shift delivery risk onto the provider — underestimating scope or complexity turns a profitable-looking deal into a loss once overruns hit." },
      { title: "Build governance and quality processes that scale beyond any one team", body: "Delivery quality that depends entirely on individual project managers doesn't scale reliably across dozens of simultaneous engagements — standardised process protects consistency." },
    ],
    benchmarks: [
      { metric: "Utilisation rate", typical: "70–85% for a healthy services business" },
      { metric: "Attrition rate", typical: "Industry-watched closely; elevated attrition signals delivery and client risk" },
      { metric: "Client concentration", typical: "No single client should typically exceed 15–25% of revenue" },
      { metric: "Gross margin", typical: "25–40%", note: "Varies by whether work is staffing-led or higher-value consulting/platform work." },
    ],
    pitfalls: [
      "Pushing utilisation so hard that attrition and quality suffer.",
      "Letting one or two large clients dominate revenue without a diversification plan.",
      "Underpricing fixed-scope contracts without adequately buffering for scope creep.",
      "Losing key talent and the client relationships built around them without a succession plan.",
      "Staying purely staffing-led without building any differentiated IP, consulting depth, or platform capability.",
    ],
    caseStudySlugs: ["infosys-global-delivery-model", "satyam-fraud-collapse"],
    starterKit: [
      { kind: "framework", slug: "talent-engagement", label: "Engagement lift plan" },
      { kind: "tool", slug: "hiring-pipeline", label: "Hiring pipeline tracker" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "framework", slug: "core-values", label: "Core value charter" },
      { kind: "journey", slug: "cant-find-good-people", label: "Can't find or keep good people journey" },
    ],
  },
  {
    slug: "pharma",
    name: "Pharma & healthcare products",
    tagline: "Regulation is the moat, and trust is the entire brand",
    summary:
      "Pharmaceutical and healthcare product businesses operate inside strict regulatory frameworks where compliance itself becomes a competitive barrier, and where a single quality failure can end the business overnight.",
    structure: [
      "Regulatory approval processes are slow and expensive, which protects incumbents but also delays new entrants and new products alike.",
      "Manufacturing quality compliance is non-negotiable — a single failed audit can halt production entirely.",
      "Distribution runs through a specialised chain (stockists, chemists, hospitals) with its own credit and relationship dynamics.",
      "Research and development investment is front-loaded and risky, with most candidate products never reaching market.",
      "Pricing is often constrained by regulation, insurance systems, or public health considerations, unlike most other categories.",
    ],
    strategies: [
      { title: "Treat regulatory compliance as core capability, not overhead", body: "Regulatory and manufacturing quality compliance is slow and expensive to build properly, which is exactly what makes it a durable moat once achieved — treating it as a cost centre to minimise is a strategic mistake." },
      { title: "Build a diversified product pipeline", body: "Because individual drug or product development carries high failure risk, a pipeline with multiple candidates at different stages protects the business from any single failure." },
      { title: "Invest in distribution and stockist relationships deliberately", body: "The pharma distribution chain runs on trust and credit relationships built over years — new entrants without these relationships struggle regardless of product quality." },
      { title: "Consider affordability as a market-expansion strategy, not just a compliance requirement", body: "Making a needed medicine genuinely affordable can open access to a vastly larger market than premium pricing alone would reach, particularly in price-sensitive geographies." },
      { title: "Protect manufacturing quality obsessively", body: "A single quality or compliance failure can trigger a full facility shutdown or product recall — the cost of prevention is always lower than the cost of a failure." },
      { title: "Balance R&D investment against near-term commercial products", body: "Pure research-stage businesses face long, uncertain paths to revenue; balancing a commercial product line against R&D investment protects cash flow while pursuing longer-term pipeline value." },
    ],
    benchmarks: [
      { metric: "R&D spend", typical: "8–15% of revenue for research-oriented pharma companies" },
      { metric: "Gross margin", typical: "60–80% for branded/patented products; much thinner for generics" },
      { metric: "Regulatory approval timeline", typical: "Multi-year process, varies substantially by product category and geography" },
      { metric: "Working capital cycle", typical: "60–120 days, driven by distribution chain credit terms" },
    ],
    pitfalls: [
      "Treating regulatory and quality compliance as a checkbox rather than a genuine capability to invest in.",
      "Depending on a single product with no pipeline diversification against development failure.",
      "Underinvesting in distribution and stockist relationships that take years to build.",
      "Missing a quality compliance issue that triggers a costly facility shutdown or recall.",
      "Pursuing only premium pricing in categories where affordability could unlock a much larger market.",
    ],
    caseStudySlugs: ["cipla-affordable-medicine-access"],
    starterKit: [
      { kind: "tool", slug: "moat-builder", label: "Moat builder" },
      { kind: "framework", slug: "critical-success-factors", label: "Critical success factors" },
      { kind: "framework", slug: "core-values", label: "Core value charter" },
      { kind: "journey", slug: "competitor-could-copy-me", label: "Competitor could copy me tomorrow journey" },
    ],
  },
  {
    slug: "construction-infrastructure",
    name: "Construction & infrastructure",
    tagline: "Long projects, thin margins, and a payment cycle that can sink you",
    summary:
      "Construction and infrastructure businesses execute large, long-duration projects where cash flow timing, contractor management, and cost overruns decide profitability far more than the headline contract value does.",
    structure: [
      "Projects run for months or years, with cash outflows front-loaded well before major payment milestones arrive.",
      "Subcontractor and labour management quality directly determines both timeline and cost overrun risk.",
      "Material cost volatility (steel, cement) can swing project economics after a fixed-price contract is already signed.",
      "Payment delays from clients — especially government or large corporate clients — are a chronic industry cash flow risk.",
      "Safety and regulatory compliance failures carry both direct costs and reputational risk that can affect future bidding.",
    ],
    strategies: [
      { title: "Match financing to project payment milestones", body: "Since cash outflows are front-loaded and payments arrive at milestones, financing structured around the project's actual payment schedule prevents the mid-project cash crunches that sink otherwise profitable projects." },
      { title: "Build in material cost contingency", body: "Fixed-price contracts signed without contingency for material price volatility can turn a profitable bid into a loss if steel, cement, or other key inputs move significantly before project completion." },
      { title: "Invest in subcontractor and labour management systems", body: "Project timeline and cost overruns are most often driven by subcontractor coordination failures, not the primary contractor's own work — systematic subcontractor management is a genuine competitive advantage." },
      { title: "Diversify the client and project mix", body: "Heavy dependence on one client type (particularly government contracts with slower payment cycles) concentrates both payment-timing risk and bidding-cycle risk." },
      { title: "Protect the balance sheet from payment delay risk", body: "Because client payment delays are common and sometimes severe, maintaining a cash buffer independent of any single project's payment schedule protects the business from a client's slow payment becoming an existential crisis." },
      { title: "Treat safety and compliance as a bidding advantage", body: "A strong safety and compliance record increasingly factors into how clients — especially larger corporate and government clients — evaluate and award future contracts, making it a genuine commercial asset, not just a cost." },
    ],
    benchmarks: [
      { metric: "Gross margin", typical: "10–20%", note: "Among the thinner margins across industries, sensitive to cost overruns." },
      { metric: "Working capital cycle", typical: "90–180 days, driven by milestone payment structures" },
      { metric: "Project cost overrun rate", typical: "Tracked as a key operational KPI; lower is a genuine competitive advantage" },
      { metric: "Receivables from government/large clients", typical: "Often the slowest-paying segment; worth tracking separately from private clients" },
    ],
    pitfalls: [
      "Signing fixed-price contracts with no material cost contingency built in.",
      "Financing projects with short-term debt that doesn't match the actual milestone payment timeline.",
      "Under-investing in subcontractor coordination, the most common source of timeline and cost overruns.",
      "Depending heavily on slow-paying government contracts without a cash buffer to absorb the delay.",
      "Treating safety and compliance as a cost to minimise rather than a genuine factor in winning future bids.",
    ],
    caseStudySlugs: ["lt-engineering-diversification"],
    starterKit: [
      { kind: "framework", slug: "cash-projection", label: "90-day cash projection" },
      { kind: "tool", slug: "cash-flow-simulator", label: "Cash flow simulator" },
      { kind: "framework", slug: "borrowing-readiness", label: "Borrowing readiness check" },
      { kind: "framework", slug: "sop-builder", label: "SOP builder" },
      { kind: "journey", slug: "cash-is-always-tight", label: "Cash is always tight journey" },
    ],
  },
  {
    slug: "media-entertainment",
    name: "Media & entertainment",
    tagline: "Attention is the product, and it's harder to hold than to win",
    summary:
      "Media and entertainment businesses compete for a genuinely scarce resource — audience attention — where content quality, distribution reach, and monetisation model together decide whether attention converts into a sustainable business.",
    structure: [
      "Content cost is largely fixed regardless of audience size, so distribution reach directly drives unit economics.",
      "Multiple monetisation models coexist — subscription, advertising, and licensing — often blended within one business.",
      "Piracy and easy content substitution constantly pressure both pricing power and exclusivity value.",
      "Talent (creators, performers) relationships and retention shape long-term content pipeline reliability.",
      "Real-time or live content (sports, events) commands premium engagement and pricing power that on-demand content generally can't match.",
    ],
    strategies: [
      { title: "Build exclusive or live content as a retention anchor", body: "On-demand content alone faces constant substitution risk; exclusive or live content (sports, major events) gives audiences a specific reason to stay that competitors can't easily replicate." },
      { title: "Blend monetisation models deliberately", body: "Relying on a single revenue model (pure subscription or pure advertising) leaves a business exposed to that model's specific weaknesses — blending subscription, advertising, and licensing spreads and stabilises revenue." },
      { title: "Invest in talent relationships as a supply chain asset", body: "Creator and performer relationships are effectively the content supply chain; losing key talent to a competitor can be as damaging as losing a manufacturing supplier in another industry." },
      { title: "Use data to inform content investment, not just gut instinct", body: "Audience engagement and completion data increasingly predict content success better than intuition alone — platforms that systematically use this data outcompete those relying purely on creative judgment." },
      { title: "Protect content value against piracy pragmatically", body: "Pure enforcement rarely eliminates piracy; making legitimate access more convenient and reasonably priced than pirated alternatives is often a more effective long-term defence." },
      { title: "Localise content deliberately for regional audiences", body: "A single national or global content strategy underperforms compared to deliberate regional and language-specific content investment in linguistically diverse markets like India." },
    ],
    benchmarks: [
      { metric: "Content cost as % of revenue", typical: "Varies hugely by model; a key ratio to track over time" },
      { metric: "Subscriber churn", typical: "5–10% monthly is common for entertainment subscriptions without live/exclusive content anchors" },
      { metric: "Average revenue per user (ARPU)", typical: "Tracked alongside subscriber growth, not in isolation" },
      { metric: "Content completion/engagement rate", typical: "A leading indicator of content investment quality" },
    ],
    pitfalls: [
      "Relying on a single monetisation model without blending subscription, advertising, or licensing.",
      "Underinvesting in exclusive or live content, leaving the catalogue exposed to easy substitution.",
      "Losing key creative talent to competitors without a retention strategy.",
      "Applying a single national content strategy in a linguistically and culturally diverse market.",
      "Fighting piracy purely through enforcement instead of making legitimate access more convenient.",
    ],
    caseStudySlugs: ["hotstar-ipl-streaming-scale"],
    starterKit: [
      { kind: "framework", slug: "content-engine", label: "Content engine setup" },
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "framework", slug: "consumer-shift", label: "Consumer behaviour shift" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "beauty-wellness",
    name: "Beauty & wellness",
    tagline: "Trust, ritual, and personalisation sell more than the formula itself",
    summary:
      "Beauty and wellness businesses sell an emotional outcome — confidence, calm, transformation — where trust, personalisation, and ritual matter as much as the underlying product formulation.",
    structure: [
      "Customer trust and word of mouth carry outsized weight, since results are personal and hard to verify before purchase.",
      "Subscription and repeat-purchase mechanics work unusually well because many products are consumed on a predictable cycle.",
      "Influencer and community-driven marketing often outperforms traditional advertising in this category specifically.",
      "Regulatory and safety compliance (especially for skincare and ingestible wellness products) is a genuine trust signal, not just a legal requirement.",
      "Personalisation — matching product to individual skin type, concern, or goal — increasingly differentiates winners from commodity players.",
    ],
    strategies: [
      { title: "Build trust through visible proof, not just claims", body: "Before/after documentation, ingredient transparency, and genuine customer reviews do more to build trust in this category than confident marketing claims alone." },
      { title: "Design for the repeat-purchase cycle", body: "Many beauty and wellness products are consumed on a predictable schedule — subscription mechanics and replenishment reminders capture recurring revenue that one-time-purchase marketing leaves on the table." },
      { title: "Invest in micro and mid-tier influencer relationships", body: "Smaller, niche-focused influencers often convert better in this category than broad celebrity reach, because their endorsement functions as a trusted peer recommendation." },
      { title: "Treat regulatory compliance as a marketable trust signal", body: "Visible certification and safety compliance — especially for skincare and ingestible products — can be actively marketed as a differentiator, not just quietly satisfied in the background." },
      { title: "Personalise where the category allows it", body: "Quizzes, consultations, or diagnostic tools that match a specific product to an individual's needs increase both conversion and perceived value compared to one-size-fits-all positioning." },
      { title: "Build community around shared rituals or goals", body: "Beauty and wellness purchases are often part of a broader identity or self-care ritual — brands that build community around that broader goal retain customers longer than those selling purely transactional products." },
    ],
    benchmarks: [
      { metric: "Gross margin", typical: "50–70%", note: "Among the healthier margins in consumer categories, before marketing spend." },
      { metric: "Repeat purchase rate", typical: "30–50% within 6 months for a well-loved product" },
      { metric: "CAC-to-LTV ratio", typical: "At least 1:3, similar to other D2C categories" },
      { metric: "Return/complaint rate", typical: "Should stay low — trust damage in this category spreads fast through reviews" },
    ],
    pitfalls: [
      "Making claims without visible, credible proof to back them up.",
      "Ignoring the repeat-purchase cycle and marketing only for one-time acquisition.",
      "Chasing broad celebrity reach over more trusted, niche micro-influencer relationships.",
      "Treating regulatory and safety compliance as invisible background work instead of a marketable trust signal.",
      "Offering one-size-fits-all products in a category where personalisation increasingly wins.",
    ],
    caseStudySlugs: ["nykaa-beauty-marketplace"],
    starterKit: [
      { kind: "framework", slug: "brand-signals", label: "Brand signal alignment" },
      { kind: "tool", slug: "customer-lifetime", label: "Customer lifetime value" },
      { kind: "framework", slug: "nps-engine", label: "Recommendation score engine" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "jewellery",
    name: "Jewellery",
    tagline: "The most trust-scarce, highest-ticket category in retail",
    summary:
      "Jewellery retail sells a high-ticket, infrequent, emotionally significant purchase in a category historically plagued by purity and pricing distrust — trust infrastructure often matters as much as design.",
    structure: [
      "Purchases are high-ticket and infrequent, making each customer relationship unusually valuable to protect.",
      "Purity certification and transparent pricing are trust differentiators in a category with a long history of disputes.",
      "Gold and precious metal price volatility directly affects both input cost and customer purchase timing.",
      "Design and craftsmanship differentiate at the premium end, while making charges and purity trust dominate at the mass end.",
      "Occasion-driven buying (weddings, festivals) creates concentrated demand spikes rather than steady year-round purchasing.",
    ],
    strategies: [
      { title: "Make trust infrastructure the core brand promise", body: "Certified purity hallmarking, transparent making charges, and clear buy-back or exchange policies address the category's oldest and deepest customer fear more directly than any design innovation." },
      { title: "Manage gold price volatility deliberately", body: "Hedging strategies and flexible making-charge structures protect margin against gold price swings that would otherwise squeeze profitability unpredictably." },
      { title: "Design collections around occasions, not just aesthetics", body: "Wedding and festival-specific collections align with when customers are actually ready to make a purchase decision, rather than relying on generic year-round design refreshes." },
      { title: "Invest in staff training for a high-trust, high-ticket sale", body: "A jewellery purchase decision often depends heavily on how much the customer trusts the salesperson in the moment — well-trained, non-pushy staff convert better than aggressive sales tactics in this category." },
      { title: "Offer flexible payment and exchange schemes", body: "Gold savings schemes, installment plans, and generous exchange policies lower the psychological barrier to a high-ticket purchase and build long-term customer relationships beyond a single transaction." },
      { title: "Differentiate mass and premium tiers deliberately", body: "The mass segment competes primarily on trust and making charges, while the premium segment competes on design and craftsmanship — trying to serve both with one undifferentiated proposition weakens both." },
    ],
    benchmarks: [
      { metric: "Making charges", typical: "8–25% of gold value, varies by design complexity and brand positioning" },
      { metric: "Inventory turnover", typical: "2–4× per year", note: "Slower than most retail due to high ticket size and considered purchase behaviour." },
      { metric: "Gross margin", typical: "10–20%", note: "Thin relative to ticket size due to gold's dominant share of cost." },
      { metric: "Repeat/exchange rate", typical: "A meaningful share of revenue often comes from old-for-new exchange transactions" },
    ],
    pitfalls: [
      "Underinvesting in purity certification and transparent pricing in a trust-scarce category.",
      "Failing to hedge against gold price volatility, letting margin swing unpredictably.",
      "Running generic year-round collections instead of occasion-timed design launches.",
      "Using aggressive sales tactics in a category where trust in the salesperson drives conversion.",
      "Trying to serve mass and premium customers with one undifferentiated proposition.",
    ],
    caseStudySlugs: ["titan-tanishq-trust"],
    starterKit: [
      { kind: "framework", slug: "brand-signals", label: "Brand signal alignment" },
      { kind: "tool", slug: "moat-builder", label: "Moat builder" },
      { kind: "framework", slug: "cx-touchpoints", label: "Experience touchpoint audit" },
      { kind: "journey", slug: "competitor-could-copy-me", label: "Competitor could copy me tomorrow journey" },
    ],
  },
  {
    slug: "electronics-retail",
    name: "Electronics retail",
    tagline: "Thin margins, fast depreciation, and a service tail that saves the business",
    summary:
      "Electronics retail sells rapidly depreciating, highly comparison-shopped products at thin margins, where after-sales service, financing, and extended warranties often matter more to profitability than the sale itself.",
    structure: [
      "Product prices depreciate quickly as new models launch, making inventory ageing a direct financial risk.",
      "Customers heavily comparison-shop online before purchasing, compressing retail margins on the core product.",
      "Extended warranties, financing, and accessories are frequently the more profitable part of the transaction.",
      "After-sales service quality drives repeat purchases and referrals in a category with genuine product failure risk.",
      "Omnichannel presence (online research, offline purchase, or the reverse) is now the default customer journey, not an edge case.",
    ],
    strategies: [
      { title: "Manage inventory ageing aggressively", body: "Electronics inventory loses value with every week a new model is closer to launch — disciplined ordering and fast clearance of ageing stock protects margin more than any single sales tactic." },
      { title: "Treat warranties and financing as core profit centres", body: "Extended warranties, financing, and accessory attachment often carry higher margins than the core electronics product itself — presenting them well at the point of sale is a genuine profit strategy, not an upsell afterthought." },
      { title: "Invest in after-sales service as a differentiator", body: "In a category where products do occasionally fail, fast and fair after-sales service becomes a genuine reason customers choose one retailer over an identical product at a competitor." },
      { title: "Build a real omnichannel experience", body: "Customers routinely research online and buy offline, or the reverse — retailers who make this journey seamless (price matching, in-store pickup, unified inventory visibility) convert better than those treating channels separately." },
      { title: "Use bundling to protect margin on commoditised products", body: "Bundling a low-margin, heavily comparison-shopped product with accessories or services increases the effective margin on the overall transaction without directly raising the comparison-shopped price." },
      { title: "Train staff to be genuinely helpful, not just persuasive", body: "In a category where customers often know more about specifications than the salesperson, genuinely knowledgeable, non-pushy staff build the kind of trust that drives repeat business and referrals." },
    ],
    benchmarks: [
      { metric: "Gross margin on core product", typical: "5–15%", note: "Thin due to heavy price comparison; warranties and financing carry higher margins." },
      { metric: "Inventory turnover", typical: "6–10× per year" },
      { metric: "Extended warranty/financing attach rate", typical: "30–50% for a well-run electronics retailer" },
      { metric: "Service turnaround time", typical: "A key driver of repeat purchase and referral" },
    ],
    pitfalls: [
      "Letting inventory age past the point where it can be sold at healthy margin.",
      "Treating warranties and financing as a minor upsell rather than a core profit strategy.",
      "Underinvesting in after-sales service in a category with real product failure rates.",
      "Running separate, disconnected online and offline experiences instead of a unified omnichannel journey.",
      "Relying purely on persuasive selling in a category where customers often research more than staff know.",
    ],
    caseStudySlugs: ["reliance-digital-electronics-retail"],
    starterKit: [
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "service-ladder", label: "Service maturity ladder" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "journey", slug: "customers-dont-come-back", label: "Customers don't come back journey" },
    ],
  },
  {
    slug: "dairy-livestock",
    name: "Dairy & livestock",
    tagline: "A cold chain business disguised as a farming business",
    summary:
      "Dairy and livestock businesses live or die on the cold chain — how fast and reliably milk and animal products move from source to processing without spoiling — layered on top of the underlying farming economics.",
    structure: [
      "Milk and animal products are highly perishable, making cold chain reliability a direct revenue determinant.",
      "Procurement relationships with individual farmers or herders decide both supply consistency and quality.",
      "Value-added processing (from raw milk to packaged dairy products) captures significantly more margin than raw product sales.",
      "Seasonal supply fluctuation (flush vs lean season) creates recurring procurement and pricing planning challenges.",
      "Animal health and feed quality directly determine both yield and product quality, making veterinary support a real operational lever.",
    ],
    strategies: [
      { title: "Invest in cold chain reliability as the core moat", body: "A reliable, unbroken cold chain from collection to processing is often harder for competitors to replicate quickly than any product formulation, making it a genuine durable advantage." },
      { title: "Build direct procurement relationships with farmers", body: "Consistent, trust-based procurement relationships with individual dairy farmers or herders protect supply reliability and quality far better than opportunistic, price-only sourcing." },
      { title: "Move up the value chain into processed products", body: "Raw milk sales carry thin margins; processed and packaged dairy products (cheese, yoghurt, ghee, packaged milk) capture substantially more value from the same underlying raw material." },
      { title: "Plan procurement and pricing around seasonal supply swings", body: "Flush-season oversupply and lean-season shortage are predictable annual patterns — planning storage, processing capacity, and pricing around them prevents both waste and shortage-driven cost spikes." },
      { title: "Support farmer-level animal health and feed quality", body: "Providing veterinary support, feed guidance, or breeding support to supplying farmers directly improves the yield and quality of the raw product a dairy business depends on." },
      { title: "Build brand trust around freshness and purity", body: "In a category where adulteration concerns are common, transparent sourcing and visible quality assurance become genuine differentiators, not just compliance requirements." },
    ],
    benchmarks: [
      { metric: "Cold chain loss/spoilage", typical: "Should stay in low single digits as a percentage of collected volume for a well-run operation" },
      { metric: "Value-added product share of revenue", typical: "Higher share generally indicates stronger margin capture versus raw milk sales alone" },
      { metric: "Farmer/herder retention", typical: "A leading indicator of supply chain stability" },
      { metric: "Seasonal price variance", typical: "Tracked between flush and lean season to plan procurement and storage" },
    ],
    pitfalls: [
      "Underinvesting in cold chain reliability, leading to spoilage losses that erode already-thin margins.",
      "Sourcing opportunistically on price alone instead of building consistent farmer relationships.",
      "Selling primarily raw milk instead of moving into higher-margin processed products.",
      "Failing to plan for predictable seasonal supply swings, causing both waste and shortage.",
      "Neglecting farmer-level animal health support, which directly affects the quality of supply received.",
    ],
    caseStudySlugs: ["hatsun-agro-dairy-expansion"],
    starterKit: [
      { kind: "framework", slug: "sop-builder", label: "SOP builder" },
      { kind: "tool", slug: "inventory-turns", label: "Inventory turns analyzer" },
      { kind: "framework", slug: "portfolio-audit", label: "Product portfolio audit" },
      { kind: "journey", slug: "want-to-grow-safely", label: "Ready to grow, afraid to break it journey" },
    ],
  },
  {
    slug: "handicrafts-exports",
    name: "Handicrafts & exports",
    tagline: "Authenticity is the product; scale is the challenge",
    summary:
      "Handicraft and artisanal export businesses sell authenticity and craftsmanship that resist standardisation — the core tension is preserving the qualities that make the product valuable while building the consistency and scale export markets demand.",
    structure: [
      "Artisan-dependent production means quality and output volume are harder to standardise than factory manufacturing.",
      "Export compliance (documentation, quality standards, international logistics) adds real complexity beyond domestic selling.",
      "Storytelling and provenance — who made this, and how — are central to the value proposition, not decorative extras.",
      "Fair, reliable payment to artisans affects both ethical sourcing credentials and long-term supply consistency.",
      "Currency fluctuation and international shipping costs directly affect margin on export sales in ways domestic sales don't face.",
    ],
    strategies: [
      { title: "Standardise quality without industrialising the craft", body: "The challenge specific to this category is building consistent quality control processes that catch defects without forcing artisans into a rigid, factory-style process that would strip out the handmade character buyers value." },
      { title: "Invest in provenance and storytelling as core marketing", body: "Buyers of handicrafts are often paying partly for the story of who made the piece and how — documenting and communicating that story is core marketing, not an afterthought." },
      { title: "Build fair, reliable artisan payment systems", body: "Consistent, fair payment builds a stable, motivated artisan base and increasingly matters to buyers as an ethical sourcing credential in export markets." },
      { title: "Learn export compliance deliberately, market by market", body: "Documentation, quality certification, and import requirements vary by destination market — building this knowledge (or the right partnerships) prevents costly shipment rejections and delays." },
      { title: "Diversify across export markets and currencies", body: "Dependence on a single export market concentrates both currency risk and demand risk; spreading across multiple markets protects against a downturn or policy shift in any one." },
      { title: "Develop products for both mass and premium export tiers", body: "A range spanning accessible, smaller-ticket items alongside premium, collector-oriented pieces captures a wider buyer base than a single price tier alone." },
    ],
    benchmarks: [
      { metric: "Artisan payment reliability", typical: "A leading indicator of supply chain stability, worth tracking as carefully as any financial metric" },
      { metric: "Export rejection/return rate", typical: "Should stay low; each rejection carries significant cost given international logistics" },
      { metric: "Gross margin", typical: "30–50%", note: "Varies widely by category and how much of the value chain is controlled directly." },
      { metric: "Market concentration", typical: "Diversification across multiple export destinations reduces currency and policy risk" },
    ],
    pitfalls: [
      "Industrialising production so aggressively that it strips out the handmade quality buyers are paying for.",
      "Treating artisan storytelling as decorative marketing rather than core to the value proposition.",
      "Underpaying or paying artisans unreliably, undermining both ethics and long-term supply stability.",
      "Learning export compliance requirements the hard way, through costly shipment rejections.",
      "Depending on a single export market, concentrating currency and policy risk.",
    ],
    caseStudySlugs: ["fabindia-handicraft-exports"],
    starterKit: [
      { kind: "framework", slug: "brand-signals", label: "Brand signal alignment" },
      { kind: "framework", slug: "portfolio-audit", label: "Product portfolio audit" },
      { kind: "tool", slug: "pricing-strategy", label: "Pricing strategy picker" },
      { kind: "journey", slug: "want-to-grow-safely", label: "Ready to grow, afraid to break it journey" },
    ],
  },
];
