import type { Journey } from "./journeys";

export const JOURNEYS_2: Journey[] = [
  // ================= SALES & REVENUE =================
  {
    slug: "leads-but-no-conversions",
    category: "Sales & revenue",
    symptom: "“I get plenty of inquiries, but very few become paying customers.”",
    title: "Leads come, conversions don't",
    description: "The leak is somewhere between interest and payment. Find the exact stage where leads die, then fix that stage — not everything at once.",
    steps: [
      { kind: "framework", slug: "five-as-funnel-audit", title: "5 As funnel audit", why: "Locate the exact stage — appeal, ask, or act — where people drop off." },
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Check whether the leads were ever qualified to buy in the first place." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Unclear positioning makes interested people hesitate at the decision moment." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Rule out that the price structure itself is what's blocking the yes." },
    ],
  },
  {
    slug: "sales-depend-on-discounts",
    category: "Sales & revenue",
    symptom: "“Nothing sells unless I announce a discount.”",
    title: "Sales only happen on discount",
    description: "Constant discounting means customers buy the price, not the product. Rebuild the reason to buy at full price.",
    steps: [
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Diagnose whether your base pricing model created the discount addiction." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Give customers a reason to choose you that isn't the lowest number." },
      { kind: "framework", slug: "brand-signals", title: "Brand signal alignment", why: "Check whether your own signals are telling customers to wait for the sale." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Build loyalty mechanics that reward repeat behaviour instead of bargain hunting." },
    ],
  },
  {
    slug: "one-big-client-dependency",
    category: "Sales & revenue",
    symptom: "“One client is most of my revenue — if they leave, I'm finished.”",
    title: "One big client is my whole business",
    description: "Concentration feels like success until it's leverage against you. Protect the relationship while deliberately building the next five.",
    steps: [
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Deepen the big relationship first — understand their business so well you become hard to replace." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Make leaving you costly for them while you diversify." },
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Pick the specific next segment to win instead of chasing anyone with a budget." },
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Qualify new prospects properly so diversification doesn't mean bad-fit clients." },
    ],
  },
  {
    slug: "followups-keep-slipping",
    category: "Sales & revenue",
    symptom: "“We meet interested people, then nobody follows up and the deal dies.”",
    title: "Follow-ups keep slipping",
    description: "Most sales are lost to silence, not rejection. Build a follow-up system that doesn't depend on anyone's memory.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Write the follow-up sequence down — day 1, day 3, day 7 — so it happens without heroics." },
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Prioritise follow-ups by real potential instead of chasing everyone equally." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Make follow-ups a tracked daily number, not a good intention." },
      { kind: "tool", slug: "hiring-pipeline", title: "Hiring pipeline tracker", why: "Borrow the pipeline habit — a visible board of every open conversation and its stage." },
    ],
  },
  {
    slug: "long-sales-cycle",
    category: "Sales & revenue",
    symptom: "“Deals take months to close and half evaporate along the way.”",
    title: "The sales cycle is painfully long",
    description: "Long cycles usually mean the wrong person in the room or missing proof. Shorten the path by removing the actual blocker.",
    steps: [
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Reframe your pitch around their profit model so the value case makes itself." },
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Confirm you're talking to the actual decision maker with a real timeline." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Strengthen proof — references and reviews shorten deliberation more than pressure does." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Reduce the risk of saying yes — guarantees and pilots collapse long deliberations." },
    ],
  },
  {
    slug: "seasonal-sales-rollercoaster",
    category: "Sales & revenue",
    symptom: "“We feast in season and starve the rest of the year.”",
    title: "Sales are a seasonal rollercoaster",
    description: "Seasonality is predictable — which means it's plannable. Smooth the cash, then build off-season revenue deliberately.",
    steps: [
      { kind: "tool", slug: "cash-flow-simulator", title: "Cash flow simulator", why: "Map the year month by month so the lean months stop being surprises." },
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Find what could sell in the off-season that you're not offering yet." },
      { kind: "framework", slug: "non-customer-expansion", title: "Non-customer expansion", why: "Find the customer group whose season is opposite to yours." },
      { kind: "tool", slug: "content-calendar", title: "Content calendar", why: "Use the quiet months to build the demand that feeds the next peak." },
    ],
  },
  {
    slug: "team-cant-sell-like-me",
    category: "Sales & revenue",
    symptom: "“I close deals fine, but nobody else on the team can.”",
    title: "Only I can close deals",
    description: "Your selling skill is trapped in your head. Turn it into a process others can run — imperfectly at first, then well.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Document your actual sales conversation — openers, questions, objection answers." },
      { kind: "framework", slug: "training-evaluation", title: "Training that sticks", why: "Train the team on it with a real before/after measure, not a one-time lecture." },
      { kind: "framework", slug: "mcd-leadership-check", title: "MCD leadership check", why: "Coach them through deals before delegating deals — skipping that stage is why it failed before." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Track their inputs (calls, demos) weekly so improvement is visible and coachable." },
    ],
  },
  {
    slug: "wrong-customers-keep-coming",
    category: "Sales & revenue",
    symptom: "“We attract bargain hunters and difficult clients, not the customers we want.”",
    title: "We attract the wrong customers",
    description: "You get the customers your positioning and pricing invite. Change the signal, change who shows up.",
    steps: [
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Define precisely who the right customer is before filtering for them." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Reposition so the right customer feels 'this is for me' and the wrong one self-selects out." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Price is a filter — the wrong model attracts exactly the wrong crowd." },
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Add a qualification step so bad-fit inquiries stop consuming your week." },
    ],
  },

  // ================= MARKETING & VISIBILITY =================
  {
    slug: "nobody-knows-we-exist",
    category: "Marketing & visibility",
    symptom: "“Our product is good, but nobody has heard of us.”",
    title: "Nobody knows we exist",
    description: "Being good and being known are separate jobs. Build visibility deliberately, starting where your exact customer already looks.",
    steps: [
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Get famous in one narrow segment first — everywhere at once means nowhere." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Set up consistent content with an owner and KPIs, not bursts of motivation." },
      { kind: "framework", slug: "ad-campaign-blueprint", title: "Ad campaign blueprint", why: "Build one complete campaign with all seven parts before spending a rupee." },
      { kind: "tool", slug: "acquisition-cost", title: "Acquisition cost auditor", why: "Track what each channel costs from day one so you scale the right ones." },
    ],
  },
  {
    slug: "ads-money-no-results",
    category: "Marketing & visibility",
    symptom: "“We spend on ads but can't tell if they bring anything back.”",
    title: "Ad money in, nothing measurable out",
    description: "Ads without measurement is donation, not marketing. Instrument first, then fix the weakest part of the ad itself.",
    steps: [
      { kind: "tool", slug: "acquisition-cost", title: "Acquisition cost auditor", why: "Get the true cost per customer for every channel — the number that decides everything." },
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "Know what a customer is worth so you know what an ad is allowed to cost." },
      { kind: "framework", slug: "ad-campaign-blueprint", title: "Ad campaign blueprint", why: "Rebuild the ad with all seven parts — most failing ads are missing three of them." },
      { kind: "framework", slug: "five-as-funnel-audit", title: "5 As funnel audit", why: "Check whether ads create awareness that then dies at a later broken stage." },
    ],
  },
  {
    slug: "content-gets-no-engagement",
    category: "Marketing & visibility",
    symptom: "“We post regularly but it feels like shouting into the void.”",
    title: "Content gets no engagement",
    description: "Volume without a hook or a purpose is noise. Give every piece a job, an audience, and a reason to stop scrolling.",
    steps: [
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Rebuild the system — pillars, owner, KPIs — instead of posting harder." },
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Sharpen exactly who the content is for — content for everyone lands with no one." },
      { kind: "framework", slug: "consumer-shift", title: "Consumer behaviour shift", why: "Check whether your audience's attention moved platforms while your content didn't." },
      { kind: "tool", slug: "content-calendar", title: "Content calendar", why: "Run a 30-day consistent test with statuses tracked before judging any format." },
    ],
  },
  {
    slug: "no-time-for-marketing",
    category: "Marketing & visibility",
    symptom: "“I know marketing matters, but operations eat every hour I have.”",
    title: "No time for marketing",
    description: "Marketing that depends on your spare time will always lose. Make it a system with an owner — even if that owner is two protected hours a week.",
    steps: [
      { kind: "framework", slug: "main-thing-calendar", title: "Main-thing calendar", why: "Protect a fixed weekly block for marketing before the week fills up." },
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "Hand off the operational tasks that are eating the marketing hours." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Decide who owns content production — internal, hired, or outsourced." },
      { kind: "tool", slug: "content-calendar", title: "Content calendar", why: "Batch-plan a month in one sitting so daily invention isn't required." },
    ],
  },
  {
    slug: "brand-looks-cheap",
    category: "Marketing & visibility",
    symptom: "“Our work is premium but our brand looks like a budget option.”",
    title: "The brand looks cheaper than the work",
    description: "Customers price you by your signals before they experience your quality. Align every signal with the level you actually deliver.",
    steps: [
      { kind: "framework", slug: "brand-signals", title: "Brand signal alignment", why: "List the mixed signals — where packaging, pricing, or presence contradicts the quality." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Decide the exact perception you want before fixing fonts and photos." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Audit every touchpoint — one cheap-feeling moment undoes ten premium ones." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Check the price itself — underpricing is often the loudest cheap signal." },
    ],
  },
  {
    slug: "word-of-mouth-only",
    category: "Marketing & visibility",
    symptom: "“All our business comes from referrals — great until the month they stop.”",
    title: "We only grow by word of mouth",
    description: "Referrals prove you're good; depending on them alone caps your growth at luck. Systematise referrals and add one owned channel.",
    steps: [
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Find your promoters systematically instead of waiting for them to act." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Turn happy customers into visible proof — reviews and references that work while you sleep." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Build one channel you own, so discovery doesn't depend entirely on others talking." },
      { kind: "tool", slug: "acquisition-cost", title: "Acquisition cost auditor", why: "Measure the new channel against referrals honestly from the start." },
    ],
  },
  {
    slug: "social-followers-no-sales",
    category: "Marketing & visibility",
    symptom: "“Good follower count, decent likes — zero effect on revenue.”",
    title: "Followers don't become customers",
    description: "Audience and demand are different assets. Connect the attention you already have to an actual conversion path.",
    steps: [
      { kind: "framework", slug: "five-as-funnel-audit", title: "5 As funnel audit", why: "You have awareness and appeal — find where ask and act are breaking." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Rebalance content: mostly value, some proof, and a clear regular next step." },
      { kind: "framework", slug: "ad-campaign-blueprint", title: "Ad campaign blueprint", why: "Give the audience one specific, compelling offer instead of general presence." },
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "Work out what converting even 1% of followers would be worth — then invest accordingly." },
    ],
  },
  {
    slug: "marketing-message-unclear",
    category: "Marketing & visibility",
    symptom: "“People hear about us and still don't understand what we actually do.”",
    title: "Nobody understands what we do",
    description: "Confusion kills more sales than competition does. Get the message so sharp a stranger could repeat it after one hearing.",
    steps: [
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Write the one sentence: who you serve, what changes for them, why you." },
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Confused messaging usually means unresolved strategy underneath — resolve it first." },
      { kind: "framework", slug: "brand-signals", title: "Brand signal alignment", why: "Make every channel repeat the same clarified message instead of five variations." },
      { kind: "tool", slug: "competitor-matrix", title: "Competitor comparison matrix", why: "See what everyone else claims so your message occupies clear, empty ground." },
    ],
  },
  {
    slug: "new-launch-no-buzz",
    category: "Marketing & visibility",
    symptom: "“We launched something new and it landed with total silence.”",
    title: "The launch nobody noticed",
    description: "Launches fail in the weeks before launch day, not on it. Rebuild the launch as a campaign with anticipation, proof, and a deadline.",
    steps: [
      { kind: "framework", slug: "ad-campaign-blueprint", title: "Ad campaign blueprint", why: "Structure the relaunch as a full campaign, not a single announcement post." },
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Aim the relaunch at one specific segment that has a burning reason to care." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Line up early users and testimonials before going wide — proof pulls harder than promises." },
      { kind: "tool", slug: "content-calendar", title: "Content calendar", why: "Plan the two weeks before and after launch as a scheduled sequence." },
    ],
  },
  {
    slug: "competitor-louder-than-us",
    category: "Marketing & visibility",
    symptom: "“A competitor with a worse product gets all the attention.”",
    title: "A louder competitor is winning attention",
    description: "The market rewards the clearest, most repeated message — not the best product. Outposition them; don't try to outshout them.",
    steps: [
      { kind: "tool", slug: "competitor-matrix", title: "Competitor comparison matrix", why: "Map exactly where you beat them — that's your message, not a generic 'we're better'." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Claim the specific ground they can't claim, instead of fighting on their ground." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Proof beats volume — stack reviews and results they can't fake." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Consistency compounds — a steady voice outlasts a loud one." },
    ],
  },

  // ================= PRICING & PROFIT =================
  {
    slug: "profits-thin-despite-sales",
    category: "Pricing & profit",
    symptom: "“Revenue looks fine, but there's barely anything left at the end.”",
    title: "Good sales, thin profits",
    description: "Somewhere between revenue and profit, value is leaking. Find the leak with numbers before assuming you need more sales.",
    steps: [
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Get the three honest numbers: gross margin, net margin, return on capital." },
      { kind: "tool", slug: "break-even-calculator", title: "Break-even calculator", why: "Check whether your unit economics even allow a healthy profit at current volume." },
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Find which products quietly lose money while the winners subsidise them." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Fix the pricing model — thin margins are often a pricing decision, not a cost problem." },
    ],
  },
  {
    slug: "customers-say-too-expensive",
    category: "Pricing & profit",
    symptom: "“Every conversation ends with 'you're too expensive'.”",
    title: "Everyone says we're too expensive",
    description: "'Too expensive' usually means 'I don't see the value', not 'I don't have the money'. Fix the value story before touching the price.",
    steps: [
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Reframe your price against what you make or save them — in their numbers." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "If you're positioned as comparable to cheaper options, you'll be compared on price." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Proof reduces price resistance more than discounts do." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Consider structure changes — tiers and anchors — before considering cuts." },
    ],
  },
  {
    slug: "race-to-bottom-pricing",
    category: "Pricing & profit",
    symptom: "“Competitors keep undercutting and we keep matching them.”",
    title: "Stuck in a price war",
    description: "In a race to the bottom, the winner wins nothing. Step out of the comparison instead of winning it.",
    steps: [
      { kind: "tool", slug: "advantage-test", title: "Advantage stress test", why: "Find what you have that's genuinely hard to copy — that's your escape route." },
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Redefine the perfect customer — price wars are usually fought over the wrong ones." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Make your existing customers expensive to poach, whatever competitors charge." },
      { kind: "framework", slug: "non-customer-expansion", title: "Non-customer expansion", why: "Grow where the price war isn't happening — the people nobody's serving yet." },
    ],
  },
  {
    slug: "cant-raise-prices",
    category: "Pricing & profit",
    symptom: "“Costs went up but I'm scared to raise prices and lose customers.”",
    title: "Afraid to raise prices",
    description: "Silent margin erosion is a slower death than a managed price rise. Raise deliberately, with value and communication doing the work.",
    steps: [
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "See exactly how much margin the cost inflation has already quietly taken." },
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "Model the honest math: a small price rise usually beats losing a few price-only customers." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Strengthen the experience so the rise feels justified, not extractive." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Structure the increase — new tiers, grandfathering, added value — instead of a flat announcement." },
    ],
  },
  {
    slug: "discounting-eats-margin",
    category: "Pricing & profit",
    symptom: "“Between offers, coupons, and negotiations, nobody pays full price.”",
    title: "Discounts are eating the margin",
    description: "Every rupee of discount comes straight out of profit. Replace blanket discounting with structure that protects the floor.",
    steps: [
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Calculate what discounting actually costs you per year — the number is usually shocking." },
      { kind: "tool", slug: "break-even-calculator", title: "Break-even calculator", why: "Know your true floor so 'small' discounts stop dipping below it." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Move to bundles or tiers that give flexibility without naked price cuts." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Reward loyalty with benefits that cost you less than margin does." },
    ],
  },
  {
    slug: "dont-know-real-costs",
    category: "Pricing & profit",
    symptom: "“Honestly, I'm not sure what each product actually costs us.”",
    title: "Flying blind on real costs",
    description: "You can't price, discount, or drop anything intelligently until you know true per-unit cost. Get the numbers first; every decision after gets easier.",
    steps: [
      { kind: "tool", slug: "break-even-calculator", title: "Break-even calculator", why: "Separate fixed from variable costs for your main product — the foundation number." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Roll unit costs up into honest margins at the business level." },
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Judge every product against its real cost — some 'winners' will surprise you." },
      { kind: "tool", slug: "cash-flow-simulator", title: "Cash flow simulator", why: "Project forward with real numbers instead of hopeful ones." },
    ],
  },
  {
    slug: "revenue-up-profit-flat",
    category: "Pricing & profit",
    symptom: "“We're selling more than ever but profit hasn't moved in two years.”",
    title: "Growing revenue, flat profit",
    description: "Growth that doesn't reach the bottom line is expensive motion. Find where scale is leaking before adding more of it.",
    steps: [
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Compare margins now vs two years ago — see exactly which ratio degraded." },
      { kind: "framework", slug: "critical-success-factors", title: "Critical success factors", why: "Pick the two numbers that actually convert growth into profit, and manage those." },
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Growth often comes from low-margin lines — check what you're scaling." },
      { kind: "tool", slug: "break-even-calculator", title: "Break-even calculator", why: "Check if fixed costs grew with revenue and silently raised your floor." },
    ],
  },
  {
    slug: "undercharging-for-value",
    category: "Pricing & profit",
    symptom: "“Clients keep telling me I charge too little — and I still can't raise it.”",
    title: "I know I'm undercharging",
    description: "Underpricing isn't humility, it's a positioning and confidence problem with a compounding cost. Fix the story you tell yourself, then the price.",
    steps: [
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Put a rupee figure on the value you create — the number that justifies the new price." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Stack the proof that supports premium pricing before announcing it." },
      { kind: "framework", slug: "mighty-why", title: "The mighty why", why: "Underpricing is often self-worth wearing a price tag — address the root." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Pick the model that captures value — often value-based, not hourly or cost-plus." },
    ],
  },

  // ================= MONEY & CASH FLOW =================
  {
    slug: "clients-pay-late",
    category: "Money & cash flow",
    symptom: "“Everyone pays 60 days late and I'm financing their business for free.”",
    title: "Clients always pay late",
    description: "Late payment is a system you've accidentally trained. Retrain it with terms, follow-up rhythm, and consequences.",
    steps: [
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Quantify what late payment actually does to your next three months." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Build the collections process — invoice day, reminder days, escalation day — as a system." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Reward early payers with genuine benefits instead of only chasing late ones." },
      { kind: "tool", slug: "cash-runway", title: "Cash flow runway", why: "Know your survival window so you know how hard you can afford to push." },
    ],
  },
  {
    slug: "stock-eats-cash",
    category: "Money & cash flow",
    symptom: "“All my money is sitting on shelves as unsold stock.”",
    title: "Cash is frozen in inventory",
    description: "Stock is cash wearing a disguise. Find what's frozen, thaw it, and change the buying habits that froze it.",
    steps: [
      { kind: "tool", slug: "inventory-turns", title: "Inventory turns analyzer", why: "Rank every product by how fast it turns — see exactly where cash is stuck." },
      { kind: "framework", slug: "working-capital-allocator", title: "Working capital allocator", why: "Decide deliberately how much capital should be in stock at all." },
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Stop reordering the products that got you here." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Plan the next three months of buying against real sales, not hope." },
    ],
  },
  {
    slug: "emis-eating-profit",
    category: "Money & cash flow",
    symptom: "“Loan EMIs take everything the business earns.”",
    title: "EMIs are eating the business",
    description: "Debt taken in optimism is repaid in stress. Restructure deliberately — duration, cost order, and expenses — before it decides for you.",
    steps: [
      { kind: "framework", slug: "borrowing-readiness", title: "Borrowing readiness check", why: "Get your three debt ratios honestly — know exactly how deep this goes." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "See whether the next quarter clears the EMIs or needs intervention now." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Check if thin margins, not the loan itself, are the real problem." },
      { kind: "tool", slug: "cash-flow-simulator", title: "Cash flow simulator", why: "Model restructuring options — longer duration vs cost cuts — before choosing." },
    ],
  },
  {
    slug: "no-money-to-grow",
    category: "Money & cash flow",
    symptom: "“I can see the opportunity but there's no money to fund it.”",
    title: "Growth opportunity, no capital",
    description: "Before borrowing or raising, find the capital hiding inside the business — then fund the opportunity in the cheapest order.",
    steps: [
      { kind: "framework", slug: "working-capital-allocator", title: "Working capital allocator", why: "Find money sleeping in fixed assets or excess stock first — it's the cheapest capital." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Prove the opportunity clears the return bar before funding it any way at all." },
      { kind: "framework", slug: "borrowing-readiness", title: "Borrowing readiness check", why: "If debt is the answer, confirm the ratios can carry it." },
      { kind: "tool", slug: "cap-table-builder", title: "Cap table builder", why: "If equity is the answer, model the dilution before talking to anyone." },
    ],
  },
  {
    slug: "festival-season-cash-crunch",
    category: "Money & cash flow",
    symptom: "“Every festival season we're scrambling for stock money.”",
    title: "The seasonal stock-money scramble",
    description: "The crunch repeats every year on schedule — so plan for it on schedule. Build the season's funding plan months before, not weeks.",
    steps: [
      { kind: "tool", slug: "cash-flow-simulator", title: "Cash flow simulator", why: "Model the season month by month — the crunch date becomes visible far in advance." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Turn the model into a concrete 90-day pre-season plan." },
      { kind: "tool", slug: "inventory-turns", title: "Inventory turns analyzer", why: "Buy the fast movers deep and stop tying season money in slow ones." },
      { kind: "framework", slug: "borrowing-readiness", title: "Borrowing readiness check", why: "If seasonal credit is needed, arrange it early on good terms, not late on desperate ones." },
    ],
  },
  {
    slug: "thinking-of-taking-loan",
    category: "Money & cash flow",
    symptom: "“I'm considering a business loan but not sure it's wise.”",
    title: "Should I take this loan?",
    description: "A loan is fuel or fire depending on three ratios and one honest question: is this funding growth, or funding losses?",
    steps: [
      { kind: "framework", slug: "borrowing-readiness", title: "Borrowing readiness check", why: "Run the three ratios lenders check — before they do." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Confirm what the loan funds earns more than the loan costs." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Check the EMIs fit inside real monthly cash flow, not optimistic cash flow." },
      { kind: "framework", slug: "value-at-risk", title: "Value at risk", why: "Write down the worst case before signing — fear shrinks when it has a number." },
    ],
  },
  {
    slug: "where-did-profit-go",
    category: "Money & cash flow",
    symptom: "“The P&L says we made money. The bank account disagrees.”",
    title: "Profit on paper, no cash in bank",
    description: "Profit is an opinion; cash is a fact. Trace where the paper profit actually went — receivables, stock, or repayments.",
    steps: [
      { kind: "tool", slug: "cash-runway", title: "Cash flow runway", why: "Start from the bank balance truth, not the P&L story." },
      { kind: "tool", slug: "inventory-turns", title: "Inventory turns analyzer", why: "Check if profit turned into stock sitting on shelves." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Map collections against payments to find the timing gap." },
      { kind: "framework", slug: "working-capital-allocator", title: "Working capital allocator", why: "See if profit got absorbed into fixed assets or capital purchases." },
    ],
  },
  {
    slug: "personal-business-money-mixed",
    category: "Money & cash flow",
    symptom: "“Business money and house money are the same pocket — and both feel empty.”",
    title: "Personal and business money are tangled",
    description: "Mixed money means you can't see whether the business actually works. Separate first, then judge the business on its own numbers.",
    steps: [
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Compute the business's real margins with a proper owner salary counted as a cost." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Run business cash separately for 90 days — the clarity is immediate." },
      { kind: "framework", slug: "passive-income-score", title: "Passive income score", why: "Score how dependent the business is on you personally — money mixing usually mirrors role mixing." },
      { kind: "tool", slug: "cash-runway", title: "Cash flow runway", why: "Establish the business's own survival number, independent of household needs." },
    ],
  },
  {
    slug: "big-order-cant-fund-it",
    category: "Money & cash flow",
    symptom: "“We won a huge order and now I'm not sure we can afford to deliver it.”",
    title: "The big order we can't afford to fulfil",
    description: "Big orders sink businesses through the funding gap between buying materials and getting paid. Bridge the gap deliberately before saying yes.",
    steps: [
      { kind: "tool", slug: "cash-flow-simulator", title: "Cash flow simulator", why: "Model the order month by month — outflows first, payment later — and find the gap." },
      { kind: "framework", slug: "value-at-risk", title: "Value at risk", why: "Know the worst case if the client delays or defaults before committing." },
      { kind: "framework", slug: "borrowing-readiness", title: "Borrowing readiness check", why: "If bridge financing is needed, verify you can carry it." },
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Negotiate advance and milestone payments framed around their interests." },
    ],
  },
  {
    slug: "business-survives-month-to-month",
    category: "Money & cash flow",
    symptom: "“We're never more than one bad month from real trouble.”",
    title: "Living month to month",
    description: "Zero buffer means every surprise is a crisis. Build the cushion deliberately — it's the cheapest insurance a business can buy.",
    steps: [
      { kind: "tool", slug: "cash-runway", title: "Cash flow runway", why: "Face the honest number: how many weeks of survival you actually have." },
      { kind: "framework", slug: "cash-projection", title: "90-day cash projection", why: "Plan three months ahead so problems arrive with warning." },
      { kind: "framework", slug: "critical-success-factors", title: "Critical success factors", why: "Pick the one or two numbers that most directly build the buffer, and track them weekly." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Find the margin leak that keeps the buffer from ever forming." },
    ],
  },
];
