import type { Journey } from "./journeys";

export const JOURNEYS_3: Journey[] = [
  // ================= CUSTOMERS & RETENTION =================
  {
    slug: "complaints-rising",
    category: "Customers & retention",
    symptom: "“Complaints are climbing and we're always firefighting.”",
    title: "Complaints keep rising",
    description: "Rising complaints are a system signal, not a customer problem. Find the recurring cause, fix the process, then move from reacting to anticipating.",
    steps: [
      { kind: "framework", slug: "service-ladder", title: "Service maturity ladder", why: "Locate honestly which service stage you're at — most complaint spirals live at stage two." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Find which specific touchpoint generates the most complaints." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Fix the recurring cause with a documented process, not repeated apologies." },
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Measure whether the fixes are actually moving customer sentiment." },
    ],
  },
  {
    slug: "customers-ghost-after-quote",
    category: "Customers & retention",
    symptom: "“They ask for a quote, we send it, then — silence forever.”",
    title: "Customers ghost after the quote",
    description: "Ghosting after a quote means something in the quote — price, trust, or clarity — raised a doubt nobody voiced. Close the gap and the loop.",
    steps: [
      { kind: "framework", slug: "bant-lead-scoring", title: "BANT lead scoring", why: "Qualify before quoting — half of ghosting is quoting people who could never buy." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Send proof with the price — a naked number invites silent comparison shopping." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Build the post-quote follow-up sequence so silence gets answered systematically." },
      { kind: "tool", slug: "pricing-strategy", title: "Pricing strategy picker", why: "Restructure the quote itself — options and anchors beat one take-it-or-leave-it number." },
    ],
  },
  {
    slug: "one-bad-review-hurt-us",
    category: "Customers & retention",
    symptom: "“One angry public review is scaring off new customers.”",
    title: "A bad review is doing real damage",
    description: "You can't delete it, but you can bury it under genuine proof and fix what caused it. Respond once, well — then build the review engine you should have had.",
    steps: [
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Fix the actual failure the review exposed — or it will repeat." },
      { kind: "framework", slug: "credibility-5r", title: "Credibility ladder", why: "Systematically collect the positive reviews your happy customers never left." },
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Catch unhappy customers privately before they go public next time." },
      { kind: "framework", slug: "thoughtful-response", title: "Response over reaction", why: "Craft the one public reply calmly — future customers read your response more than the review." },
    ],
  },
  {
    slug: "no-idea-what-customers-think",
    category: "Customers & retention",
    symptom: "“Honestly, I have no idea if customers are happy or just quiet.”",
    title: "Flying blind on customer sentiment",
    description: "Silence isn't satisfaction. Build a simple, regular listening system before the first surprise departure teaches you the hard way.",
    steps: [
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Start with the one question that predicts loyalty best." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Score yourself first, then compare against what customers actually say." },
      { kind: "framework", slug: "service-ladder", title: "Service maturity ladder", why: "Check whether unhappy customers even have a way to reach you." },
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "For key accounts, understand their world well enough to sense trouble early." },
    ],
  },
  {
    slug: "big-customers-drifting-away",
    category: "Customers & retention",
    symptom: "“Our oldest, biggest customers are ordering less and less.”",
    title: "Key customers are drifting away",
    description: "Big accounts rarely leave suddenly — they fade while nobody's watching. Re-engage deliberately before the fade completes.",
    steps: [
      { kind: "framework", slug: "customer-money-model", title: "Customer's money model", why: "Re-learn their business — drift often means their needs moved and you didn't." },
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "Quantify what losing each account really costs — it justifies serious retention effort." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Deepen the relationship structurally, not just with a discount visit." },
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Ask them directly and formally — key accounts often tell you exactly why, if asked." },
    ],
  },
  {
    slug: "service-cant-keep-up",
    category: "Customers & retention",
    symptom: "“We're growing, but service quality is visibly slipping.”",
    title: "Growth is breaking our service",
    description: "Service that lived in a few good people's effort doesn't survive scale. Systematise the service before growth finishes breaking it.",
    steps: [
      { kind: "framework", slug: "service-ladder", title: "Service maturity ladder", why: "Diagnose which stage broke — capture, resolution, or anticipation." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Document the service standards that used to live in individual judgment." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Check the service team's capability actually matches the new volume." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Track response and resolution times weekly so slippage is visible immediately." },
    ],
  },
  {
    slug: "no-loyalty-program-works",
    category: "Customers & retention",
    symptom: "“We tried points and cards — nobody cares about our loyalty program.”",
    title: "The loyalty program nobody uses",
    description: "Loyalty programs fail when they reward transactions instead of the relationship. Rebuild it around what your customers actually value.",
    steps: [
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Find out what your promoters actually love — build the program around that." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Choose the right switching cost for your category — points are only one of ten." },
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "Size the reward budget from real lifetime value, not marketing hope." },
      { kind: "framework", slug: "consumer-shift", title: "Consumer behaviour shift", why: "Check whether the reward your program offers matches what customers now want." },
    ],
  },
  {
    slug: "winning-new-losing-old",
    category: "Customers & retention",
    symptom: "“We're great at winning customers and terrible at keeping them.”",
    title: "A leaky bucket business",
    description: "Acquisition covering for churn is running up a down escalator. Fix retention first — it's cheaper than any campaign you'll ever run.",
    steps: [
      { kind: "tool", slug: "customer-lifetime", title: "Customer lifetime value", why: "See what churn actually costs against what acquisition actually costs." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Find where the experience breaks after the sale — that's where the bucket leaks." },
      { kind: "framework", slug: "nps-engine", title: "Recommendation score engine", why: "Identify at-risk customers while they're still saveable." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Give staying a structural advantage over leaving." },
    ],
  },

  // ================= TEAM & HIRING =================
  {
    slug: "team-lacks-ownership",
    category: "Team & hiring",
    symptom: "“Everyone does their tasks; nobody owns outcomes.”",
    title: "Tasks get done, nothing gets owned",
    description: "Ownership isn't a personality trait you hire — it's a structure you build: clear outcomes, real authority, and a scoreboard.",
    steps: [
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Match your best people to the activities that actually matter most." },
      { kind: "framework", slug: "mcd-leadership-check", title: "MCD leadership check", why: "Check if you're managing people who should be coached, and coaching people ready to own." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Give each outcome a visible number and a name next to it." },
      { kind: "framework", slug: "performance-culture", title: "High-performance story", why: "Give the team the why — ownership without meaning doesn't last." },
    ],
  },
  {
    slug: "key-person-might-leave",
    category: "Team & hiring",
    symptom: "“If my best person resigns tomorrow, we're in serious trouble.”",
    title: "One resignation from crisis",
    description: "Key-person risk has two fixes that work together: make them want to stay, and make the business survivable if they don't.",
    steps: [
      { kind: "framework", slug: "stay-interview-plan", title: "Stay interview plan", why: "Have the stay conversation now, while there's still time to act on what you hear." },
      { kind: "framework", slug: "navratna-mentoring", title: "Gem cultivation", why: "Invest in their growth visibly — people leave stagnation more than salaries." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Get their critical knowledge out of their head and into documents." },
      { kind: "framework", slug: "esop-designer", title: "Ownership pool designer", why: "Consider real ownership — the strongest stay reason money can structure." },
    ],
  },
  {
    slug: "attrition-is-high",
    category: "Team & hiring",
    symptom: "“People keep leaving within a year and I keep re-hiring.”",
    title: "The revolving door team",
    description: "High attrition is expensive feedback. Find the real reason people leave, fix it, and stop paying the rehiring tax.",
    steps: [
      { kind: "framework", slug: "stay-interview-plan", title: "Stay interview plan", why: "Ask the ones still here what would make them leave — before they do." },
      { kind: "framework", slug: "talent-engagement", title: "Engagement lift plan", why: "Score engagement honestly and pick deliberate moves to lift it." },
      { kind: "tool", slug: "hiring-scorecard", title: "Hiring scorecard", why: "Check whether the leaving pattern starts with who you're hiring." },
      { kind: "framework", slug: "performance-culture", title: "High-performance story", why: "Give people a story worth staying for, not just a salary worth comparing." },
    ],
  },
  {
    slug: "team-conflicts-draining-me",
    category: "Team & hiring",
    symptom: "“Half my week goes into refereeing conflicts between people.”",
    title: "Team conflicts eat my week",
    description: "Chronic conflict usually means unclear ownership, avoided conversations, or a hire that shouldn't have happened. Address the structure, not just the incidents.",
    steps: [
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Check if role overlap and unclear ownership are manufacturing the conflicts." },
      { kind: "framework", slug: "change-conversation", title: "Change conversation planner", why: "Have the direct conversation with the recurring source, structured and calm." },
      { kind: "framework", slug: "thoughtful-response", title: "Response over reaction", why: "Fix your own reaction pattern first — teams mirror the founder's conflict style." },
      { kind: "framework", slug: "core-values", title: "Core value charter", why: "Set the behavioural line — what's debated openly vs what's never acceptable." },
    ],
  },
  {
    slug: "cant-afford-good-talent",
    category: "Team & hiring",
    symptom: "“The people I want cost more than I can pay.”",
    title: "Good talent is out of budget",
    description: "You can't outbid big companies on salary — so compete on ownership, growth, and meaning, and hire potential instead of pedigree.",
    steps: [
      { kind: "tool", slug: "hiring-scorecard", title: "Hiring scorecard", why: "Define outcomes precisely — high-potential people beat expensive résumés on real scorecards." },
      { kind: "framework", slug: "esop-designer", title: "Ownership pool designer", why: "Offer upside you can afford — a share of growth instead of salary you can't." },
      { kind: "framework", slug: "navratna-mentoring", title: "Gem cultivation", why: "Grow your own stars — a deliberate development path attracts ambitious underdogs." },
      { kind: "framework", slug: "performance-culture", title: "High-performance story", why: "Sell the mission and growth — the currencies big companies struggle to print." },
    ],
  },
  {
    slug: "new-hires-take-too-long",
    category: "Team & hiring",
    symptom: "“Every new person takes six months to be actually useful.”",
    title: "New hires ramp painfully slowly",
    description: "Slow ramp isn't a talent problem — it's an onboarding gap. Structure the first 30 days and watch the six months collapse.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Document the core processes new people currently learn by osmosis." },
      { kind: "framework", slug: "training-evaluation", title: "Training that sticks", why: "Train against measurable skill gaps with a real before/after check." },
      { kind: "framework", slug: "mcd-leadership-check", title: "MCD leadership check", why: "Manage closely early, coach deliberately, then release — in that order." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Give new hires visible daily numbers so progress is obvious to them and you." },
    ],
  },
  {
    slug: "team-resists-change",
    category: "Team & hiring",
    symptom: "“Every new idea meets 'but we've always done it this way'.”",
    title: "The team resists every change",
    description: "Resistance is rarely stubbornness — it's unconvinced self-interest. Show each person what the change means for them, and involve them in shaping it.",
    steps: [
      { kind: "framework", slug: "change-conversation", title: "Change conversation planner", why: "Structure the case person by person — their gains, their costs, honestly." },
      { kind: "framework", slug: "performance-culture", title: "High-performance story", why: "Wrap the change in a story worth believing, retold weekly." },
      { kind: "framework", slug: "consumer-shift", title: "Consumer behaviour shift", why: "Show the market evidence — external reality persuades better than internal authority." },
      { kind: "framework", slug: "speed-resolution", title: "Resolution accelerator", why: "Convert agreement into immediate visible action before momentum dies." },
    ],
  },
  {
    slug: "no-second-line-leadership",
    category: "Team & hiring",
    symptom: "“There's me, and then there's everyone waiting for my instructions.”",
    title: "No second line of leadership",
    description: "A business with one decision-maker has one point of failure. Deliberately grow two or three people who can carry real decisions.",
    steps: [
      { kind: "framework", slug: "navratna-mentoring", title: "Gem cultivation", why: "Pick your highest-potential person and start a structured mentoring rhythm." },
      { kind: "framework", slug: "mcd-leadership-check", title: "MCD leadership check", why: "Move your best people deliberately from managed to coached to delegated." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Map who could own each critical activity with the right development." },
      { kind: "framework", slug: "esop-designer", title: "Ownership pool designer", why: "Back future leaders with real skin in the game." },
    ],
  },

  // ================= OPERATIONS & SYSTEMS =================
  {
    slug: "everything-is-urgent",
    category: "Operations & systems",
    symptom: "“Every day is firefighting; nothing important ever gets time.”",
    title: "Everything is always urgent",
    description: "Permanent urgency means missing systems, not bad luck. Find the recurring fires, build the process that prevents each, and reclaim the calendar.",
    steps: [
      { kind: "framework", slug: "main-thing-calendar", title: "Main-thing calendar", why: "Protect the important hours first — firefighting expands to fill whatever you leave open." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Turn the three most recurring fires into documented processes that prevent them." },
      { kind: "framework", slug: "critical-success-factors", title: "Critical success factors", why: "Decide what actually matters so urgency stops outranking importance by default." },
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "Route entire categories of fires to someone who isn't you." },
    ],
  },
  {
    slug: "quality-inconsistent",
    category: "Operations & systems",
    symptom: "“Some days our output is excellent; some days it's embarrassing.”",
    title: "Quality is a coin flip",
    description: "Inconsistency means quality depends on who's working and how their day is going. Standardise the process so the floor rises to meet the ceiling.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Document what 'done correctly' looks like for the core process." },
      { kind: "framework", slug: "training-evaluation", title: "Training that sticks", why: "Close the specific skill gaps behind the bad days." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Track quality daily so drift shows up in numbers before customers see it." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Confirm the right people are on the activities where consistency matters most." },
    ],
  },
  {
    slug: "too-many-mistakes-rework",
    category: "Operations & systems",
    symptom: "“We do everything twice — once wrong, then again right.”",
    title: "Mistakes and rework everywhere",
    description: "Rework is a hidden tax on every order. Find where errors enter the process, add the checkpoint there, and stop paying twice.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Add quality checkpoints inside the process, not just inspection at the end." },
      { kind: "framework", slug: "critical-success-factors", title: "Critical success factors", why: "Make error rate one of your two or three tracked numbers." },
      { kind: "framework", slug: "training-evaluation", title: "Training that sticks", why: "Fix the skill gaps producing the same mistake repeatedly." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Price the rework honestly — seeing its margin cost funds the fix." },
    ],
  },
  {
    slug: "deliveries-always-late",
    category: "Operations & systems",
    symptom: "“We promise a date, then miss it — again.”",
    title: "Deliveries are always late",
    description: "Chronic lateness has one bottleneck causing most of it. Find that constraint, fix it first, and build honest buffers into promises.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Map the delivery process step by step — the bottleneck becomes visible." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Track on-time percentage weekly — what's measured stops slipping silently." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Check whether the constraint is a person, a process, or capacity." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Repair the communication around delays while you fix the delays themselves." },
    ],
  },
  {
    slug: "no-processes-documented",
    category: "Operations & systems",
    symptom: "“Everything lives in people's heads — nothing is written anywhere.”",
    title: "Zero documented processes",
    description: "Undocumented process is risk wearing a familiar face. Start with the three processes that would hurt most to lose, and write them this week.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Document the single most critical process first — momentum comes from finishing one." },
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "List what only exists in your head — that's the priority documentation queue." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Identify which person's departure would hurt most — document their work next." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Build the review rhythm that keeps documents alive instead of forgotten." },
    ],
  },
  {
    slug: "drowning-in-manual-work",
    category: "Operations & systems",
    symptom: "“We type the same things into three registers and two apps, daily.”",
    title: "Drowning in manual, repeated work",
    description: "Repeated manual work is a queue of automation and elimination candidates. Map it, cut what's pointless, systematise the rest.",
    steps: [
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "List a week of tasks honestly — elimination candidates jump out immediately." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Standardise the process first — you can only automate what's defined." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Price the top automation candidate against the hours it frees." },
      { kind: "framework", slug: "main-thing-calendar", title: "Main-thing calendar", why: "Reinvest the freed hours deliberately before busywork reclaims them." },
    ],
  },

  // ================= COMPETITION & STRATEGY =================
  {
    slug: "new-competitor-undercutting",
    category: "Competition & strategy",
    symptom: "“A new player entered at prices that make no sense.”",
    title: "A new competitor is undercutting everyone",
    description: "Don't match unsustainable prices — outlast them. Deepen what price can't buy: relationships, proof, and switching costs.",
    steps: [
      { kind: "tool", slug: "competitor-matrix", title: "Competitor comparison matrix", why: "Map where they're genuinely strong vs just cheap — fight on your strong ground." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Lock in existing customers with value that survives a price comparison." },
      { kind: "tool", slug: "advantage-test", title: "Advantage stress test", why: "Confirm which of your advantages actually hold under this pressure." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Know your own floor — decide response with numbers, not panic." },
    ],
  },
  {
    slug: "market-is-shrinking",
    category: "Competition & strategy",
    symptom: "“Our whole category is slowly declining and we're declining with it.”",
    title: "The market itself is shrinking",
    description: "You can't out-execute a dying market — but you can reposition toward where the demand went, before the decline finishes the decision for you.",
    steps: [
      { kind: "framework", slug: "consumer-shift", title: "Consumer behaviour shift", why: "Name precisely where the demand moved — it rarely vanishes, it relocates." },
      { kind: "framework", slug: "non-customer-expansion", title: "Non-customer expansion", why: "Find who still needs the underlying outcome but buys it differently now." },
      { kind: "tool", slug: "business-model-canvas", title: "Business model canvas", why: "Redesign the model around the new reality, not a patched version of the old one." },
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Test the new direction in one contained segment before betting the business." },
    ],
  },
  {
    slug: "dont-know-where-to-focus",
    category: "Competition & strategy",
    symptom: "“Products, markets, channels — I genuinely don't know what to prioritise.”",
    title: "Too many directions, no focus",
    description: "Strategy is choosing what not to do. Force the ranking with honest criteria, pick two priorities, and park the rest guilt-free.",
    steps: [
      { kind: "tool", slug: "swot-builder", title: "SWOT builder", why: "Lay out the honest position first — focus chosen blind is just guessing." },
      { kind: "framework", slug: "critical-success-factors", title: "Critical success factors", why: "Pick the two or three factors with 5-10x potential — everything else waits." },
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Rebuild from the perfect customer outward — focus follows clarity." },
      { kind: "framework", slug: "seven-step-goals", title: "Seven-step goal system", why: "Convert the chosen focus into a goal with rituals and review." },
    ],
  },
  {
    slug: "me-too-business-no-differentiation",
    category: "Competition & strategy",
    symptom: "“Honestly, we do exactly what fifty other businesses here do.”",
    title: "We're a me-too business",
    description: "Sameness makes price the only argument. Build one genuine difference customers can name — then make everything point at it.",
    steps: [
      { kind: "tool", slug: "competitor-matrix", title: "Competitor comparison matrix", why: "Map the whole field — differentiation starts with seeing the sameness clearly." },
      { kind: "framework", slug: "perfect-strategy", title: "The five perfects", why: "Choose one positioning word to own — from the customer's view, not yours." },
      { kind: "tool", slug: "moat-builder", title: "Moat builder", why: "Pick the one barrier you'll actually build this quarter." },
      { kind: "framework", slug: "positioning-statement", title: "Positioning rewrite", why: "Announce the difference so the market files you differently." },
    ],
  },
  {
    slug: "big-player-entered-market",
    category: "Competition & strategy",
    symptom: "“A national brand just opened in our market.”",
    title: "A giant just entered my market",
    description: "You can't beat a giant at scale — beat them at closeness. Speed, relationships, and local depth are structurally hard for giants to copy.",
    steps: [
      { kind: "tool", slug: "competitor-matrix", title: "Competitor comparison matrix", why: "Map their real strengths and their structural blind spots — giants have both." },
      { kind: "framework", slug: "switching-barriers", title: "Switching barrier designer", why: "Deepen existing relationships before the giant's launch offers reach them." },
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Dominate the specific niches too small or specific for the giant to serve well." },
      { kind: "framework", slug: "cx-touchpoints", title: "Experience touchpoint audit", why: "Win on the personal experience a national chain can't replicate locally." },
    ],
  },

  // ================= GROWTH & EXPANSION =================
  {
    slug: "ready-for-second-location",
    category: "Growth & expansion",
    symptom: "“The first location works — I think it's time for a second.”",
    title: "Opening the second location",
    description: "The second location tests whether you built a business or a well-run job. Prove the model is documented and funded before signing anything.",
    steps: [
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "The first location must run on documents, not on you, before you split your attention." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Confirm location one's real profitability — expansion multiplies whatever exists." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Run location two's numbers as an investment, not an ambition." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Name who runs location one when you're at location two." },
    ],
  },
  {
    slug: "want-to-go-online",
    category: "Growth & expansion",
    symptom: "“Our offline business works — now everyone says go online.”",
    title: "Taking the business online",
    description: "Online isn't a channel you add — it's a different economics you enter. Test small, measure the real costs, then scale what proves out.",
    steps: [
      { kind: "tool", slug: "business-model-canvas", title: "Business model canvas", why: "Map the online model separately — costs, channels, and margins all change." },
      { kind: "framework", slug: "pilot-market", title: "Pilot market qualifier", why: "Start with one product line and one channel, not the whole catalogue everywhere." },
      { kind: "tool", slug: "acquisition-cost", title: "Acquisition cost auditor", why: "Measure digital acquisition cost from the first week — it decides everything online." },
      { kind: "framework", slug: "content-engine", title: "Content engine setup", why: "Build the content system online demand depends on." },
    ],
  },
  {
    slug: "new-product-line-idea",
    category: "Growth & expansion",
    symptom: "“I have an idea for a new product line — should we do it?”",
    title: "The new product line decision",
    description: "New lines fail from weak demand proof, not weak ideas. Validate demand and portfolio fit before committing money.",
    steps: [
      { kind: "framework", slug: "portfolio-audit", title: "Product portfolio audit", why: "Check the current portfolio first — does it need a new line or a cleanup?" },
      { kind: "framework", slug: "non-customer-expansion", title: "Non-customer expansion", why: "Test whether the idea unlocks blocked demand or just adds a variant." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Run the honest investment math including your time." },
      { kind: "framework", slug: "value-at-risk", title: "Value at risk", why: "Cap the downside — pilot batch, not full production." },
    ],
  },
  {
    slug: "scaling-breaks-quality",
    category: "Growth & expansion",
    symptom: "“Every time we grow, something breaks — quality, service, or the team.”",
    title: "Growth keeps breaking things",
    description: "Each growth spurt exposes the next weakest system. Find what breaks at double the volume, and reinforce it before doubling.",
    steps: [
      { kind: "framework", slug: "scale-up-plan", title: "Scale-up trio", why: "Balance speed, scalability, and sustainability — breakage means one is over-indexed." },
      { kind: "framework", slug: "sop-builder", title: "SOP builder", why: "Systematise the last thing that broke — it's telling you where the gap is." },
      { kind: "framework", slug: "capable-manpower", title: "Critical capability map", why: "Check whether the team's capability grew with the volume." },
      { kind: "framework", slug: "execution-scoreboard", title: "Execution scoreboard", why: "Track quality alongside growth so trouble shows up in the same dashboard." },
    ],
  },
  {
    slug: "need-investment-to-grow",
    category: "Growth & expansion",
    symptom: "“We're thinking about raising money or taking on a partner.”",
    title: "Raising money or taking a partner",
    description: "Capital costs equity or interest, and both cost freedom. Know your numbers, your dilution, and your walk-away terms before the first meeting.",
    steps: [
      { kind: "tool", slug: "business-model-canvas", title: "Business model canvas", why: "Get the model onto one page — the first thing any serious investor probes." },
      { kind: "framework", slug: "profit-ratios", title: "Profit ratio snapshot", why: "Know your real margins cold — credibility dies on fuzzy numbers." },
      { kind: "tool", slug: "cap-table-builder", title: "Cap table builder", why: "Model the dilution scenarios before anyone proposes one to you." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Be precise about what the money buys and what it returns — vagueness kills deals." },
    ],
  },

  // ================= FOUNDER & PERSONAL =================
  {
    slug: "burning-out",
    category: "Founder & personal",
    symptom: "“I'm exhausted, snapping at people, and dreading Mondays.”",
    title: "I think I'm burning out",
    description: "Burnout is a system problem showing up in a person. Reduce the load structurally, recover deliberately, and rebuild the reason you started.",
    steps: [
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "Cut the load first — recovery can't outpace an impossible workload." },
      { kind: "framework", slug: "main-thing-calendar", title: "Main-thing calendar", why: "Rebuild the week with recovery and focus protected, not leftover." },
      { kind: "framework", slug: "solitude-ritual", title: "Sixty-minute solitude", why: "Reinstall daily thinking space — burnout thrives on reactive noise." },
      { kind: "framework", slug: "mighty-why", title: "The mighty why", why: "Reconnect with the reason — exhaustion with meaning is recoverable; without it, it isn't." },
    ],
  },
  {
    slug: "lost-motivation",
    category: "Founder & personal",
    symptom: "“The business is fine. I just don't feel anything about it anymore.”",
    title: "The fire has gone out",
    description: "Numbness usually means the challenge is gone or the meaning is. Diagnose which, then either raise the game or reconnect the purpose.",
    steps: [
      { kind: "framework", slug: "mighty-why", title: "The mighty why", why: "Check whether the original why still exists — or needs rewriting for who you are now." },
      { kind: "tool", slug: "goal-arrow", title: "Goal arrow", why: "Set a goal that genuinely stretches you — boredom is often mastery without a next mountain." },
      { kind: "framework", slug: "seven-step-goals", title: "Seven-step goal system", why: "Structure the new challenge with rituals so momentum doesn't depend on mood." },
      { kind: "framework", slug: "passive-income-score", title: "Passive income score", why: "If the answer is stepping back, check how ready the business is to let you." },
    ],
  },
  {
    slug: "cant-make-decisions",
    category: "Founder & personal",
    symptom: "“I keep postponing big decisions and it's costing us.”",
    title: "Frozen on big decisions",
    description: "Chronic indecision is usually a missing frame, not missing courage. Structure the choice, cap the downside, and give yourself a deadline.",
    steps: [
      { kind: "tool", slug: "swot-builder", title: "SWOT builder", why: "Lay the situation out visually — half of paralysis is holding it all in your head." },
      { kind: "framework", slug: "value-at-risk", title: "Value at risk", why: "Put a number on the worst case — fear shrinks when quantified." },
      { kind: "framework", slug: "roi-check", title: "Project ROI check", why: "Compare the options on return, not on anxiety." },
      { kind: "framework", slug: "speed-resolution", title: "Resolution accelerator", why: "Convert the decision into action within 24 hours, with support recruited." },
    ],
  },
  {
    slug: "no-worklife-balance",
    category: "Founder & personal",
    symptom: "“My family has started introducing me as 'the one who's always working'.”",
    title: "The business owns my whole life",
    description: "The business takes what you let it. Draw the lines structurally — delegation, boundaries, and a calendar that includes your life.",
    steps: [
      { kind: "framework", slug: "main-thing-calendar", title: "Main-thing calendar", why: "Put family and health into the calendar first — as fixed as any client meeting." },
      { kind: "framework", slug: "replace-yourself", title: "Replace yourself", why: "Hand off what's keeping you at the shop after everyone else left." },
      { kind: "framework", slug: "passive-income-score", title: "Passive income score", why: "Score how much the business genuinely needs your presence vs how much it's habit." },
      { kind: "framework", slug: "mighty-why", title: "The mighty why", why: "Remember what the business was supposed to buy you — probably not this." },
    ],
  },
];
