import type { DocTemplate } from "./knowledgeTypes";

export const TEMPLATES: DocTemplate[] = [
  {
    slug: "job-offer-letter",
    title: "Job offer letter",
    category: "People",
    description: "A starting draft for offering a role to a candidate — role, compensation, and start date, in a clear, professional format.",
    blocks: [
      { type: "field", label: "Company name" },
      { type: "field", label: "Candidate name" },
      { type: "field", label: "Role / designation" },
      { type: "field", label: "Reporting to" },
      { type: "field", label: "Annual compensation (CTC)" },
      { type: "field", label: "Proposed start date" },
      { type: "clause", heading: "Offer", text: "We are pleased to offer you the position stated above. This letter sets out the key terms of your employment; a detailed appointment letter and employment agreement will follow separately." },
      { type: "field", label: "Probation period (if any)", placeholder: "e.g. 3 months" },
      { type: "field", label: "Notice period", placeholder: "e.g. 30 days" },
      { type: "clause", heading: "Acceptance", text: "Please confirm your acceptance of this offer by signing and returning a copy of this letter by the date specified below." },
      { type: "field", label: "Response deadline" },
      { type: "field", label: "Authorised signatory name & title" },
    ],
  },
  {
    slug: "mutual-nda",
    title: "Mutual non-disclosure agreement",
    category: "Legal",
    description: "A starting draft for a two-way confidentiality agreement before sharing sensitive business information with a partner, vendor, or prospective hire.",
    blocks: [
      { type: "field", label: "Party 1 (name & address)" },
      { type: "field", label: "Party 2 (name & address)" },
      { type: "field", label: "Effective date" },
      { type: "clause", heading: "Purpose", text: "The parties wish to explore a potential business relationship and, in connection with that opportunity, may disclose confidential information to each other that each party wishes to protect." },
      { type: "field", label: "Purpose of disclosure (one line)", placeholder: "e.g. evaluating a potential supply partnership" },
      { type: "clause", heading: "Confidentiality obligation", text: "Each party agrees to use the other's confidential information only for the stated purpose, to protect it with reasonable care, and not to disclose it to any third party without prior written consent." },
      { type: "field", label: "Confidentiality period", placeholder: "e.g. 2 years from disclosure" },
      { type: "clause", heading: "Exclusions", text: "Confidential information does not include information that is already public, was already known to the receiving party, or is independently developed without reference to the disclosed information." },
      { type: "field", label: "Governing law / jurisdiction" },
    ],
  },
  {
    slug: "invoice-template",
    title: "Invoice",
    category: "Finance",
    description: "A clean, fillable invoice layout for billing a customer or client.",
    blocks: [
      { type: "field", label: "Your business name & address" },
      { type: "field", label: "Bill to (customer name & address)" },
      { type: "field", label: "Invoice number" },
      { type: "field", label: "Invoice date" },
      { type: "field", label: "Payment due date" },
      { type: "field", label: "Items / services (description, quantity, rate)", multiline: true },
      { type: "field", label: "Subtotal" },
      { type: "field", label: "Tax (if applicable)" },
      { type: "field", label: "Total amount due" },
      { type: "field", label: "Payment instructions (bank details / UPI)", multiline: true },
      { type: "clause", text: "Thank you for your business. Please reach out with any questions about this invoice." },
    ],
  },
  {
    slug: "vendor-agreement-checklist",
    title: "Vendor agreement checklist",
    category: "Operations",
    description: "A checklist of terms to confirm are covered before signing a vendor or supplier agreement — not a substitute for the agreement itself.",
    blocks: [
      { type: "field", label: "Vendor name" },
      { type: "field", label: "What they're supplying" },
      { type: "clause", heading: "Confirm before signing", text: "Walk through each item below with the vendor before finalising the agreement." },
      { type: "field", label: "Pricing and any volume discounts, in writing" },
      { type: "field", label: "Payment terms (when, how, penalties for late payment)" },
      { type: "field", label: "Delivery / turnaround time commitments" },
      { type: "field", label: "Quality standards and what happens if they're not met" },
      { type: "field", label: "Minimum order quantities, if any" },
      { type: "field", label: "Termination notice period for either party" },
      { type: "field", label: "Who owns any IP or custom work produced" },
      { type: "field", label: "Confidentiality expectations" },
    ],
  },
  {
    slug: "performance-appraisal-form",
    title: "Performance appraisal form",
    category: "People",
    description: "A structured form for a periodic performance review conversation.",
    blocks: [
      { type: "field", label: "Employee name" },
      { type: "field", label: "Role" },
      { type: "field", label: "Review period" },
      { type: "field", label: "Reviewer name" },
      { type: "field", label: "Key achievements this period", multiline: true },
      { type: "field", label: "Areas for improvement", multiline: true },
      { type: "field", label: "Progress against last period's goals", multiline: true },
      { type: "field", label: "Goals for next period", multiline: true },
      { type: "field", label: "Overall rating / summary" },
      { type: "field", label: "Employee comments", multiline: true },
      { type: "field", label: "Signatures & date" },
    ],
  },
  {
    slug: "exit-interview-record",
    title: "Exit interview record",
    category: "People",
    description: "A structured record of a departing employee's exit conversation, useful for spotting patterns across multiple exits.",
    blocks: [
      { type: "field", label: "Employee name" },
      { type: "field", label: "Role & department" },
      { type: "field", label: "Last working day" },
      { type: "field", label: "Reason given for leaving", multiline: true },
      { type: "field", label: "What they liked most about working here", multiline: true },
      { type: "field", label: "What they liked least", multiline: true },
      { type: "field", label: "Thoughts on management and culture", multiline: true },
      { type: "field", label: "Would they recommend working here? Why or why not?", multiline: true },
      { type: "field", label: "Suggestions for improvement", multiline: true },
      { type: "field", label: "Interviewer name & date" },
    ],
  },
  {
    slug: "partnership-term-sheet",
    title: "Partnership term sheet",
    category: "Legal",
    description: "A starting draft to outline the key commercial terms of a business partnership before formal legal agreements are drawn up.",
    blocks: [
      { type: "field", label: "Partner 1 (name & entity)" },
      { type: "field", label: "Partner 2 (name & entity)" },
      { type: "field", label: "Purpose of the partnership" },
      { type: "field", label: "Ownership / revenue split" },
      { type: "field", label: "Capital or resources each partner contributes", multiline: true },
      { type: "field", label: "Roles and responsibilities of each partner", multiline: true },
      { type: "field", label: "Decision-making process for major decisions" },
      { type: "field", label: "How profits and losses are shared" },
      { type: "field", label: "Exit terms — what happens if one partner wants out" },
      { type: "field", label: "Dispute resolution approach" },
      { type: "clause", text: "This term sheet is intended to record commercial intent only and should be converted into a formal partnership agreement by a qualified professional before either party acts on it." },
    ],
  },
  {
    slug: "client-proposal",
    title: "Client proposal",
    category: "Sales",
    description: "A structured layout for proposing a project or engagement to a prospective client.",
    blocks: [
      { type: "field", label: "Client name" },
      { type: "field", label: "Prepared by" },
      { type: "field", label: "Date" },
      { type: "field", label: "Client's problem or goal, as you understand it", multiline: true },
      { type: "field", label: "Proposed approach / solution", multiline: true },
      { type: "field", label: "Scope of work — what's included", multiline: true },
      { type: "field", label: "Timeline and key milestones", multiline: true },
      { type: "field", label: "Investment / pricing" },
      { type: "field", label: "What's not included (out of scope)", multiline: true },
      { type: "field", label: "Next steps" },
    ],
  },
  {
    slug: "vendor-purchase-order",
    title: "Purchase order",
    category: "Operations",
    description: "A formal record of what's being ordered from a vendor, at what price and terms.",
    blocks: [
      { type: "field", label: "Purchase order number" },
      { type: "field", label: "Date" },
      { type: "field", label: "Vendor name & address" },
      { type: "field", label: "Ship / deliver to" },
      { type: "field", label: "Items ordered (description, quantity, unit price)", multiline: true },
      { type: "field", label: "Total order value" },
      { type: "field", label: "Required delivery date" },
      { type: "field", label: "Payment terms" },
      { type: "field", label: "Authorised by" },
    ],
  },
];
